// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity.sql

package query

import (
	"context"
	"database/sql"
)

const createActivityLog = `-- name: CreateActivityLog :exec
INSERT INTO activity_logs (level, action, target, description, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateActivityLogParams struct {
	Level       int64
	Action      sql.NullString
	Target      sql.NullString
	Description sql.NullString
	CreatedAt   int64
	UpdatedAt   int64
}

func (q *Queries) CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) error {
	_, err := q.db.ExecContext(ctx, createActivityLog,
		arg.Level,
		arg.Action,
		arg.Target,
		arg.Description,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listRecentActivityLogs = `-- name: ListRecentActivityLogs :many
SELECT id, level, "action", target, description, created_at, updated_at FROM activity_logs ORDER BY created_at DESC, id DESC LIMIT 100
`

func (q *Queries) ListRecentActivityLogs(ctx context.Context) ([]ActivityLog, error) {
	rows, err := q.db.QueryContext(ctx, listRecentActivityLogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityLog
	for rows.Next() {
		var i ActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.Level,
			&i.Action,
			&i.Target,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
