// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: articles.sql

package query

import (
	"context"
)

const getArticleByID = `-- name: GetArticleByID :one
SELECT id, title, slug, content_html, content_type, description, excerpt, meta_description, meta_title, meta_image, source_author, source_url, source_content, status, comment, scheduled_at, scheduled_crosspost_platforms, scheduled_send_newsletter, created_at, updated_at FROM articles WHERE id = ?
`

func (q *Queries) GetArticleByID(ctx context.Context, id int64) (Article, error) {
	row := q.db.QueryRowContext(ctx, getArticleByID, id)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.ContentHtml,
		&i.ContentType,
		&i.Description,
		&i.Excerpt,
		&i.MetaDescription,
		&i.MetaTitle,
		&i.MetaImage,
		&i.SourceAuthor,
		&i.SourceUrl,
		&i.SourceContent,
		&i.Status,
		&i.Comment,
		&i.ScheduledAt,
		&i.ScheduledCrosspostPlatforms,
		&i.ScheduledSendNewsletter,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
