// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: articles_admin.sql

package query

import (
	"context"
	"database/sql"
	"strings"
)

const countAdminArticles = `-- name: CountAdminArticles :one
SELECT COUNT(*) FROM articles
`

func (q *Queries) CountAdminArticles(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdminArticles)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAdminArticlesBySlug = `-- name: CountAdminArticlesBySlug :one
SELECT COUNT(*) FROM articles WHERE slug = ? AND id != ?
`

type CountAdminArticlesBySlugParams struct {
	Slug sql.NullString
	ID   int64
}

// Slug-uniqueness probe (excludeID mirrors where.not(id: id || 0)).
func (q *Queries) CountAdminArticlesBySlug(ctx context.Context, arg CountAdminArticlesBySlugParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdminArticlesBySlug, arg.Slug, arg.ID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAdminArticlesByStatus = `-- name: CountAdminArticlesByStatus :one
SELECT COUNT(*) FROM articles WHERE status = ?
`

func (q *Queries) CountAdminArticlesByStatus(ctx context.Context, status int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdminArticlesByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCommentsForArticles = `-- name: CountCommentsForArticles :many
SELECT commentable_id, COUNT(*) AS comment_count
FROM comments
WHERE commentable_type = 'Article' AND commentable_id IN (/*SLICE:ids*/?)
GROUP BY commentable_id
`

type CountCommentsForArticlesRow struct {
	CommentableID sql.NullInt64
	CommentCount  int64
}

// Admin index comment counts (load_comment_counts: all statuses).
func (q *Queries) CountCommentsForArticles(ctx context.Context, ids []sql.NullInt64) ([]CountCommentsForArticlesRow, error) {
	query := countCommentsForArticles
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountCommentsForArticlesRow
	for rows.Next() {
		var i CountCommentsForArticlesRow
		if err := rows.Scan(&i.CommentableID, &i.CommentCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countSearchAdminArticles = `-- name: CountSearchAdminArticles :one
SELECT COUNT(*) FROM articles
WHERE like(?, title, '\') OR like(?, slug, '\')
   OR like(?, description, '\') OR like(?, content_html, '\')
`

type CountSearchAdminArticlesParams struct {
	LIKE   string
	LIKE_2 string
	LIKE_3 string
	LIKE_4 string
}

func (q *Queries) CountSearchAdminArticles(ctx context.Context, arg CountSearchAdminArticlesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSearchAdminArticles,
		arg.LIKE,
		arg.LIKE_2,
		arg.LIKE_3,
		arg.LIKE_4,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchAdminArticlesByStatus = `-- name: CountSearchAdminArticlesByStatus :one
SELECT COUNT(*) FROM articles
WHERE status = ? AND (like(?, title, '\') OR like(?, slug, '\')
   OR like(?, description, '\') OR like(?, content_html, '\'))
`

type CountSearchAdminArticlesByStatusParams struct {
	Status int64
	LIKE   string
	LIKE_2 string
	LIKE_3 string
	LIKE_4 string
}

func (q *Queries) CountSearchAdminArticlesByStatus(ctx context.Context, arg CountSearchAdminArticlesByStatusParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSearchAdminArticlesByStatus,
		arg.Status,
		arg.LIKE,
		arg.LIKE_2,
		arg.LIKE_3,
		arg.LIKE_4,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createArticle = `-- name: CreateArticle :one
INSERT INTO articles (
  title, slug, content_html, content_type, description, excerpt,
  meta_description, meta_title, meta_image,
  source_author, source_url, source_content,
  status, comment, scheduled_at,
  scheduled_crosspost_platforms, scheduled_send_newsletter,
  created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, title, slug, content_html, content_type, description, excerpt, meta_description, meta_title, meta_image, source_author, source_url, source_content, status, comment, scheduled_at, scheduled_crosspost_platforms, scheduled_send_newsletter, created_at, updated_at
`

type CreateArticleParams struct {
	Title                       sql.NullString
	Slug                        sql.NullString
	ContentHtml                 sql.NullString
	ContentType                 string
	Description                 sql.NullString
	Excerpt                     sql.NullString
	MetaDescription             sql.NullString
	MetaTitle                   sql.NullString
	MetaImage                   sql.NullString
	SourceAuthor                sql.NullString
	SourceUrl                   sql.NullString
	SourceContent               sql.NullString
	Status                      int64
	Comment                     int64
	ScheduledAt                 sql.NullInt64
	ScheduledCrosspostPlatforms string
	ScheduledSendNewsletter     int64
	CreatedAt                   int64
	UpdatedAt                   int64
}

func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) (Article, error) {
	row := q.db.QueryRowContext(ctx, createArticle,
		arg.Title,
		arg.Slug,
		arg.ContentHtml,
		arg.ContentType,
		arg.Description,
		arg.Excerpt,
		arg.MetaDescription,
		arg.MetaTitle,
		arg.MetaImage,
		arg.SourceAuthor,
		arg.SourceUrl,
		arg.SourceContent,
		arg.Status,
		arg.Comment,
		arg.ScheduledAt,
		arg.ScheduledCrosspostPlatforms,
		arg.ScheduledSendNewsletter,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.ContentHtml,
		&i.ContentType,
		&i.Description,
		&i.Excerpt,
		&i.MetaDescription,
		&i.MetaTitle,
		&i.MetaImage,
		&i.SourceAuthor,
		&i.SourceUrl,
		&i.SourceContent,
		&i.Status,
		&i.Comment,
		&i.ScheduledAt,
		&i.ScheduledCrosspostPlatforms,
		&i.ScheduledSendNewsletter,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteArticle = `-- name: DeleteArticle :exec
DELETE FROM articles WHERE id = ?
`

// Real delete: dependent-destroy rows go first (comments are reachable via
// the polymorphic key and the legacy article_id FK).
func (q *Queries) DeleteArticle(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteArticle, id)
	return err
}

const deleteArticleTagsByArticleID = `-- name: DeleteArticleTagsByArticleID :exec
DELETE FROM article_tags WHERE article_id = ?
`

func (q *Queries) DeleteArticleTagsByArticleID(ctx context.Context, articleID int64) error {
	_, err := q.db.ExecContext(ctx, deleteArticleTagsByArticleID, articleID)
	return err
}

const deleteCommentsForArticle = `-- name: DeleteCommentsForArticle :exec
DELETE FROM comments WHERE (commentable_type = 'Article' AND commentable_id = ?) OR article_id = ?
`

type DeleteCommentsForArticleParams struct {
	CommentableID sql.NullInt64
	ArticleID     sql.NullInt64
}

func (q *Queries) DeleteCommentsForArticle(ctx context.Context, arg DeleteCommentsForArticleParams) error {
	_, err := q.db.ExecContext(ctx, deleteCommentsForArticle, arg.CommentableID, arg.ArticleID)
	return err
}

const deleteJobRun = `-- name: DeleteJobRun :exec
DELETE FROM job_runs WHERE id = ?
`

func (q *Queries) DeleteJobRun(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteJobRun, id)
	return err
}

const deleteSocialMediaPost = `-- name: DeleteSocialMediaPost :exec
DELETE FROM social_media_posts WHERE article_id = ? AND platform = ?
`

type DeleteSocialMediaPostParams struct {
	ArticleID int64
	Platform  string
}

func (q *Queries) DeleteSocialMediaPost(ctx context.Context, arg DeleteSocialMediaPostParams) error {
	_, err := q.db.ExecContext(ctx, deleteSocialMediaPost, arg.ArticleID, arg.Platform)
	return err
}

const deleteSocialMediaPostsByArticleID = `-- name: DeleteSocialMediaPostsByArticleID :exec
DELETE FROM social_media_posts WHERE article_id = ?
`

func (q *Queries) DeleteSocialMediaPostsByArticleID(ctx context.Context, articleID int64) error {
	_, err := q.db.ExecContext(ctx, deleteSocialMediaPostsByArticleID, articleID)
	return err
}

const getAdminArticleByID = `-- name: GetAdminArticleByID :one
SELECT id, title, slug, content_html, content_type, description, excerpt, meta_description, meta_title, meta_image, source_author, source_url, source_content, status, comment, scheduled_at, scheduled_crosspost_platforms, scheduled_send_newsletter, created_at, updated_at FROM articles WHERE id = ?
`

func (q *Queries) GetAdminArticleByID(ctx context.Context, id int64) (Article, error) {
	row := q.db.QueryRowContext(ctx, getAdminArticleByID, id)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.ContentHtml,
		&i.ContentType,
		&i.Description,
		&i.Excerpt,
		&i.MetaDescription,
		&i.MetaTitle,
		&i.MetaImage,
		&i.SourceAuthor,
		&i.SourceUrl,
		&i.SourceContent,
		&i.Status,
		&i.Comment,
		&i.ScheduledAt,
		&i.ScheduledCrosspostPlatforms,
		&i.ScheduledSendNewsletter,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminArticleBySlug = `-- name: GetAdminArticleBySlug :one

SELECT id, title, slug, content_html, content_type, description, excerpt, meta_description, meta_title, meta_image, source_author, source_url, source_content, status, comment, scheduled_at, scheduled_crosspost_platforms, scheduled_send_newsletter, created_at, updated_at FROM articles WHERE slug = ?
`

// Admin article management (plan section 4.1). Feature-local lookups are
// named independently of other query files on purpose.
func (q *Queries) GetAdminArticleBySlug(ctx context.Context, slug sql.NullString) (Article, error) {
	row := q.db.QueryRowContext(ctx, getAdminArticleBySlug, slug)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.ContentHtml,
		&i.ContentType,
		&i.Description,
		&i.Excerpt,
		&i.MetaDescription,
		&i.MetaTitle,
		&i.MetaImage,
		&i.SourceAuthor,
		&i.SourceUrl,
		&i.SourceContent,
		&i.Status,
		&i.Comment,
		&i.ScheduledAt,
		&i.ScheduledCrosspostPlatforms,
		&i.ScheduledSendNewsletter,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCrosspostByPlatform = `-- name: GetCrosspostByPlatform :one
SELECT id, platform, enabled, api_key, api_key_secret, access_token, access_token_secret, client_id, client_key, client_secret, app_password, refresh_token, token_expires_at, server_url, username, max_characters, auto_fetch_comments, comment_fetch_schedule, settings, created_at, updated_at FROM crossposts WHERE platform = ?
`

// Crosspost config lookup (set_form_options / batch_crosspost / handle_crosspost).
func (q *Queries) GetCrosspostByPlatform(ctx context.Context, platform string) (Crosspost, error) {
	row := q.db.QueryRowContext(ctx, getCrosspostByPlatform, platform)
	var i Crosspost
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.Enabled,
		&i.ApiKey,
		&i.ApiKeySecret,
		&i.AccessToken,
		&i.AccessTokenSecret,
		&i.ClientID,
		&i.ClientKey,
		&i.ClientSecret,
		&i.AppPassword,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.ServerUrl,
		&i.Username,
		&i.MaxCharacters,
		&i.AutoFetchComments,
		&i.CommentFetchSchedule,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getListmonk = `-- name: GetListmonk :one
SELECT id, url, username, api_key, list_id, template_id, enabled, created_at, updated_at FROM listmonks ORDER BY id LIMIT 1
`

func (q *Queries) GetListmonk(ctx context.Context) (Listmonk, error) {
	row := q.db.QueryRowContext(ctx, getListmonk)
	var i Listmonk
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Username,
		&i.ApiKey,
		&i.ListID,
		&i.TemplateID,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNewsletterSettings = `-- name: GetNewsletterSettings :one
SELECT id, enabled, provider, from_email, smtp_address, smtp_port, smtp_user_name, smtp_password, smtp_domain, smtp_authentication, smtp_enable_starttls, created_at, updated_at FROM newsletter_settings ORDER BY id LIMIT 1
`

// NewsletterSetting.instance (first_or_initialize: a missing row means disabled).
func (q *Queries) GetNewsletterSettings(ctx context.Context) (NewsletterSetting, error) {
	row := q.db.QueryRowContext(ctx, getNewsletterSettings)
	var i NewsletterSetting
	err := row.Scan(
		&i.ID,
		&i.Enabled,
		&i.Provider,
		&i.FromEmail,
		&i.SmtpAddress,
		&i.SmtpPort,
		&i.SmtpUserName,
		&i.SmtpPassword,
		&i.SmtpDomain,
		&i.SmtpAuthentication,
		&i.SmtpEnableStarttls,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertArticleTag = `-- name: InsertArticleTag :exec
INSERT OR IGNORE INTO article_tags (article_id, tag_id, created_at, updated_at) VALUES (?, ?, ?, ?)
`

type InsertArticleTagParams struct {
	ArticleID int64
	TagID     int64
	CreatedAt int64
	UpdatedAt int64
}

// tag_list assignment: reset join rows, then re-insert (find_or_create_by
// semantics via the UNIQUE(article_id, tag_id) conflict target).
func (q *Queries) InsertArticleTag(ctx context.Context, arg InsertArticleTagParams) error {
	_, err := q.db.ExecContext(ctx, insertArticleTag,
		arg.ArticleID,
		arg.TagID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listAdminArticles = `-- name: ListAdminArticles :many
SELECT id, title, slug, content_html, content_type, description, excerpt, meta_description, meta_title, meta_image, source_author, source_url, source_content, status, comment, scheduled_at, scheduled_crosspost_platforms, scheduled_send_newsletter, created_at, updated_at FROM articles ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListAdminArticlesParams struct {
	Limit  int64
	Offset int64
}

// Admin list: fetch_articles orders created_at DESC, 100 per page.
func (q *Queries) ListAdminArticles(ctx context.Context, arg ListAdminArticlesParams) ([]Article, error) {
	rows, err := q.db.QueryContext(ctx, listAdminArticles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Article
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.ContentHtml,
			&i.ContentType,
			&i.Description,
			&i.Excerpt,
			&i.MetaDescription,
			&i.MetaTitle,
			&i.MetaImage,
			&i.SourceAuthor,
			&i.SourceUrl,
			&i.SourceContent,
			&i.Status,
			&i.Comment,
			&i.ScheduledAt,
			&i.ScheduledCrosspostPlatforms,
			&i.ScheduledSendNewsletter,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminArticlesByStatus = `-- name: ListAdminArticlesByStatus :many
SELECT id, title, slug, content_html, content_type, description, excerpt, meta_description, meta_title, meta_image, source_author, source_url, source_content, status, comment, scheduled_at, scheduled_crosspost_platforms, scheduled_send_newsletter, created_at, updated_at FROM articles WHERE status = ? ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListAdminArticlesByStatusParams struct {
	Status int64
	Limit  int64
	Offset int64
}

func (q *Queries) ListAdminArticlesByStatus(ctx context.Context, arg ListAdminArticlesByStatusParams) ([]Article, error) {
	rows, err := q.db.QueryContext(ctx, listAdminArticlesByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Article
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.ContentHtml,
			&i.ContentType,
			&i.Description,
			&i.Excerpt,
			&i.MetaDescription,
			&i.MetaTitle,
			&i.MetaImage,
			&i.SourceAuthor,
			&i.SourceUrl,
			&i.SourceContent,
			&i.Status,
			&i.Comment,
			&i.ScheduledAt,
			&i.ScheduledCrosspostPlatforms,
			&i.ScheduledSendNewsletter,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArticleTagNames = `-- name: ListArticleTagNames :many
SELECT article_tags.article_id, tags.name
FROM article_tags
JOIN tags ON tags.id = article_tags.tag_id
WHERE article_tags.article_id IN (/*SLICE:ids*/?)
ORDER BY tags.name
`

type ListArticleTagNamesRow struct {
	ArticleID int64
	Name      string
}

func (q *Queries) ListArticleTagNames(ctx context.Context, ids []int64) ([]ListArticleTagNamesRow, error) {
	query := listArticleTagNames
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListArticleTagNamesRow
	for rows.Next() {
		var i ListArticleTagNamesRow
		if err := rows.Scan(&i.ArticleID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFetchableSocialPosts = `-- name: ListFetchableSocialPosts :many
SELECT id, article_id, platform, url, created_at, updated_at FROM social_media_posts WHERE article_id = ? AND url != '' ORDER BY platform
`

// fetch_comments sources: posts with a url, optionally platform-filtered.
func (q *Queries) ListFetchableSocialPosts(ctx context.Context, articleID int64) ([]SocialMediaPost, error) {
	rows, err := q.db.QueryContext(ctx, listFetchableSocialPosts, articleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SocialMediaPost
	for rows.Next() {
		var i SocialMediaPost
		if err := rows.Scan(
			&i.ID,
			&i.ArticleID,
			&i.Platform,
			&i.Url,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFetchableSocialPostsByPlatform = `-- name: ListFetchableSocialPostsByPlatform :many
SELECT id, article_id, platform, url, created_at, updated_at FROM social_media_posts WHERE article_id = ? AND url != '' AND platform = ?
`

type ListFetchableSocialPostsByPlatformParams struct {
	ArticleID int64
	Platform  string
}

func (q *Queries) ListFetchableSocialPostsByPlatform(ctx context.Context, arg ListFetchableSocialPostsByPlatformParams) ([]SocialMediaPost, error) {
	rows, err := q.db.QueryContext(ctx, listFetchableSocialPostsByPlatform, arg.ArticleID, arg.Platform)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SocialMediaPost
	for rows.Next() {
		var i SocialMediaPost
		if err := rows.Scan(
			&i.ID,
			&i.ArticleID,
			&i.Platform,
			&i.Url,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQueuedJobRunsByKind = `-- name: ListQueuedJobRunsByKind :many
SELECT id, kind, payload, run_at, status, attempts, last_error, created_at, updated_at FROM job_runs WHERE kind = ? AND status = 'queued'
`

// Queued publish_article jobs, cancelled before a reschedule
// (PublishScheduledArticlesJob.cancel_old_jobs).
func (q *Queries) ListQueuedJobRunsByKind(ctx context.Context, kind string) ([]JobRun, error) {
	rows, err := q.db.QueryContext(ctx, listQueuedJobRunsByKind, kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobRun
	for rows.Next() {
		var i JobRun
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Payload,
			&i.RunAt,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSocialPostsByArticleID = `-- name: ListSocialPostsByArticleID :many
SELECT id, article_id, platform, url, created_at, updated_at FROM social_media_posts WHERE article_id = ? ORDER BY platform
`

func (q *Queries) ListSocialPostsByArticleID(ctx context.Context, articleID int64) ([]SocialMediaPost, error) {
	rows, err := q.db.QueryContext(ctx, listSocialPostsByArticleID, articleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SocialMediaPost
	for rows.Next() {
		var i SocialMediaPost
		if err := rows.Scan(
			&i.ID,
			&i.ArticleID,
			&i.Platform,
			&i.Url,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSocialPostsForArticles = `-- name: ListSocialPostsForArticles :many
SELECT id, article_id, platform, url, created_at, updated_at FROM social_media_posts WHERE article_id IN (/*SLICE:ids*/?) ORDER BY platform
`

func (q *Queries) ListSocialPostsForArticles(ctx context.Context, ids []int64) ([]SocialMediaPost, error) {
	query := listSocialPostsForArticles
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SocialMediaPost
	for rows.Next() {
		var i SocialMediaPost
		if err := rows.Scan(
			&i.ID,
			&i.ArticleID,
			&i.Platform,
			&i.Url,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchAdminArticles = `-- name: SearchAdminArticles :many
SELECT id, title, slug, content_html, content_type, description, excerpt, meta_description, meta_title, meta_image, source_author, source_url, source_content, status, comment, scheduled_at, scheduled_crosspost_platforms, scheduled_send_newsletter, created_at, updated_at FROM articles
WHERE like(?, title, '\') OR like(?, slug, '\')
   OR like(?, description, '\') OR like(?, content_html, '\')
ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type SearchAdminArticlesParams struct {
	LIKE   string
	LIKE_2 string
	LIKE_3 string
	LIKE_4 string
	Limit  int64
	Offset int64
}

// Article.search_content: LIKE on title/slug/description/content_html with
// ESCAPE '\'. The sqlc sqlite grammar rejects the ESCAPE keyword, so the
// queries use the equivalent like(pattern, string, escape) function form.
// The caller pre-escapes %, _ and backslash, then wraps the term in %...%
// (sanitize_sql_like semantics).
func (q *Queries) SearchAdminArticles(ctx context.Context, arg SearchAdminArticlesParams) ([]Article, error) {
	rows, err := q.db.QueryContext(ctx, searchAdminArticles,
		arg.LIKE,
		arg.LIKE_2,
		arg.LIKE_3,
		arg.LIKE_4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Article
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.ContentHtml,
			&i.ContentType,
			&i.Description,
			&i.Excerpt,
			&i.MetaDescription,
			&i.MetaTitle,
			&i.MetaImage,
			&i.SourceAuthor,
			&i.SourceUrl,
			&i.SourceContent,
			&i.Status,
			&i.Comment,
			&i.ScheduledAt,
			&i.ScheduledCrosspostPlatforms,
			&i.ScheduledSendNewsletter,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchAdminArticlesByStatus = `-- name: SearchAdminArticlesByStatus :many
SELECT id, title, slug, content_html, content_type, description, excerpt, meta_description, meta_title, meta_image, source_author, source_url, source_content, status, comment, scheduled_at, scheduled_crosspost_platforms, scheduled_send_newsletter, created_at, updated_at FROM articles
WHERE status = ? AND (like(?, title, '\') OR like(?, slug, '\')
   OR like(?, description, '\') OR like(?, content_html, '\'))
ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type SearchAdminArticlesByStatusParams struct {
	Status int64
	LIKE   string
	LIKE_2 string
	LIKE_3 string
	LIKE_4 string
	Limit  int64
	Offset int64
}

func (q *Queries) SearchAdminArticlesByStatus(ctx context.Context, arg SearchAdminArticlesByStatusParams) ([]Article, error) {
	rows, err := q.db.QueryContext(ctx, searchAdminArticlesByStatus,
		arg.Status,
		arg.LIKE,
		arg.LIKE_2,
		arg.LIKE_3,
		arg.LIKE_4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Article
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.ContentHtml,
			&i.ContentType,
			&i.Description,
			&i.Excerpt,
			&i.MetaDescription,
			&i.MetaTitle,
			&i.MetaImage,
			&i.SourceAuthor,
			&i.SourceUrl,
			&i.SourceContent,
			&i.Status,
			&i.Comment,
			&i.ScheduledAt,
			&i.ScheduledCrosspostPlatforms,
			&i.ScheduledSendNewsletter,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArticle = `-- name: UpdateArticle :one
UPDATE articles
SET title = ?, slug = ?, content_html = ?, content_type = ?, description = ?, excerpt = ?,
    meta_description = ?, meta_title = ?, meta_image = ?,
    source_author = ?, source_url = ?, source_content = ?,
    status = ?, comment = ?, scheduled_at = ?,
    scheduled_crosspost_platforms = ?, scheduled_send_newsletter = ?,
    created_at = ?, updated_at = ?
WHERE id = ?
RETURNING id, title, slug, content_html, content_type, description, excerpt, meta_description, meta_title, meta_image, source_author, source_url, source_content, status, comment, scheduled_at, scheduled_crosspost_platforms, scheduled_send_newsletter, created_at, updated_at
`

type UpdateArticleParams struct {
	Title                       sql.NullString
	Slug                        sql.NullString
	ContentHtml                 sql.NullString
	ContentType                 string
	Description                 sql.NullString
	Excerpt                     sql.NullString
	MetaDescription             sql.NullString
	MetaTitle                   sql.NullString
	MetaImage                   sql.NullString
	SourceAuthor                sql.NullString
	SourceUrl                   sql.NullString
	SourceContent               sql.NullString
	Status                      int64
	Comment                     int64
	ScheduledAt                 sql.NullInt64
	ScheduledCrosspostPlatforms string
	ScheduledSendNewsletter     int64
	CreatedAt                   int64
	UpdatedAt                   int64
	ID                          int64
}

func (q *Queries) UpdateArticle(ctx context.Context, arg UpdateArticleParams) (Article, error) {
	row := q.db.QueryRowContext(ctx, updateArticle,
		arg.Title,
		arg.Slug,
		arg.ContentHtml,
		arg.ContentType,
		arg.Description,
		arg.Excerpt,
		arg.MetaDescription,
		arg.MetaTitle,
		arg.MetaImage,
		arg.SourceAuthor,
		arg.SourceUrl,
		arg.SourceContent,
		arg.Status,
		arg.Comment,
		arg.ScheduledAt,
		arg.ScheduledCrosspostPlatforms,
		arg.ScheduledSendNewsletter,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.ContentHtml,
		&i.ContentType,
		&i.Description,
		&i.Excerpt,
		&i.MetaDescription,
		&i.MetaTitle,
		&i.MetaImage,
		&i.SourceAuthor,
		&i.SourceUrl,
		&i.SourceContent,
		&i.Status,
		&i.Comment,
		&i.ScheduledAt,
		&i.ScheduledCrosspostPlatforms,
		&i.ScheduledSendNewsletter,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateArticleStatus = `-- name: UpdateArticleStatus :one
UPDATE articles
SET status = ?, scheduled_crosspost_platforms = ?, scheduled_send_newsletter = ?, updated_at = ?
WHERE id = ?
RETURNING id, title, slug, content_html, content_type, description, excerpt, meta_description, meta_title, meta_image, source_author, source_url, source_content, status, comment, scheduled_at, scheduled_crosspost_platforms, scheduled_send_newsletter, created_at, updated_at
`

type UpdateArticleStatusParams struct {
	Status                      int64
	ScheduledCrosspostPlatforms string
	ScheduledSendNewsletter     int64
	UpdatedAt                   int64
	ID                          int64
}

// Status-only transitions (publish/unpublish/trash). The Article sync
// callbacks clear the schedule snapshots unless the target is schedule, so
// the caller passes the already-synced snapshot values.
func (q *Queries) UpdateArticleStatus(ctx context.Context, arg UpdateArticleStatusParams) (Article, error) {
	row := q.db.QueryRowContext(ctx, updateArticleStatus,
		arg.Status,
		arg.ScheduledCrosspostPlatforms,
		arg.ScheduledSendNewsletter,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.ContentHtml,
		&i.ContentType,
		&i.Description,
		&i.Excerpt,
		&i.MetaDescription,
		&i.MetaTitle,
		&i.MetaImage,
		&i.SourceAuthor,
		&i.SourceUrl,
		&i.SourceContent,
		&i.Status,
		&i.Comment,
		&i.ScheduledAt,
		&i.ScheduledCrosspostPlatforms,
		&i.ScheduledSendNewsletter,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSocialMediaPost = `-- name: UpsertSocialMediaPost :exec
INSERT INTO social_media_posts (article_id, platform, url, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(article_id, platform) DO UPDATE SET url = excluded.url, updated_at = excluded.updated_at
`

type UpsertSocialMediaPostParams struct {
	ArticleID int64
	Platform  string
	Url       string
	CreatedAt int64
	UpdatedAt int64
}

// Nested-attributes sync: blank url destroys the row, otherwise upsert.
func (q *Queries) UpsertSocialMediaPost(ctx context.Context, arg UpsertSocialMediaPostParams) error {
	_, err := q.db.ExecContext(ctx, upsertSocialMediaPost,
		arg.ArticleID,
		arg.Platform,
		arg.Url,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
