// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package query

import (
	"context"
	"database/sql"
)

const completeSetup = `-- name: CompleteSetup :exec
UPDATE settings
SET title = ?, description = ?, author = ?, url = ?, time_zone = ?,
    setup_completed = 1, updated_at = ?
WHERE id = 1
`

type CompleteSetupParams struct {
	Title       sql.NullString
	Description sql.NullString
	Author      sql.NullString
	Url         sql.NullString
	TimeZone    string
	UpdatedAt   int64
}

func (q *Queries) CompleteSetup(ctx context.Context, arg CompleteSetupParams) error {
	_, err := q.db.ExecContext(ctx, completeSetup,
		arg.Title,
		arg.Description,
		arg.Author,
		arg.Url,
		arg.TimeZone,
		arg.UpdatedAt,
	)
	return err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (token, user_id, ip_address, user_agent, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, token, user_id, ip_address, user_agent, created_at, updated_at
`

type CreateSessionParams struct {
	Token     string
	UserID    int64
	IpAddress sql.NullString
	UserAgent sql.NullString
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.Token,
		arg.UserID,
		arg.IpAddress,
		arg.UserAgent,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.UserID,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (user_name, password_digest, created_at, updated_at)
VALUES (?, ?, ?, ?)
RETURNING id, user_name, password_digest, created_at, updated_at
`

type CreateUserParams struct {
	UserName       string
	PasswordDigest string
	CreatedAt      int64
	UpdatedAt      int64
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.UserName,
		arg.PasswordDigest,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.PasswordDigest,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSessionByToken = `-- name: DeleteSessionByToken :exec
DELETE FROM sessions WHERE token = ?
`

func (q *Queries) DeleteSessionByToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionByToken, token)
	return err
}

const ensureSettings = `-- name: EnsureSettings :exec
INSERT INTO settings (id, created_at, updated_at)
VALUES (1, ?, ?)
ON CONFLICT (id) DO NOTHING
`

type EnsureSettingsParams struct {
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) EnsureSettings(ctx context.Context, arg EnsureSettingsParams) error {
	_, err := q.db.ExecContext(ctx, ensureSettings, arg.CreatedAt, arg.UpdatedAt)
	return err
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT id, token, user_id, ip_address, user_agent, created_at, updated_at FROM sessions WHERE token = ?
`

func (q *Queries) GetSessionByToken(ctx context.Context, token string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByToken, token)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.UserID,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSettings = `-- name: GetSettings :one
SELECT id, title, description, author, url, time_zone, head_code, custom_css, tool_code, giscus, social_links, setup_completed, created_at, updated_at FROM settings WHERE id = 1
`

func (q *Queries) GetSettings(ctx context.Context) (Setting, error) {
	row := q.db.QueryRowContext(ctx, getSettings)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Author,
		&i.Url,
		&i.TimeZone,
		&i.HeadCode,
		&i.CustomCss,
		&i.ToolCode,
		&i.Giscus,
		&i.SocialLinks,
		&i.SetupCompleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, user_name, password_digest, created_at, updated_at FROM users WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.PasswordDigest,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUserName = `-- name: GetUserByUserName :one
SELECT id, user_name, password_digest, created_at, updated_at FROM users WHERE user_name = ?
`

func (q *Queries) GetUserByUserName(ctx context.Context, userName string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUserName, userName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.PasswordDigest,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users SET user_name = ?, password_digest = ?, updated_at = ?
WHERE id = ?
`

type UpdateUserParams struct {
	UserName       string
	PasswordDigest string
	UpdatedAt      int64
	ID             int64
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.UserName,
		arg.PasswordDigest,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
