// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comments.sql

package query

import (
	"context"
	"database/sql"
)

const countAdminComments = `-- name: CountAdminComments :one
SELECT COUNT(*) FROM comments
`

func (q *Queries) CountAdminComments(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdminComments)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAdminCommentsByStatus = `-- name: CountAdminCommentsByStatus :one
SELECT COUNT(*) FROM comments WHERE status = ?
`

func (q *Queries) CountAdminCommentsByStatus(ctx context.Context, status int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdminCommentsByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createComment = `-- name: CreateComment :one
INSERT INTO comments (
  commentable_type, commentable_id, article_id, parent_id,
  author_name, author_email, author_url, author_username, author_avatar_url,
  content, status, platform, external_id, url, published_at,
  created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, commentable_type, commentable_id, article_id, parent_id, author_name, author_email, author_url, author_username, author_avatar_url, content, status, platform, external_id, url, published_at, created_at, updated_at
`

type CreateCommentParams struct {
	CommentableType sql.NullString
	CommentableID   sql.NullInt64
	ArticleID       sql.NullInt64
	ParentID        sql.NullInt64
	AuthorName      string
	AuthorEmail     sql.NullString
	AuthorUrl       sql.NullString
	AuthorUsername  sql.NullString
	AuthorAvatarUrl sql.NullString
	Content         string
	Status          int64
	Platform        sql.NullString
	ExternalID      sql.NullString
	Url             sql.NullString
	PublishedAt     sql.NullInt64
	CreatedAt       int64
	UpdatedAt       int64
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRowContext(ctx, createComment,
		arg.CommentableType,
		arg.CommentableID,
		arg.ArticleID,
		arg.ParentID,
		arg.AuthorName,
		arg.AuthorEmail,
		arg.AuthorUrl,
		arg.AuthorUsername,
		arg.AuthorAvatarUrl,
		arg.Content,
		arg.Status,
		arg.Platform,
		arg.ExternalID,
		arg.Url,
		arg.PublishedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.CommentableType,
		&i.CommentableID,
		&i.ArticleID,
		&i.ParentID,
		&i.AuthorName,
		&i.AuthorEmail,
		&i.AuthorUrl,
		&i.AuthorUsername,
		&i.AuthorAvatarUrl,
		&i.Content,
		&i.Status,
		&i.Platform,
		&i.ExternalID,
		&i.Url,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM comments WHERE id = ?
`

func (q *Queries) DeleteComment(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteComment, id)
	return err
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT id, commentable_type, commentable_id, article_id, parent_id, author_name, author_email, author_url, author_username, author_avatar_url, content, status, platform, external_id, url, published_at, created_at, updated_at FROM comments WHERE id = ?
`

func (q *Queries) GetCommentByID(ctx context.Context, id int64) (Comment, error) {
	row := q.db.QueryRowContext(ctx, getCommentByID, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.CommentableType,
		&i.CommentableID,
		&i.ArticleID,
		&i.ParentID,
		&i.AuthorName,
		&i.AuthorEmail,
		&i.AuthorUrl,
		&i.AuthorUsername,
		&i.AuthorAvatarUrl,
		&i.Content,
		&i.Status,
		&i.Platform,
		&i.ExternalID,
		&i.Url,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCommentableArticleByID = `-- name: GetCommentableArticleByID :one
SELECT id, title, slug, content_html, content_type, description, excerpt, meta_description, meta_title, meta_image, source_author, source_url, source_content, status, comment, scheduled_at, scheduled_crosspost_platforms, scheduled_send_newsletter, created_at, updated_at, content_markdown FROM articles WHERE id = ?
`

func (q *Queries) GetCommentableArticleByID(ctx context.Context, id int64) (Article, error) {
	row := q.db.QueryRowContext(ctx, getCommentableArticleByID, id)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.ContentHtml,
		&i.ContentType,
		&i.Description,
		&i.Excerpt,
		&i.MetaDescription,
		&i.MetaTitle,
		&i.MetaImage,
		&i.SourceAuthor,
		&i.SourceUrl,
		&i.SourceContent,
		&i.Status,
		&i.Comment,
		&i.ScheduledAt,
		&i.ScheduledCrosspostPlatforms,
		&i.ScheduledSendNewsletter,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContentMarkdown,
	)
	return i, err
}

const getCommentableArticleBySlug = `-- name: GetCommentableArticleBySlug :one

SELECT id, title, slug, content_html, content_type, description, excerpt, meta_description, meta_title, meta_image, source_author, source_url, source_content, status, comment, scheduled_at, scheduled_crosspost_platforms, scheduled_send_newsletter, created_at, updated_at, content_markdown FROM articles WHERE slug = ?
`

// Comment chain (plan section 4.5). Commentable lookups are duplicated here under
// feature-specific names so this file stays independent of other features'
// query files.
func (q *Queries) GetCommentableArticleBySlug(ctx context.Context, slug sql.NullString) (Article, error) {
	row := q.db.QueryRowContext(ctx, getCommentableArticleBySlug, slug)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.ContentHtml,
		&i.ContentType,
		&i.Description,
		&i.Excerpt,
		&i.MetaDescription,
		&i.MetaTitle,
		&i.MetaImage,
		&i.SourceAuthor,
		&i.SourceUrl,
		&i.SourceContent,
		&i.Status,
		&i.Comment,
		&i.ScheduledAt,
		&i.ScheduledCrosspostPlatforms,
		&i.ScheduledSendNewsletter,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContentMarkdown,
	)
	return i, err
}

const getCommentablePageByID = `-- name: GetCommentablePageByID :one
SELECT id, title, slug, content_html, content_type, redirect_url, page_order, status, comment, scheduled_at, created_at, updated_at, content_markdown FROM pages WHERE id = ?
`

func (q *Queries) GetCommentablePageByID(ctx context.Context, id int64) (Page, error) {
	row := q.db.QueryRowContext(ctx, getCommentablePageByID, id)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.ContentHtml,
		&i.ContentType,
		&i.RedirectUrl,
		&i.PageOrder,
		&i.Status,
		&i.Comment,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContentMarkdown,
	)
	return i, err
}

const getCommentablePageBySlug = `-- name: GetCommentablePageBySlug :one
SELECT id, title, slug, content_html, content_type, redirect_url, page_order, status, comment, scheduled_at, created_at, updated_at, content_markdown FROM pages WHERE slug = ?
`

func (q *Queries) GetCommentablePageBySlug(ctx context.Context, slug sql.NullString) (Page, error) {
	row := q.db.QueryRowContext(ctx, getCommentablePageBySlug, slug)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.ContentHtml,
		&i.ContentType,
		&i.RedirectUrl,
		&i.PageOrder,
		&i.Status,
		&i.Comment,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContentMarkdown,
	)
	return i, err
}

const getExternalComment = `-- name: GetExternalComment :one
SELECT id, commentable_type, commentable_id, article_id, parent_id, author_name, author_email, author_url, author_username, author_avatar_url, content, status, platform, external_id, url, published_at, created_at, updated_at FROM comments
WHERE commentable_type = ? AND commentable_id = ? AND platform = ? AND external_id = ?
`

type GetExternalCommentParams struct {
	CommentableType sql.NullString
	CommentableID   sql.NullInt64
	Platform        sql.NullString
	ExternalID      sql.NullString
}

func (q *Queries) GetExternalComment(ctx context.Context, arg GetExternalCommentParams) (Comment, error) {
	row := q.db.QueryRowContext(ctx, getExternalComment,
		arg.CommentableType,
		arg.CommentableID,
		arg.Platform,
		arg.ExternalID,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.CommentableType,
		&i.CommentableID,
		&i.ArticleID,
		&i.ParentID,
		&i.AuthorName,
		&i.AuthorEmail,
		&i.AuthorUrl,
		&i.AuthorUsername,
		&i.AuthorAvatarUrl,
		&i.Content,
		&i.Status,
		&i.Platform,
		&i.ExternalID,
		&i.Url,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAdminComments = `-- name: ListAdminComments :many
SELECT id, commentable_type, commentable_id, article_id, parent_id, author_name, author_email, author_url, author_username, author_avatar_url, content, status, platform, external_id, url, published_at, created_at, updated_at FROM comments
ORDER BY COALESCE(published_at, created_at) DESC
LIMIT ? OFFSET ?
`

type ListAdminCommentsParams struct {
	Limit  int64
	Offset int64
}

// Admin moderation list (plan section 4.5):
// COALESCE(published_at, created_at) DESC, 30 per page.
func (q *Queries) ListAdminComments(ctx context.Context, arg ListAdminCommentsParams) ([]Comment, error) {
	rows, err := q.db.QueryContext(ctx, listAdminComments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.CommentableType,
			&i.CommentableID,
			&i.ArticleID,
			&i.ParentID,
			&i.AuthorName,
			&i.AuthorEmail,
			&i.AuthorUrl,
			&i.AuthorUsername,
			&i.AuthorAvatarUrl,
			&i.Content,
			&i.Status,
			&i.Platform,
			&i.ExternalID,
			&i.Url,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminCommentsByStatus = `-- name: ListAdminCommentsByStatus :many
SELECT id, commentable_type, commentable_id, article_id, parent_id, author_name, author_email, author_url, author_username, author_avatar_url, content, status, platform, external_id, url, published_at, created_at, updated_at FROM comments
WHERE status = ?
ORDER BY COALESCE(published_at, created_at) DESC
LIMIT ? OFFSET ?
`

type ListAdminCommentsByStatusParams struct {
	Status int64
	Limit  int64
	Offset int64
}

func (q *Queries) ListAdminCommentsByStatus(ctx context.Context, arg ListAdminCommentsByStatusParams) ([]Comment, error) {
	rows, err := q.db.QueryContext(ctx, listAdminCommentsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.CommentableType,
			&i.CommentableID,
			&i.ArticleID,
			&i.ParentID,
			&i.AuthorName,
			&i.AuthorEmail,
			&i.AuthorUrl,
			&i.AuthorUsername,
			&i.AuthorAvatarUrl,
			&i.Content,
			&i.Status,
			&i.Platform,
			&i.ExternalID,
			&i.Url,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommentsForCommentable = `-- name: ListCommentsForCommentable :many
SELECT id, commentable_type, commentable_id, article_id, parent_id, author_name, author_email, author_url, author_username, author_avatar_url, content, status, platform, external_id, url, published_at, created_at, updated_at FROM comments
WHERE commentable_type = ? AND commentable_id = ?
ORDER BY published_at ASC
`

type ListCommentsForCommentableParams struct {
	CommentableType sql.NullString
	CommentableID   sql.NullInt64
}

// Mirrors Comment.default_scope (published_at ASC; SQLite sorts NULLs first).
func (q *Queries) ListCommentsForCommentable(ctx context.Context, arg ListCommentsForCommentableParams) ([]Comment, error) {
	rows, err := q.db.QueryContext(ctx, listCommentsForCommentable, arg.CommentableType, arg.CommentableID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.CommentableType,
			&i.CommentableID,
			&i.ArticleID,
			&i.ParentID,
			&i.AuthorName,
			&i.AuthorEmail,
			&i.AuthorUrl,
			&i.AuthorUsername,
			&i.AuthorAvatarUrl,
			&i.Content,
			&i.Status,
			&i.Platform,
			&i.ExternalID,
			&i.Url,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCommentStatus = `-- name: UpdateCommentStatus :one
UPDATE comments SET status = ?, updated_at = ?
WHERE id = ?
RETURNING id, commentable_type, commentable_id, article_id, parent_id, author_name, author_email, author_url, author_username, author_avatar_url, content, status, platform, external_id, url, published_at, created_at, updated_at
`

type UpdateCommentStatusParams struct {
	Status    int64
	UpdatedAt int64
	ID        int64
}

func (q *Queries) UpdateCommentStatus(ctx context.Context, arg UpdateCommentStatusParams) (Comment, error) {
	row := q.db.QueryRowContext(ctx, updateCommentStatus, arg.Status, arg.UpdatedAt, arg.ID)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.CommentableType,
		&i.CommentableID,
		&i.ArticleID,
		&i.ParentID,
		&i.AuthorName,
		&i.AuthorEmail,
		&i.AuthorUrl,
		&i.AuthorUsername,
		&i.AuthorAvatarUrl,
		&i.Content,
		&i.Status,
		&i.Platform,
		&i.ExternalID,
		&i.Url,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateExternalComment = `-- name: UpdateExternalComment :one
UPDATE comments
SET author_name = ?, author_username = ?, author_avatar_url = ?,
    content = ?, published_at = ?, url = ?, updated_at = ?
WHERE id = ?
RETURNING id, commentable_type, commentable_id, article_id, parent_id, author_name, author_email, author_url, author_username, author_avatar_url, content, status, platform, external_id, url, published_at, created_at, updated_at
`

type UpdateExternalCommentParams struct {
	AuthorName      string
	AuthorUsername  sql.NullString
	AuthorAvatarUrl sql.NullString
	Content         string
	PublishedAt     sql.NullInt64
	Url             sql.NullString
	UpdatedAt       int64
	ID              int64
}

// Re-fetched platform data never touches status (moderation decision).
func (q *Queries) UpdateExternalComment(ctx context.Context, arg UpdateExternalCommentParams) (Comment, error) {
	row := q.db.QueryRowContext(ctx, updateExternalComment,
		arg.AuthorName,
		arg.AuthorUsername,
		arg.AuthorAvatarUrl,
		arg.Content,
		arg.PublishedAt,
		arg.Url,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.CommentableType,
		&i.CommentableID,
		&i.ArticleID,
		&i.ParentID,
		&i.AuthorName,
		&i.AuthorEmail,
		&i.AuthorUrl,
		&i.AuthorUsername,
		&i.AuthorAvatarUrl,
		&i.Content,
		&i.Status,
		&i.Platform,
		&i.ExternalID,
		&i.Url,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
