// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: crossposts.sql

package query

import (
	"context"
	"database/sql"
)

const ensureCrosspost = `-- name: EnsureCrosspost :exec

INSERT OR IGNORE INTO crossposts (platform, created_at, updated_at) VALUES (?, ?, ?)
`

type EnsureCrosspostParams struct {
	Platform  string
	CreatedAt int64
	UpdatedAt int64
}

// Crosspost platform config + per-article image collection (T20).
// Reads reuse GetCrosspostByPlatform / UpsertSocialMediaPost /
// ListFetchableSocialPostsByPlatform from articles_admin.sql.
// Crosspost.find_or_create_by(platform:) on the admin update path.
func (q *Queries) EnsureCrosspost(ctx context.Context, arg EnsureCrosspostParams) error {
	_, err := q.db.ExecContext(ctx, ensureCrosspost, arg.Platform, arg.CreatedAt, arg.UpdatedAt)
	return err
}

const listImageAttachmentsForArticle = `-- name: ListImageAttachmentsForArticle :many
SELECT files.id, files.key, files.filename, files.content_type, files.byte_size, files.checksum, files.variant_of, files.created_at
FROM attachments
JOIN files ON files.id = attachments.file_id
WHERE attachments.record_type = 'Article' AND attachments.record_id = ?
  AND files.content_type LIKE 'image/%'
ORDER BY attachments.id
`

// Article#all_image_attachments path 1: image files attached to the article
// (ActionText attachables in Rails), in attachment order.
func (q *Queries) ListImageAttachmentsForArticle(ctx context.Context, recordID int64) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, listImageAttachmentsForArticle, recordID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Filename,
			&i.ContentType,
			&i.ByteSize,
			&i.Checksum,
			&i.VariantOf,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCrosspost = `-- name: UpdateCrosspost :exec
UPDATE crossposts SET
  enabled = ?, server_url = ?, username = ?,
  access_token = ?, access_token_secret = ?,
  client_key = ?, client_secret = ?,
  api_key = ?, api_key_secret = ?, app_password = ?,
  max_characters = ?, auto_fetch_comments = ?, comment_fetch_schedule = ?,
  updated_at = ?
WHERE platform = ?
`

type UpdateCrosspostParams struct {
	Enabled              int64
	ServerUrl            sql.NullString
	Username             sql.NullString
	AccessToken          sql.NullString
	AccessTokenSecret    sql.NullString
	ClientKey            sql.NullString
	ClientSecret         sql.NullString
	ApiKey               sql.NullString
	ApiKeySecret         sql.NullString
	AppPassword          sql.NullString
	MaxCharacters        sql.NullInt64
	AutoFetchComments    int64
	CommentFetchSchedule sql.NullString
	UpdatedAt            int64
	Platform             string
}

// Admin update: full overlay of the permitted crosspost_params columns.
func (q *Queries) UpdateCrosspost(ctx context.Context, arg UpdateCrosspostParams) error {
	_, err := q.db.ExecContext(ctx, updateCrosspost,
		arg.Enabled,
		arg.ServerUrl,
		arg.Username,
		arg.AccessToken,
		arg.AccessTokenSecret,
		arg.ClientKey,
		arg.ClientSecret,
		arg.ApiKey,
		arg.ApiKeySecret,
		arg.AppPassword,
		arg.MaxCharacters,
		arg.AutoFetchComments,
		arg.CommentFetchSchedule,
		arg.UpdatedAt,
		arg.Platform,
	)
	return err
}
