// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fetch_comments.sql

package query

import (
	"context"
	"database/sql"
)

const listCommentFetchTargets = `-- name: ListCommentFetchTargets :many

SELECT a.id, p.url
FROM articles a
JOIN social_media_posts p ON p.article_id = a.id
WHERE a.status = 1 AND p.platform = ? AND p.url != ''
ORDER BY a.id
`

type ListCommentFetchTargetsRow struct {
	ID  int64
	Url string
}

// Social comment fetching (T22, plan section 4.8): the cron scan target list
// and the parent backfill of the two-pass external upsert.
// Reads reuse GetCrosspostByPlatform (articles_admin.sql) and GetExternalComment
// / CreateComment / UpdateExternalComment (comments.sql).
// FetchSocialCommentsJob scan: published articles (status = 1,
// Article.published) that have a social_media_posts URL for the platform.
// UNIQUE(article_id, platform) makes the Rails .distinct unnecessary; the id
// order only keeps the scan deterministic.
func (q *Queries) ListCommentFetchTargets(ctx context.Context, platform string) ([]ListCommentFetchTargetsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCommentFetchTargets, platform)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentFetchTargetsRow
	for rows.Next() {
		var i ListCommentFetchTargetsRow
		if err := rows.Scan(&i.ID, &i.Url); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCommentParent = `-- name: SetCommentParent :exec
UPDATE comments SET parent_id = ?, updated_at = ? WHERE id = ?
`

type SetCommentParentParams struct {
	ParentID  sql.NullInt64
	UpdatedAt int64
	ID        int64
}

// Second pass of the two-pass external upsert
// (Admin::ArticlesController#fetch_comments): attach a reply to its parent.
func (q *Queries) SetCommentParent(ctx context.Context, arg SetCommentParentParams) error {
	_, err := q.db.ExecContext(ctx, setCommentParent, arg.ParentID, arg.UpdatedAt, arg.ID)
	return err
}
