// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: files.sql

package query

import (
	"context"
	"database/sql"
)

const createAttachment = `-- name: CreateAttachment :exec
INSERT OR IGNORE INTO attachments (file_id, record_type, record_id, name, created_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateAttachmentParams struct {
	FileID     int64
	RecordType string
	RecordID   int64
	Name       string
	CreatedAt  int64
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) error {
	_, err := q.db.ExecContext(ctx, createAttachment,
		arg.FileID,
		arg.RecordType,
		arg.RecordID,
		arg.Name,
		arg.CreatedAt,
	)
	return err
}

const createFile = `-- name: CreateFile :one
INSERT INTO files (key, filename, content_type, byte_size, checksum, variant_of, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, "key", filename, content_type, byte_size, checksum, variant_of, created_at
`

type CreateFileParams struct {
	Key         string
	Filename    string
	ContentType sql.NullString
	ByteSize    int64
	Checksum    sql.NullString
	VariantOf   sql.NullInt64
	CreatedAt   int64
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, createFile,
		arg.Key,
		arg.Filename,
		arg.ContentType,
		arg.ByteSize,
		arg.Checksum,
		arg.VariantOf,
		arg.CreatedAt,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Filename,
		&i.ContentType,
		&i.ByteSize,
		&i.Checksum,
		&i.VariantOf,
		&i.CreatedAt,
	)
	return i, err
}

const getFileByKey = `-- name: GetFileByKey :one
SELECT id, "key", filename, content_type, byte_size, checksum, variant_of, created_at FROM files WHERE key = ?
`

func (q *Queries) GetFileByKey(ctx context.Context, key string) (File, error) {
	row := q.db.QueryRowContext(ctx, getFileByKey, key)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Filename,
		&i.ContentType,
		&i.ByteSize,
		&i.Checksum,
		&i.VariantOf,
		&i.CreatedAt,
	)
	return i, err
}

const listAttachmentsForFile = `-- name: ListAttachmentsForFile :many
SELECT id, file_id, record_type, record_id, name, created_at FROM attachments WHERE file_id = ? ORDER BY id
`

func (q *Queries) ListAttachmentsForFile(ctx context.Context, fileID int64) ([]Attachment, error) {
	rows, err := q.db.QueryContext(ctx, listAttachmentsForFile, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attachment
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.RecordType,
			&i.RecordID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFileVariants = `-- name: ListFileVariants :many
SELECT id, "key", filename, content_type, byte_size, checksum, variant_of, created_at FROM files WHERE variant_of = ? ORDER BY id
`

func (q *Queries) ListFileVariants(ctx context.Context, variantOf sql.NullInt64) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, listFileVariants, variantOf)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Filename,
			&i.ContentType,
			&i.ByteSize,
			&i.Checksum,
			&i.VariantOf,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
