// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: files.sql

package query

import (
	"context"
	"database/sql"
)

const countAttachmentsForFile = `-- name: CountAttachmentsForFile :one
SELECT COUNT(*) FROM attachments WHERE file_id = ?
`

func (q *Queries) CountAttachmentsForFile(ctx context.Context, fileID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAttachmentsForFile, fileID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFileKeyContentReferences = `-- name: CountFileKeyContentReferences :one
SELECT
  (SELECT COUNT(*) FROM articles
   WHERE content_html LIKE '%/files/' || ?1 || '%'
      OR meta_image LIKE '%/files/' || ?1 || '%') +
  (SELECT COUNT(*) FROM pages
   WHERE content_html LIKE '%/files/' || ?1 || '%') +
  (SELECT COUNT(*) FROM comments
   WHERE content LIKE '%/files/' || ?1 || '%') +
  (SELECT COUNT(*) FROM settings
   WHERE head_code LIKE '%/files/' || ?1 || '%'
      OR custom_css LIKE '%/files/' || ?1 || '%'
      OR tool_code LIKE '%/files/' || ?1 || '%'
      OR social_links LIKE '%/files/' || ?1 || '%') +
  (SELECT COUNT(*) FROM redirects
   WHERE replacement LIKE '%/files/' || ?1 || '%')
`

// Files can also be referenced by URL (/files/<key>) from stored content:
// admin uploads and RSS-imported images are embedded in article/page bodies
// and never get an attachment row. Keys are alphanumeric (media.ValidKey),
// so the LIKE pattern needs no metacharacter escaping; a prefix collision
// with a longer key only over-protects.
func (q *Queries) CountFileKeyContentReferences(ctx context.Context, key sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFileKeyContentReferences, key)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createAttachment = `-- name: CreateAttachment :exec
INSERT OR IGNORE INTO attachments (file_id, record_type, record_id, name, created_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateAttachmentParams struct {
	FileID     int64
	RecordType string
	RecordID   int64
	Name       string
	CreatedAt  int64
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) error {
	_, err := q.db.ExecContext(ctx, createAttachment,
		arg.FileID,
		arg.RecordType,
		arg.RecordID,
		arg.Name,
		arg.CreatedAt,
	)
	return err
}

const createFile = `-- name: CreateFile :one
INSERT INTO files (key, filename, content_type, byte_size, checksum, variant_of, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, "key", filename, content_type, byte_size, checksum, variant_of, created_at
`

type CreateFileParams struct {
	Key         string
	Filename    string
	ContentType sql.NullString
	ByteSize    int64
	Checksum    sql.NullString
	VariantOf   sql.NullInt64
	CreatedAt   int64
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, createFile,
		arg.Key,
		arg.Filename,
		arg.ContentType,
		arg.ByteSize,
		arg.Checksum,
		arg.VariantOf,
		arg.CreatedAt,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Filename,
		&i.ContentType,
		&i.ByteSize,
		&i.Checksum,
		&i.VariantOf,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAttachmentsForRecord = `-- name: DeleteAttachmentsForRecord :exec
DELETE FROM attachments WHERE record_type = ? AND record_id = ?
`

type DeleteAttachmentsForRecordParams struct {
	RecordType string
	RecordID   int64
}

func (q *Queries) DeleteAttachmentsForRecord(ctx context.Context, arg DeleteAttachmentsForRecordParams) error {
	_, err := q.db.ExecContext(ctx, deleteAttachmentsForRecord, arg.RecordType, arg.RecordID)
	return err
}

const deleteFile = `-- name: DeleteFile :exec
DELETE FROM files WHERE id = ?
`

func (q *Queries) DeleteFile(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteFile, id)
	return err
}

const getFileByID = `-- name: GetFileByID :one
SELECT id, "key", filename, content_type, byte_size, checksum, variant_of, created_at FROM files WHERE id = ?
`

func (q *Queries) GetFileByID(ctx context.Context, id int64) (File, error) {
	row := q.db.QueryRowContext(ctx, getFileByID, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Filename,
		&i.ContentType,
		&i.ByteSize,
		&i.Checksum,
		&i.VariantOf,
		&i.CreatedAt,
	)
	return i, err
}

const getFileByKey = `-- name: GetFileByKey :one
SELECT id, "key", filename, content_type, byte_size, checksum, variant_of, created_at FROM files WHERE key = ?
`

func (q *Queries) GetFileByKey(ctx context.Context, key string) (File, error) {
	row := q.db.QueryRowContext(ctx, getFileByKey, key)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Filename,
		&i.ContentType,
		&i.ByteSize,
		&i.Checksum,
		&i.VariantOf,
		&i.CreatedAt,
	)
	return i, err
}

const listAttachmentFilesForRecord = `-- name: ListAttachmentFilesForRecord :many
SELECT f.id, f.key FROM attachments a
JOIN files f ON f.id = a.file_id
WHERE a.record_type = ? AND a.record_id = ?
`

type ListAttachmentFilesForRecordParams struct {
	RecordType string
	RecordID   int64
}

type ListAttachmentFilesForRecordRow struct {
	ID  int64
	Key string
}

// Media cleanup for record destroy: the files behind one record's
// attachments.
func (q *Queries) ListAttachmentFilesForRecord(ctx context.Context, arg ListAttachmentFilesForRecordParams) ([]ListAttachmentFilesForRecordRow, error) {
	rows, err := q.db.QueryContext(ctx, listAttachmentFilesForRecord, arg.RecordType, arg.RecordID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAttachmentFilesForRecordRow
	for rows.Next() {
		var i ListAttachmentFilesForRecordRow
		if err := rows.Scan(&i.ID, &i.Key); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttachmentsForFile = `-- name: ListAttachmentsForFile :many
SELECT id, file_id, record_type, record_id, name, created_at FROM attachments WHERE file_id = ? ORDER BY id
`

func (q *Queries) ListAttachmentsForFile(ctx context.Context, fileID int64) ([]Attachment, error) {
	rows, err := q.db.QueryContext(ctx, listAttachmentsForFile, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attachment
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.RecordType,
			&i.RecordID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFileVariants = `-- name: ListFileVariants :many
SELECT id, "key", filename, content_type, byte_size, checksum, variant_of, created_at FROM files WHERE variant_of = ? ORDER BY id
`

func (q *Queries) ListFileVariants(ctx context.Context, variantOf sql.NullInt64) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, listFileVariants, variantOf)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Filename,
			&i.ContentType,
			&i.ByteSize,
			&i.Checksum,
			&i.VariantOf,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrphanFileCandidates = `-- name: ListOrphanFileCandidates :many
SELECT f.id, f.key FROM files f
WHERE f.created_at < ?1
  AND f.variant_of IS NULL
  AND NOT EXISTS (SELECT 1 FROM attachments a WHERE a.file_id = f.id)
  AND NOT EXISTS (SELECT 1 FROM static_files sf WHERE sf.file_id = f.id)
  AND NOT EXISTS (SELECT 1 FROM files v JOIN attachments av ON av.file_id = v.id WHERE v.variant_of = f.id)
  AND NOT EXISTS (SELECT 1 FROM files v JOIN static_files sv ON sv.file_id = v.id WHERE v.variant_of = f.id)
ORDER BY f.id
`

type ListOrphanFileCandidatesRow struct {
	ID  int64
	Key string
}

// Startup orphan sweep (jobs.ReapOrphanFiles): family roots (variants are
// reachable only through their original, so they share the original's fate)
// created before the cutoff that no attachment or static_files entry
// references, neither directly nor through a family variant.
func (q *Queries) ListOrphanFileCandidates(ctx context.Context, cutoff int64) ([]ListOrphanFileCandidatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listOrphanFileCandidates, cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrphanFileCandidatesRow
	for rows.Next() {
		var i ListOrphanFileCandidatesRow
		if err := rows.Scan(&i.ID, &i.Key); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
