// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package query

import (
	"context"
	"database/sql"
)

const claimJobRun = `-- name: ClaimJobRun :execrows
UPDATE job_runs SET status = 'running', updated_at = ?
WHERE id = ? AND status = 'queued'
`

type ClaimJobRunParams struct {
	UpdatedAt int64
	ID        int64
}

func (q *Queries) ClaimJobRun(ctx context.Context, arg ClaimJobRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimJobRun, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const completeJobRun = `-- name: CompleteJobRun :exec
UPDATE job_runs SET status = 'done', last_error = NULL, updated_at = ?
WHERE id = ?
`

type CompleteJobRunParams struct {
	UpdatedAt int64
	ID        int64
}

func (q *Queries) CompleteJobRun(ctx context.Context, arg CompleteJobRunParams) error {
	_, err := q.db.ExecContext(ctx, completeJobRun, arg.UpdatedAt, arg.ID)
	return err
}

const deleteFinishedJobRuns = `-- name: DeleteFinishedJobRuns :execrows
DELETE FROM job_runs
WHERE status IN ('done', 'failed') AND updated_at < ?
`

func (q *Queries) DeleteFinishedJobRuns(ctx context.Context, updatedAt int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteFinishedJobRuns, updatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteOldActivityLogs = `-- name: DeleteOldActivityLogs :execrows
DELETE FROM activity_logs WHERE created_at < ?
`

func (q *Queries) DeleteOldActivityLogs(ctx context.Context, createdAt int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteOldActivityLogs, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const enqueueJobRun = `-- name: EnqueueJobRun :execlastid
INSERT INTO job_runs (kind, payload, run_at, status, attempts, created_at, updated_at)
VALUES (?, ?, ?, 'queued', 0, ?, ?)
`

type EnqueueJobRunParams struct {
	Kind      string
	Payload   sql.NullString
	RunAt     int64
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) EnqueueJobRun(ctx context.Context, arg EnqueueJobRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, enqueueJobRun,
		arg.Kind,
		arg.Payload,
		arg.RunAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const enqueueJobRunUnlessActive = `-- name: EnqueueJobRunUnlessActive :execrows
INSERT INTO job_runs (kind, payload, run_at, status, attempts, created_at, updated_at)
SELECT ?1, ?2, ?3, 'queued', 0, ?4, ?5
WHERE NOT EXISTS (
  SELECT 1 FROM job_runs WHERE kind = ?1 AND status IN ('queued', 'running')
)
`

type EnqueueJobRunUnlessActiveParams struct {
	Kind      string
	Payload   sql.NullString
	RunAt     int64
	CreatedAt int64
	UpdatedAt int64
}

// Dedup variant of EnqueueJobRun for singleton jobs (twitter_sync): inserts
// only when no queued/running row of the same kind exists. The scheduler
// re-fires on a fixed cadence while the due timestamp (last_synced_at) only
// advances after a successful run, so without this a backed-up worker would
// accumulate duplicate rows. Rows affected: 1 = enqueued, 0 = skipped.
func (q *Queries) EnqueueJobRunUnlessActive(ctx context.Context, arg EnqueueJobRunUnlessActiveParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, enqueueJobRunUnlessActive,
		arg.Kind,
		arg.Payload,
		arg.RunAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const failJobRun = `-- name: FailJobRun :exec
UPDATE job_runs SET status = 'failed', attempts = ?, last_error = ?, updated_at = ?
WHERE id = ?
`

type FailJobRunParams struct {
	Attempts  int64
	LastError sql.NullString
	UpdatedAt int64
	ID        int64
}

func (q *Queries) FailJobRun(ctx context.Context, arg FailJobRunParams) error {
	_, err := q.db.ExecContext(ctx, failJobRun,
		arg.Attempts,
		arg.LastError,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const getDueJobRun = `-- name: GetDueJobRun :one
SELECT id, kind, payload, run_at, status, attempts, last_error, created_at, updated_at FROM job_runs
WHERE status = 'queued' AND run_at <= ?
ORDER BY run_at
LIMIT 1
`

func (q *Queries) GetDueJobRun(ctx context.Context, runAt int64) (JobRun, error) {
	row := q.db.QueryRowContext(ctx, getDueJobRun, runAt)
	var i JobRun
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Payload,
		&i.RunAt,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTwitterSync = `-- name: GetTwitterSync :one
SELECT id, enabled, username, user_id, since_id, start_date, sync_schedule, last_synced_at, last_error, created_at, updated_at FROM twitter_syncs WHERE id = 1
`

func (q *Queries) GetTwitterSync(ctx context.Context) (TwitterSync, error) {
	row := q.db.QueryRowContext(ctx, getTwitterSync)
	var i TwitterSync
	err := row.Scan(
		&i.ID,
		&i.Enabled,
		&i.Username,
		&i.UserID,
		&i.SinceID,
		&i.StartDate,
		&i.SyncSchedule,
		&i.LastSyncedAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveImportJobPayloads = `-- name: ListActiveImportJobPayloads :many
SELECT kind, payload FROM job_runs
WHERE status IN ('queued', 'running')
  AND kind IN ('import_db', 'import_rails', 'twitter_archive_import')
`

type ListActiveImportJobPayloadsRow struct {
	Kind    string
	Payload sql.NullString
}

// Startup orphan-upload cleanup (jobs.CleanupOrphanImportFiles): payloads of
// still-active import jobs reference the data/imports files that must not be
// deleted. The twitter_archive_import payload carries only an import_id; its
// path lives in twitter_archive_imports.source_path.
func (q *Queries) ListActiveImportJobPayloads(ctx context.Context) ([]ListActiveImportJobPayloadsRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveImportJobPayloads)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveImportJobPayloadsRow
	for rows.Next() {
		var i ListActiveImportJobPayloadsRow
		if err := rows.Scan(&i.Kind, &i.Payload); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveTwitterArchiveImportPaths = `-- name: ListActiveTwitterArchiveImportPaths :many
SELECT source_path FROM twitter_archive_imports
WHERE source_path IS NOT NULL AND status IN ('queued', 'running')
`

// Source uploads of still-active imports; the startup orphan cleanup keeps
// them even while their job row is missing (crash between the INSERT and the
// enqueue). Startup recovery fails such rows once they fall behind the
// cutoff, which unprotects the file on the next sweep.
func (q *Queries) ListActiveTwitterArchiveImportPaths(ctx context.Context) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, listActiveTwitterArchiveImportPaths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullString
	for rows.Next() {
		var source_path sql.NullString
		if err := rows.Scan(&source_path); err != nil {
			return nil, err
		}
		items = append(items, source_path)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommentFetchers = `-- name: ListCommentFetchers :many
SELECT platform, comment_fetch_schedule FROM crossposts
WHERE enabled = 1 AND auto_fetch_comments = 1
  AND comment_fetch_schedule IS NOT NULL AND comment_fetch_schedule != ''
`

type ListCommentFetchersRow struct {
	Platform             string
	CommentFetchSchedule sql.NullString
}

func (q *Queries) ListCommentFetchers(ctx context.Context) ([]ListCommentFetchersRow, error) {
	rows, err := q.db.QueryContext(ctx, listCommentFetchers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentFetchersRow
	for rows.Next() {
		var i ListCommentFetchersRow
		if err := rows.Scan(&i.Platform, &i.CommentFetchSchedule); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requeueStaleRunningJobRuns = `-- name: RequeueStaleRunningJobRuns :execrows
UPDATE job_runs SET
  status = CASE WHEN attempts + 1 >= ?1 THEN 'failed' ELSE 'queued' END,
  attempts = attempts + 1,
  last_error = CASE WHEN attempts + 1 >= ?1 THEN ?2 ELSE last_error END,
  updated_at = ?3
WHERE status = 'running' AND updated_at < ?4
`

type RequeueStaleRunningJobRunsParams struct {
	MaxAttempts int64
	CrashError  sql.NullString
	Now         int64
	Cutoff      int64
}

// Startup recovery: rows claimed (running) but untouched since :cutoff belong
// to a dead process; requeue them so they run again. The requeue consumes an
// attempt, and a row whose attempt budget is exhausted by it is failed
// instead of requeued: the claim path never checks attempts, so a plain
// requeue would let a job that reliably crashes the process (OOM/SIGKILL)
// loop forever under Restart=always.
func (q *Queries) RequeueStaleRunningJobRuns(ctx context.Context, arg RequeueStaleRunningJobRunsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, requeueStaleRunningJobRuns,
		arg.MaxAttempts,
		arg.CrashError,
		arg.Now,
		arg.Cutoff,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const rescheduleJobRun = `-- name: RescheduleJobRun :exec
UPDATE job_runs SET status = 'queued', attempts = ?, run_at = ?, last_error = ?, updated_at = ?
WHERE id = ?
`

type RescheduleJobRunParams struct {
	Attempts  int64
	RunAt     int64
	LastError sql.NullString
	UpdatedAt int64
	ID        int64
}

func (q *Queries) RescheduleJobRun(ctx context.Context, arg RescheduleJobRunParams) error {
	_, err := q.db.ExecContext(ctx, rescheduleJobRun,
		arg.Attempts,
		arg.RunAt,
		arg.LastError,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
