// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs_admin.sql

package query

import (
	"context"
)

const countAdminJobRuns = `-- name: CountAdminJobRuns :one
SELECT COUNT(*) FROM job_runs
`

func (q *Queries) CountAdminJobRuns(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdminJobRuns)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAdminJobRunsByStatus = `-- name: CountAdminJobRunsByStatus :one
SELECT COUNT(*) FROM job_runs WHERE status = ?
`

func (q *Queries) CountAdminJobRunsByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdminJobRunsByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listAdminJobRuns = `-- name: ListAdminJobRuns :many

SELECT id, kind, payload, run_at, status, attempts, last_error, created_at, updated_at FROM job_runs ORDER BY id DESC LIMIT ? OFFSET ?
`

type ListAdminJobRunsParams struct {
	Limit  int64
	Offset int64
}

// Admin job_runs read-only list (plan section 5): id DESC, 100 per page,
// optional status filter. No Mission Control-style management actions.
func (q *Queries) ListAdminJobRuns(ctx context.Context, arg ListAdminJobRunsParams) ([]JobRun, error) {
	rows, err := q.db.QueryContext(ctx, listAdminJobRuns, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobRun
	for rows.Next() {
		var i JobRun
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Payload,
			&i.RunAt,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminJobRunsByStatus = `-- name: ListAdminJobRunsByStatus :many
SELECT id, kind, payload, run_at, status, attempts, last_error, created_at, updated_at FROM job_runs WHERE status = ? ORDER BY id DESC LIMIT ? OFFSET ?
`

type ListAdminJobRunsByStatusParams struct {
	Status string
	Limit  int64
	Offset int64
}

func (q *Queries) ListAdminJobRunsByStatus(ctx context.Context, arg ListAdminJobRunsByStatusParams) ([]JobRun, error) {
	rows, err := q.db.QueryContext(ctx, listAdminJobRunsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobRun
	for rows.Next() {
		var i JobRun
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Payload,
			&i.RunAt,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
