// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: kv.sql

package query

import (
	"context"
	"database/sql"
)

const getKVValue = `-- name: GetKVValue :one
SELECT value FROM kv WHERE key = ?
`

func (q *Queries) GetKVValue(ctx context.Context, key string) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getKVValue, key)
	var value sql.NullString
	err := row.Scan(&value)
	return value, err
}

const setKVValue = `-- name: SetKVValue :exec
INSERT INTO kv (key, value, updated_at) VALUES (?, ?, ?)
ON CONFLICT(key) DO UPDATE SET value = excluded.value, updated_at = excluded.updated_at
`

type SetKVValueParams struct {
	Key       string
	Value     sql.NullString
	UpdatedAt int64
}

func (q *Queries) SetKVValue(ctx context.Context, arg SetKVValueParams) error {
	_, err := q.db.ExecContext(ctx, setKVValue, arg.Key, arg.Value, arg.UpdatedAt)
	return err
}
