// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package query

import (
	"database/sql"
)

type ActivityLog struct {
	ID          int64
	Level       int64
	Action      sql.NullString
	Target      sql.NullString
	Description sql.NullString
	CreatedAt   int64
	UpdatedAt   int64
}

type Article struct {
	ID                          int64
	Title                       sql.NullString
	Slug                        sql.NullString
	ContentHtml                 sql.NullString
	ContentType                 string
	Description                 sql.NullString
	Excerpt                     sql.NullString
	MetaDescription             sql.NullString
	MetaTitle                   sql.NullString
	MetaImage                   sql.NullString
	SourceAuthor                sql.NullString
	SourceUrl                   sql.NullString
	SourceContent               sql.NullString
	Status                      int64
	Comment                     int64
	ScheduledAt                 sql.NullInt64
	ScheduledCrosspostPlatforms string
	ScheduledSendNewsletter     int64
	CreatedAt                   int64
	UpdatedAt                   int64
	ContentMarkdown             sql.NullString
}

type ArticleTag struct {
	ID        int64
	ArticleID int64
	TagID     int64
	CreatedAt int64
	UpdatedAt int64
}

type Attachment struct {
	ID         int64
	FileID     int64
	RecordType string
	RecordID   int64
	Name       string
	CreatedAt  int64
}

type Comment struct {
	ID              int64
	CommentableType sql.NullString
	CommentableID   sql.NullInt64
	ArticleID       sql.NullInt64
	ParentID        sql.NullInt64
	AuthorName      string
	AuthorEmail     sql.NullString
	AuthorUrl       sql.NullString
	AuthorUsername  sql.NullString
	AuthorAvatarUrl sql.NullString
	Content         string
	Status          int64
	Platform        sql.NullString
	ExternalID      sql.NullString
	Url             sql.NullString
	PublishedAt     sql.NullInt64
	CreatedAt       int64
	UpdatedAt       int64
}

type Crosspost struct {
	ID                   int64
	Platform             string
	Enabled              int64
	ApiKey               sql.NullString
	ApiKeySecret         sql.NullString
	AccessToken          sql.NullString
	AccessTokenSecret    sql.NullString
	ClientID             sql.NullString
	ClientKey            sql.NullString
	ClientSecret         sql.NullString
	AppPassword          sql.NullString
	RefreshToken         sql.NullString
	TokenExpiresAt       sql.NullInt64
	ServerUrl            sql.NullString
	Username             sql.NullString
	MaxCharacters        sql.NullInt64
	AutoFetchComments    int64
	CommentFetchSchedule sql.NullString
	Settings             sql.NullString
	CreatedAt            int64
	UpdatedAt            int64
}

type File struct {
	ID          int64
	Key         string
	Filename    string
	ContentType sql.NullString
	ByteSize    int64
	Checksum    sql.NullString
	VariantOf   sql.NullInt64
	CreatedAt   int64
}

type JobRun struct {
	ID        int64
	Kind      string
	Payload   sql.NullString
	RunAt     int64
	Status    string
	Attempts  int64
	LastError sql.NullString
	CreatedAt int64
	UpdatedAt int64
}

type Kv struct {
	Key       string
	Value     sql.NullString
	UpdatedAt int64
}

type Listmonk struct {
	ID         int64
	Url        sql.NullString
	Username   sql.NullString
	ApiKey     sql.NullString
	ListID     sql.NullInt64
	TemplateID sql.NullInt64
	Enabled    int64
	CreatedAt  int64
	UpdatedAt  int64
}

type NewsletterSetting struct {
	ID                 int64
	Enabled            int64
	Provider           string
	FromEmail          sql.NullString
	SmtpAddress        sql.NullString
	SmtpPort           sql.NullInt64
	SmtpUserName       sql.NullString
	SmtpPassword       sql.NullString
	SmtpDomain         sql.NullString
	SmtpAuthentication sql.NullString
	SmtpEnableStarttls sql.NullInt64
	CreatedAt          int64
	UpdatedAt          int64
}

type Page struct {
	ID              int64
	Title           sql.NullString
	Slug            sql.NullString
	ContentHtml     sql.NullString
	ContentType     string
	RedirectUrl     sql.NullString
	PageOrder       int64
	Status          int64
	Comment         int64
	ScheduledAt     sql.NullInt64
	CreatedAt       int64
	UpdatedAt       int64
	ContentMarkdown sql.NullString
}

type Redirect struct {
	ID          int64
	Regex       string
	Replacement string
	Enabled     int64
	Permanent   int64
	CreatedAt   int64
	UpdatedAt   int64
}

type Session struct {
	ID        int64
	Token     string
	UserID    int64
	IpAddress sql.NullString
	UserAgent sql.NullString
	CreatedAt int64
	UpdatedAt int64
}

type Setting struct {
	ID             int64
	Title          sql.NullString
	Description    sql.NullString
	Author         sql.NullString
	Url            sql.NullString
	TimeZone       string
	HeadCode       sql.NullString
	CustomCss      sql.NullString
	ToolCode       sql.NullString
	Giscus         sql.NullString
	SocialLinks    sql.NullString
	SetupCompleted int64
	CreatedAt      int64
	UpdatedAt      int64
}

type SocialMediaPost struct {
	ID        int64
	ArticleID int64
	Platform  string
	Url       string
	CreatedAt int64
	UpdatedAt int64
}

type StaticFile struct {
	ID          int64
	Filename    string
	Description sql.NullString
	FileID      int64
	CreatedAt   int64
	UpdatedAt   int64
}

type Subscriber struct {
	ID                int64
	Email             string
	ConfirmationToken sql.NullString
	UnsubscribeToken  sql.NullString
	ConfirmedAt       sql.NullInt64
	UnsubscribedAt    sql.NullInt64
	CreatedAt         int64
	UpdatedAt         int64
}

type SubscriberTag struct {
	ID           int64
	SubscriberID int64
	TagID        int64
	CreatedAt    int64
	UpdatedAt    int64
}

type Tag struct {
	ID        int64
	Name      string
	Slug      string
	CreatedAt int64
	UpdatedAt int64
}

type TwitterArchiveConnection struct {
	ID               int64
	AccountID        string
	ScreenName       sql.NullString
	UserLink         sql.NullString
	RelationshipType string
	CreatedAt        int64
	UpdatedAt        int64
}

type TwitterArchiveImport struct {
	ID              int64
	Status          string
	Progress        int64
	TotalItemsCount int64
	TweetsCount     int64
	FollowersCount  int64
	FollowingCount  int64
	LikesCount      int64
	SourceFilename  string
	SourcePath      sql.NullString
	StatusMessage   sql.NullString
	ErrorMessage    sql.NullString
	QueuedAt        int64
	StartedAt       sql.NullInt64
	FinishedAt      sql.NullInt64
	ActiveSlot      sql.NullInt64
	CreatedAt       int64
	UpdatedAt       int64
}

type TwitterArchiveLike struct {
	ID          int64
	TweetID     string
	FullText    sql.NullString
	ExpandedUrl sql.NullString
	CreatedAt   int64
	UpdatedAt   int64
}

type TwitterArchiveTweet struct {
	ID         int64
	TweetID    string
	ScreenName string
	FullText   string
	EntryType  string
	TweetedAt  int64
	CreatedAt  int64
	UpdatedAt  int64
}

type TwitterSync struct {
	ID           int64
	Enabled      int64
	Username     sql.NullString
	UserID       sql.NullString
	SinceID      sql.NullString
	StartDate    sql.NullString
	SyncSchedule string
	LastSyncedAt sql.NullInt64
	LastError    sql.NullString
	CreatedAt    int64
	UpdatedAt    int64
}

type User struct {
	ID             int64
	UserName       string
	PasswordDigest string
	CreatedAt      int64
	UpdatedAt      int64
}
