// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: newsletter.sql

package query

import (
	"context"
	"database/sql"
)

const ensureListmonk = `-- name: EnsureListmonk :exec
INSERT INTO listmonks (id, created_at, updated_at)
VALUES (1, ?, ?)
ON CONFLICT (id) DO NOTHING
`

type EnsureListmonkParams struct {
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) EnsureListmonk(ctx context.Context, arg EnsureListmonkParams) error {
	_, err := q.db.ExecContext(ctx, ensureListmonk, arg.CreatedAt, arg.UpdatedAt)
	return err
}

const ensureNewsletterSetting = `-- name: EnsureNewsletterSetting :exec

INSERT INTO newsletter_settings (id, created_at, updated_at)
VALUES (1, ?, ?)
ON CONFLICT (id) DO NOTHING
`

type EnsureNewsletterSettingParams struct {
	CreatedAt int64
	UpdatedAt int64
}

// Newsletter settings singleton (id = 1), mirroring NewsletterSetting.instance,
// and the listmonk singleton (id = 1), mirroring Listmonk.first_or_initialize.
// Reads reuse GetNewsletterSettings / GetListmonk from articles_admin.sql.
func (q *Queries) EnsureNewsletterSetting(ctx context.Context, arg EnsureNewsletterSettingParams) error {
	_, err := q.db.ExecContext(ctx, ensureNewsletterSetting, arg.CreatedAt, arg.UpdatedAt)
	return err
}

const updateListmonk = `-- name: UpdateListmonk :exec
UPDATE listmonks
SET url = ?, username = ?, api_key = ?, list_id = ?, template_id = ?,
    enabled = ?, updated_at = ?
WHERE id = 1
`

type UpdateListmonkParams struct {
	Url        sql.NullString
	Username   sql.NullString
	ApiKey     sql.NullString
	ListID     sql.NullInt64
	TemplateID sql.NullInt64
	Enabled    int64
	UpdatedAt  int64
}

func (q *Queries) UpdateListmonk(ctx context.Context, arg UpdateListmonkParams) error {
	_, err := q.db.ExecContext(ctx, updateListmonk,
		arg.Url,
		arg.Username,
		arg.ApiKey,
		arg.ListID,
		arg.TemplateID,
		arg.Enabled,
		arg.UpdatedAt,
	)
	return err
}

const updateNewsletterSetting = `-- name: UpdateNewsletterSetting :exec
UPDATE newsletter_settings
SET enabled = ?, provider = ?, from_email = ?,
    smtp_address = ?, smtp_port = ?, smtp_user_name = ?, smtp_password = ?,
    smtp_domain = ?, smtp_authentication = ?, smtp_enable_starttls = ?,
    updated_at = ?
WHERE id = 1
`

type UpdateNewsletterSettingParams struct {
	Enabled            int64
	Provider           string
	FromEmail          sql.NullString
	SmtpAddress        sql.NullString
	SmtpPort           sql.NullInt64
	SmtpUserName       sql.NullString
	SmtpPassword       sql.NullString
	SmtpDomain         sql.NullString
	SmtpAuthentication sql.NullString
	SmtpEnableStarttls sql.NullInt64
	UpdatedAt          int64
}

func (q *Queries) UpdateNewsletterSetting(ctx context.Context, arg UpdateNewsletterSettingParams) error {
	_, err := q.db.ExecContext(ctx, updateNewsletterSetting,
		arg.Enabled,
		arg.Provider,
		arg.FromEmail,
		arg.SmtpAddress,
		arg.SmtpPort,
		arg.SmtpUserName,
		arg.SmtpPassword,
		arg.SmtpDomain,
		arg.SmtpAuthentication,
		arg.SmtpEnableStarttls,
		arg.UpdatedAt,
	)
	return err
}
