// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: newsletter_send.sql

package query

import (
	"context"
)

const listAllSubscriberTags = `-- name: ListAllSubscriberTags :many
SELECT subscriber_id, tag_id FROM subscriber_tags ORDER BY id
`

type ListAllSubscriberTagsRow struct {
	SubscriberID int64
	TagID        int64
}

func (q *Queries) ListAllSubscriberTags(ctx context.Context) ([]ListAllSubscriberTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllSubscriberTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllSubscriberTagsRow
	for rows.Next() {
		var i ListAllSubscriberTagsRow
		if err := rows.Scan(&i.SubscriberID, &i.TagID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllSubscribers = `-- name: ListAllSubscribers :many

SELECT id, email, confirmation_token, unsubscribe_token, confirmed_at, unsubscribed_at, created_at, updated_at FROM subscribers ORDER BY id
`

// Newsletter send jobs (plan T19): recipient selection for the native
// sender. The tag intersection itself runs in Go (subscribers.FilterRelevant),
// mirroring the Ruby select in NativeNewsletterSenderJob#perform.
// Article/subscriber/comment reads reuse GetArticleByID, ListTagsForArticle,
// GetSubscriberByID, GetCommentByID and the GetCommentable* queries.
// Subscriber.active.includes(:tags): every row; FilterRelevant drops the
// inactive ones, so the scan stays unordered-by-state like the Rails scope.
func (q *Queries) ListAllSubscribers(ctx context.Context) ([]Subscriber, error) {
	rows, err := q.db.QueryContext(ctx, listAllSubscribers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscriber
	for rows.Next() {
		var i Subscriber
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.ConfirmationToken,
			&i.UnsubscribeToken,
			&i.ConfirmedAt,
			&i.UnsubscribedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
