// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pages_admin.sql

package query

import (
	"context"
	"database/sql"
)

const adminPageSlugCount = `-- name: AdminPageSlugCount :one
SELECT COUNT(*) FROM pages WHERE slug = ? AND id != ?
`

type AdminPageSlugCountParams struct {
	Slug sql.NullString
	ID   int64
}

// Uniqueness check; excludeID is 0 on create so any row matches.
func (q *Queries) AdminPageSlugCount(ctx context.Context, arg AdminPageSlugCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, adminPageSlugCount, arg.Slug, arg.ID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const cancelQueuedPublishPageJobs = `-- name: CancelQueuedPublishPageJobs :execrows
UPDATE job_runs SET status = 'failed', last_error = ?, updated_at = ?
WHERE kind = 'publish_page' AND status = 'queued'
  AND json_extract(payload, '$.page_id') = CAST(?3 AS INTEGER)
`

type CancelQueuedPublishPageJobsParams struct {
	LastError sql.NullString
	UpdatedAt int64
	PageID    int64
}

// Drops still-queued publish_page jobs for one page before a new schedule is
// enqueued (article-side cancel_old_jobs semantics, per task T10).
func (q *Queries) CancelQueuedPublishPageJobs(ctx context.Context, arg CancelQueuedPublishPageJobsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, cancelQueuedPublishPageJobs, arg.LastError, arg.UpdatedAt, arg.PageID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countAdminPages = `-- name: CountAdminPages :one
SELECT COUNT(*) FROM pages
`

func (q *Queries) CountAdminPages(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdminPages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAdminPagesByStatus = `-- name: CountAdminPagesByStatus :one
SELECT COUNT(*) FROM pages WHERE status = ?
`

func (q *Queries) CountAdminPagesByStatus(ctx context.Context, status int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdminPagesByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPage = `-- name: CreatePage :one
INSERT INTO pages (
  title, slug, content_html, content_type, redirect_url,
  page_order, status, comment, scheduled_at,
  created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, title, slug, content_html, content_type, redirect_url, page_order, status, comment, scheduled_at, created_at, updated_at
`

type CreatePageParams struct {
	Title       sql.NullString
	Slug        sql.NullString
	ContentHtml sql.NullString
	ContentType string
	RedirectUrl sql.NullString
	PageOrder   int64
	Status      int64
	Comment     int64
	ScheduledAt sql.NullInt64
	CreatedAt   int64
	UpdatedAt   int64
}

func (q *Queries) CreatePage(ctx context.Context, arg CreatePageParams) (Page, error) {
	row := q.db.QueryRowContext(ctx, createPage,
		arg.Title,
		arg.Slug,
		arg.ContentHtml,
		arg.ContentType,
		arg.RedirectUrl,
		arg.PageOrder,
		arg.Status,
		arg.Comment,
		arg.ScheduledAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.ContentHtml,
		&i.ContentType,
		&i.RedirectUrl,
		&i.PageOrder,
		&i.Status,
		&i.Comment,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePageByID = `-- name: DeletePageByID :exec
DELETE FROM pages WHERE id = ?
`

func (q *Queries) DeletePageByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePageByID, id)
	return err
}

const deletePageComments = `-- name: DeletePageComments :exec
DELETE FROM comments WHERE commentable_type = 'Page' AND commentable_id = ?
`

// Page has_many :comments, as: :commentable, dependent: :destroy; the
// polymorphic association has no FK, so real deletes clean it up by hand.
func (q *Queries) DeletePageComments(ctx context.Context, commentableID sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, deletePageComments, commentableID)
	return err
}

const getAdminPageBySlug = `-- name: GetAdminPageBySlug :one

SELECT id, title, slug, content_html, content_type, redirect_url, page_order, status, comment, scheduled_at, created_at, updated_at FROM pages WHERE slug = ?
`

// Admin page management (plan section 4.1, task T10). Mirrors
// Admin::PagesController: lookup by slug, page_order DESC listing with a
// 100-per-page window, and cancellation of superseded publish_page jobs.
func (q *Queries) GetAdminPageBySlug(ctx context.Context, slug sql.NullString) (Page, error) {
	row := q.db.QueryRowContext(ctx, getAdminPageBySlug, slug)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.ContentHtml,
		&i.ContentType,
		&i.RedirectUrl,
		&i.PageOrder,
		&i.Status,
		&i.Comment,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAdminPages = `-- name: ListAdminPages :many
SELECT id, title, slug, content_html, content_type, redirect_url, page_order, status, comment, scheduled_at, created_at, updated_at FROM pages
ORDER BY page_order DESC
LIMIT ? OFFSET ?
`

type ListAdminPagesParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListAdminPages(ctx context.Context, arg ListAdminPagesParams) ([]Page, error) {
	rows, err := q.db.QueryContext(ctx, listAdminPages, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Page
	for rows.Next() {
		var i Page
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.ContentHtml,
			&i.ContentType,
			&i.RedirectUrl,
			&i.PageOrder,
			&i.Status,
			&i.Comment,
			&i.ScheduledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminPagesByStatus = `-- name: ListAdminPagesByStatus :many
SELECT id, title, slug, content_html, content_type, redirect_url, page_order, status, comment, scheduled_at, created_at, updated_at FROM pages
WHERE status = ?
ORDER BY page_order DESC
LIMIT ? OFFSET ?
`

type ListAdminPagesByStatusParams struct {
	Status int64
	Limit  int64
	Offset int64
}

func (q *Queries) ListAdminPagesByStatus(ctx context.Context, arg ListAdminPagesByStatusParams) ([]Page, error) {
	rows, err := q.db.QueryContext(ctx, listAdminPagesByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Page
	for rows.Next() {
		var i Page
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.ContentHtml,
			&i.ContentType,
			&i.RedirectUrl,
			&i.PageOrder,
			&i.Status,
			&i.Comment,
			&i.ScheduledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePage = `-- name: UpdatePage :one
UPDATE pages
SET title = ?, slug = ?, content_html = ?, content_type = ?, redirect_url = ?,
    page_order = ?, status = ?, comment = ?, scheduled_at = ?, updated_at = ?
WHERE id = ?
RETURNING id, title, slug, content_html, content_type, redirect_url, page_order, status, comment, scheduled_at, created_at, updated_at
`

type UpdatePageParams struct {
	Title       sql.NullString
	Slug        sql.NullString
	ContentHtml sql.NullString
	ContentType string
	RedirectUrl sql.NullString
	PageOrder   int64
	Status      int64
	Comment     int64
	ScheduledAt sql.NullInt64
	UpdatedAt   int64
	ID          int64
}

func (q *Queries) UpdatePage(ctx context.Context, arg UpdatePageParams) (Page, error) {
	row := q.db.QueryRowContext(ctx, updatePage,
		arg.Title,
		arg.Slug,
		arg.ContentHtml,
		arg.ContentType,
		arg.RedirectUrl,
		arg.PageOrder,
		arg.Status,
		arg.Comment,
		arg.ScheduledAt,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.ContentHtml,
		&i.ContentType,
		&i.RedirectUrl,
		&i.PageOrder,
		&i.Status,
		&i.Comment,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePageStatus = `-- name: UpdatePageStatus :exec
UPDATE pages SET status = ?, updated_at = ?
WHERE id = ?
`

type UpdatePageStatusParams struct {
	Status    int64
	UpdatedAt int64
	ID        int64
}

func (q *Queries) UpdatePageStatus(ctx context.Context, arg UpdatePageStatusParams) error {
	_, err := q.db.ExecContext(ctx, updatePageStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}
