// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pages_admin.sql

package query

import (
	"context"
	"database/sql"
)

const adminPageSlugCount = `-- name: AdminPageSlugCount :one
SELECT COUNT(*) FROM pages WHERE slug = ? AND id != ?
`

type AdminPageSlugCountParams struct {
	Slug sql.NullString
	ID   int64
}

// Uniqueness check; excludeID is 0 on create so any row matches.
func (q *Queries) AdminPageSlugCount(ctx context.Context, arg AdminPageSlugCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, adminPageSlugCount, arg.Slug, arg.ID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const cancelQueuedPublishPageJobs = `-- name: CancelQueuedPublishPageJobs :execrows
UPDATE job_runs SET status = 'failed', last_error = ?, updated_at = ?
WHERE kind = 'publish_page' AND status = 'queued'
  AND json_extract(payload, '$.page_id') = CAST(?3 AS INTEGER)
`

type CancelQueuedPublishPageJobsParams struct {
	LastError sql.NullString
	UpdatedAt int64
	PageID    int64
}

// Drops still-queued publish_page jobs for one page before a new schedule is
// enqueued (article-side cancel_old_jobs semantics, per task T10).
func (q *Queries) CancelQueuedPublishPageJobs(ctx context.Context, arg CancelQueuedPublishPageJobsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, cancelQueuedPublishPageJobs, arg.LastError, arg.UpdatedAt, arg.PageID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countAdminPagesFiltered = `-- name: CountAdminPagesFiltered :one
SELECT COUNT(*) FROM pages
WHERE (CAST(?1 AS INTEGER) = -1 OR status = CAST(?1 AS INTEGER))
`

func (q *Queries) CountAdminPagesFiltered(ctx context.Context, statusFilter int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdminPagesFiltered, statusFilter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPage = `-- name: CreatePage :one
INSERT INTO pages (
  title, slug, content_html, content_type, content_markdown, redirect_url,
  page_order, status, comment, scheduled_at,
  created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, title, slug, content_html, content_type, redirect_url, page_order, status, comment, scheduled_at, created_at, updated_at, content_markdown
`

type CreatePageParams struct {
	Title           sql.NullString
	Slug            sql.NullString
	ContentHtml     sql.NullString
	ContentType     string
	ContentMarkdown sql.NullString
	RedirectUrl     sql.NullString
	PageOrder       int64
	Status          int64
	Comment         int64
	ScheduledAt     sql.NullInt64
	CreatedAt       int64
	UpdatedAt       int64
}

func (q *Queries) CreatePage(ctx context.Context, arg CreatePageParams) (Page, error) {
	row := q.db.QueryRowContext(ctx, createPage,
		arg.Title,
		arg.Slug,
		arg.ContentHtml,
		arg.ContentType,
		arg.ContentMarkdown,
		arg.RedirectUrl,
		arg.PageOrder,
		arg.Status,
		arg.Comment,
		arg.ScheduledAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.ContentHtml,
		&i.ContentType,
		&i.RedirectUrl,
		&i.PageOrder,
		&i.Status,
		&i.Comment,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContentMarkdown,
	)
	return i, err
}

const deletePageByID = `-- name: DeletePageByID :exec
DELETE FROM pages WHERE id = ?
`

func (q *Queries) DeletePageByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePageByID, id)
	return err
}

const deletePageComments = `-- name: DeletePageComments :exec
DELETE FROM comments WHERE commentable_type = 'Page' AND commentable_id = ?
`

// Page has_many :comments, as: :commentable, dependent: :destroy; the
// polymorphic association has no FK, so real deletes clean it up by hand.
func (q *Queries) DeletePageComments(ctx context.Context, commentableID sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, deletePageComments, commentableID)
	return err
}

const getAdminPageBySlug = `-- name: GetAdminPageBySlug :one

SELECT id, title, slug, content_html, content_type, redirect_url, page_order, status, comment, scheduled_at, created_at, updated_at, content_markdown FROM pages WHERE slug = ?
`

// Admin page management (plan section 4.1, task T10). Mirrors
// Admin::PagesController: lookup by slug, page_order DESC listing with a
// 100-per-page window, and cancellation of superseded publish_page jobs.
func (q *Queries) GetAdminPageBySlug(ctx context.Context, slug sql.NullString) (Page, error) {
	row := q.db.QueryRowContext(ctx, getAdminPageBySlug, slug)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.ContentHtml,
		&i.ContentType,
		&i.RedirectUrl,
		&i.PageOrder,
		&i.Status,
		&i.Comment,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContentMarkdown,
	)
	return i, err
}

const listAdminPagesFilteredCreatedAsc = `-- name: ListAdminPagesFilteredCreatedAsc :many
SELECT id, title, slug, content_html, content_type, redirect_url, page_order, status, comment, scheduled_at, created_at, updated_at, content_markdown FROM pages
WHERE (CAST(?1 AS INTEGER) = -1 OR status = CAST(?1 AS INTEGER))
ORDER BY created_at ASC, id ASC
LIMIT ?3 OFFSET ?2
`

type ListAdminPagesFilteredCreatedAscParams struct {
	StatusFilter int64
	Offset       int64
	Limit        int64
}

func (q *Queries) ListAdminPagesFilteredCreatedAsc(ctx context.Context, arg ListAdminPagesFilteredCreatedAscParams) ([]Page, error) {
	rows, err := q.db.QueryContext(ctx, listAdminPagesFilteredCreatedAsc, arg.StatusFilter, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Page
	for rows.Next() {
		var i Page
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.ContentHtml,
			&i.ContentType,
			&i.RedirectUrl,
			&i.PageOrder,
			&i.Status,
			&i.Comment,
			&i.ScheduledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContentMarkdown,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminPagesFilteredCreatedDesc = `-- name: ListAdminPagesFilteredCreatedDesc :many
SELECT id, title, slug, content_html, content_type, redirect_url, page_order, status, comment, scheduled_at, created_at, updated_at, content_markdown FROM pages
WHERE (CAST(?1 AS INTEGER) = -1 OR status = CAST(?1 AS INTEGER))
ORDER BY created_at DESC, id DESC
LIMIT ?3 OFFSET ?2
`

type ListAdminPagesFilteredCreatedDescParams struct {
	StatusFilter int64
	Offset       int64
	Limit        int64
}

func (q *Queries) ListAdminPagesFilteredCreatedDesc(ctx context.Context, arg ListAdminPagesFilteredCreatedDescParams) ([]Page, error) {
	rows, err := q.db.QueryContext(ctx, listAdminPagesFilteredCreatedDesc, arg.StatusFilter, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Page
	for rows.Next() {
		var i Page
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.ContentHtml,
			&i.ContentType,
			&i.RedirectUrl,
			&i.PageOrder,
			&i.Status,
			&i.Comment,
			&i.ScheduledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContentMarkdown,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminPagesFilteredOrderAsc = `-- name: ListAdminPagesFilteredOrderAsc :many
SELECT id, title, slug, content_html, content_type, redirect_url, page_order, status, comment, scheduled_at, created_at, updated_at, content_markdown FROM pages
WHERE (CAST(?1 AS INTEGER) = -1 OR status = CAST(?1 AS INTEGER))
ORDER BY page_order ASC, id ASC
LIMIT ?3 OFFSET ?2
`

type ListAdminPagesFilteredOrderAscParams struct {
	StatusFilter int64
	Offset       int64
	Limit        int64
}

func (q *Queries) ListAdminPagesFilteredOrderAsc(ctx context.Context, arg ListAdminPagesFilteredOrderAscParams) ([]Page, error) {
	rows, err := q.db.QueryContext(ctx, listAdminPagesFilteredOrderAsc, arg.StatusFilter, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Page
	for rows.Next() {
		var i Page
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.ContentHtml,
			&i.ContentType,
			&i.RedirectUrl,
			&i.PageOrder,
			&i.Status,
			&i.Comment,
			&i.ScheduledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContentMarkdown,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminPagesFilteredOrderDesc = `-- name: ListAdminPagesFilteredOrderDesc :many
SELECT id, title, slug, content_html, content_type, redirect_url, page_order, status, comment, scheduled_at, created_at, updated_at, content_markdown FROM pages
WHERE (CAST(?1 AS INTEGER) = -1 OR status = CAST(?1 AS INTEGER))
ORDER BY page_order DESC, id DESC
LIMIT ?3 OFFSET ?2
`

type ListAdminPagesFilteredOrderDescParams struct {
	StatusFilter int64
	Offset       int64
	Limit        int64
}

// Admin list: optional status filter (status_filter -1 = all), 100 per page.
// sqlc cannot parameterize the ORDER BY column or direction, so the six sort
// combinations the admin list offers (page_order/created_at/updated_at x
// asc/desc) are separate queries; the default is page_order DESC. id breaks
// sort-key ties (page_order ties are common) so pagination is stable. The
// CASTs pin the reused filter param's Go type (without them sqlc falls back
// to interface{}).
func (q *Queries) ListAdminPagesFilteredOrderDesc(ctx context.Context, arg ListAdminPagesFilteredOrderDescParams) ([]Page, error) {
	rows, err := q.db.QueryContext(ctx, listAdminPagesFilteredOrderDesc, arg.StatusFilter, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Page
	for rows.Next() {
		var i Page
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.ContentHtml,
			&i.ContentType,
			&i.RedirectUrl,
			&i.PageOrder,
			&i.Status,
			&i.Comment,
			&i.ScheduledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContentMarkdown,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminPagesFilteredUpdatedAsc = `-- name: ListAdminPagesFilteredUpdatedAsc :many
SELECT id, title, slug, content_html, content_type, redirect_url, page_order, status, comment, scheduled_at, created_at, updated_at, content_markdown FROM pages
WHERE (CAST(?1 AS INTEGER) = -1 OR status = CAST(?1 AS INTEGER))
ORDER BY updated_at ASC, id ASC
LIMIT ?3 OFFSET ?2
`

type ListAdminPagesFilteredUpdatedAscParams struct {
	StatusFilter int64
	Offset       int64
	Limit        int64
}

func (q *Queries) ListAdminPagesFilteredUpdatedAsc(ctx context.Context, arg ListAdminPagesFilteredUpdatedAscParams) ([]Page, error) {
	rows, err := q.db.QueryContext(ctx, listAdminPagesFilteredUpdatedAsc, arg.StatusFilter, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Page
	for rows.Next() {
		var i Page
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.ContentHtml,
			&i.ContentType,
			&i.RedirectUrl,
			&i.PageOrder,
			&i.Status,
			&i.Comment,
			&i.ScheduledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContentMarkdown,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminPagesFilteredUpdatedDesc = `-- name: ListAdminPagesFilteredUpdatedDesc :many
SELECT id, title, slug, content_html, content_type, redirect_url, page_order, status, comment, scheduled_at, created_at, updated_at, content_markdown FROM pages
WHERE (CAST(?1 AS INTEGER) = -1 OR status = CAST(?1 AS INTEGER))
ORDER BY updated_at DESC, id DESC
LIMIT ?3 OFFSET ?2
`

type ListAdminPagesFilteredUpdatedDescParams struct {
	StatusFilter int64
	Offset       int64
	Limit        int64
}

func (q *Queries) ListAdminPagesFilteredUpdatedDesc(ctx context.Context, arg ListAdminPagesFilteredUpdatedDescParams) ([]Page, error) {
	rows, err := q.db.QueryContext(ctx, listAdminPagesFilteredUpdatedDesc, arg.StatusFilter, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Page
	for rows.Next() {
		var i Page
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.ContentHtml,
			&i.ContentType,
			&i.RedirectUrl,
			&i.PageOrder,
			&i.Status,
			&i.Comment,
			&i.ScheduledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContentMarkdown,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePage = `-- name: UpdatePage :one
UPDATE pages
SET title = ?, slug = ?, content_html = ?, content_type = ?, content_markdown = ?, redirect_url = ?,
    page_order = ?, status = ?, comment = ?, scheduled_at = ?, updated_at = ?
WHERE id = ?
RETURNING id, title, slug, content_html, content_type, redirect_url, page_order, status, comment, scheduled_at, created_at, updated_at, content_markdown
`

type UpdatePageParams struct {
	Title           sql.NullString
	Slug            sql.NullString
	ContentHtml     sql.NullString
	ContentType     string
	ContentMarkdown sql.NullString
	RedirectUrl     sql.NullString
	PageOrder       int64
	Status          int64
	Comment         int64
	ScheduledAt     sql.NullInt64
	UpdatedAt       int64
	ID              int64
}

func (q *Queries) UpdatePage(ctx context.Context, arg UpdatePageParams) (Page, error) {
	row := q.db.QueryRowContext(ctx, updatePage,
		arg.Title,
		arg.Slug,
		arg.ContentHtml,
		arg.ContentType,
		arg.ContentMarkdown,
		arg.RedirectUrl,
		arg.PageOrder,
		arg.Status,
		arg.Comment,
		arg.ScheduledAt,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.ContentHtml,
		&i.ContentType,
		&i.RedirectUrl,
		&i.PageOrder,
		&i.Status,
		&i.Comment,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContentMarkdown,
	)
	return i, err
}

const updatePageStatus = `-- name: UpdatePageStatus :exec
UPDATE pages SET status = ?, updated_at = ?
WHERE id = ?
`

type UpdatePageStatusParams struct {
	Status    int64
	UpdatedAt int64
	ID        int64
}

func (q *Queries) UpdatePageStatus(ctx context.Context, arg UpdatePageStatusParams) error {
	_, err := q.db.ExecContext(ctx, updatePageStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}
