// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: publish.sql

package query

import (
	"context"
	"database/sql"
)

const getArticlePublishState = `-- name: GetArticlePublishState :one
SELECT status, scheduled_at, scheduled_crosspost_platforms, scheduled_send_newsletter
FROM articles WHERE id = ?
`

type GetArticlePublishStateRow struct {
	Status                      int64
	ScheduledAt                 sql.NullInt64
	ScheduledCrosspostPlatforms string
	ScheduledSendNewsletter     int64
}

func (q *Queries) GetArticlePublishState(ctx context.Context, id int64) (GetArticlePublishStateRow, error) {
	row := q.db.QueryRowContext(ctx, getArticlePublishState, id)
	var i GetArticlePublishStateRow
	err := row.Scan(
		&i.Status,
		&i.ScheduledAt,
		&i.ScheduledCrosspostPlatforms,
		&i.ScheduledSendNewsletter,
	)
	return i, err
}

const getPagePublishState = `-- name: GetPagePublishState :one
SELECT status, scheduled_at FROM pages WHERE id = ?
`

type GetPagePublishStateRow struct {
	Status      int64
	ScheduledAt sql.NullInt64
}

func (q *Queries) GetPagePublishState(ctx context.Context, id int64) (GetPagePublishStateRow, error) {
	row := q.db.QueryRowContext(ctx, getPagePublishState, id)
	var i GetPagePublishStateRow
	err := row.Scan(&i.Status, &i.ScheduledAt)
	return i, err
}

const publishScheduledArticle = `-- name: PublishScheduledArticle :execrows
UPDATE articles
SET status = ?1,
    created_at = ?2,
    scheduled_at = NULL,
    scheduled_crosspost_platforms = '[]',
    scheduled_send_newsletter = 0,
    updated_at = ?3
WHERE id = ?4 AND status = ?5
`

type PublishScheduledArticleParams struct {
	PublishStatus  int64
	CreatedAt      int64
	UpdatedAt      int64
	ID             int64
	ScheduleStatus int64
}

// Flips schedule -> publish, backfills created_at with scheduled_at, and
// clears the consumed snapshot. Guarded by the schedule status so a rerun
// after a successful flip updates 0 rows and never re-consumes the snapshot.
func (q *Queries) PublishScheduledArticle(ctx context.Context, arg PublishScheduledArticleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, publishScheduledArticle,
		arg.PublishStatus,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ID,
		arg.ScheduleStatus,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const publishScheduledPage = `-- name: PublishScheduledPage :execrows
UPDATE pages
SET status = ?1,
    scheduled_at = NULL,
    updated_at = ?2
WHERE id = ?3 AND status = ?4
`

type PublishScheduledPageParams struct {
	PublishStatus  int64
	UpdatedAt      int64
	ID             int64
	ScheduleStatus int64
}

// Rails Page#publish_scheduled does NOT backfill created_at (unlike Article).
func (q *Queries) PublishScheduledPage(ctx context.Context, arg PublishScheduledPageParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, publishScheduledPage,
		arg.PublishStatus,
		arg.UpdatedAt,
		arg.ID,
		arg.ScheduleStatus,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
