// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: public.sql

package query

import (
	"context"
	"database/sql"
)

const countPublicTags = `-- name: CountPublicTags :one
SELECT COUNT(*) FROM tags
`

func (q *Queries) CountPublicTags(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPublicTags)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPublishedArticles = `-- name: CountPublishedArticles :one
SELECT COUNT(*) FROM articles WHERE status = 1
`

func (q *Queries) CountPublishedArticles(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPublishedArticles)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPublishedArticlesByTag = `-- name: CountPublishedArticlesByTag :one
SELECT COUNT(*) FROM articles
JOIN article_tags ON article_tags.article_id = articles.id
WHERE articles.status = 1 AND article_tags.tag_id = ?
`

func (q *Queries) CountPublishedArticlesByTag(ctx context.Context, tagID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPublishedArticlesByTag, tagID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchPublishedArticles = `-- name: CountSearchPublishedArticles :one
SELECT COUNT(*) FROM articles
WHERE status = 1 AND (
  (title LIKE ? ESCAPE '\') OR
  (slug LIKE ? ESCAPE '\') OR
  (description LIKE ? ESCAPE '\') OR
  (content_html LIKE ? ESCAPE '\')
)
`

type CountSearchPublishedArticlesParams struct {
	Title       sql.NullString
	Slug        sql.NullString
	Description sql.NullString
	ContentHtml sql.NullString
}

func (q *Queries) CountSearchPublishedArticles(ctx context.Context, arg CountSearchPublishedArticlesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSearchPublishedArticles,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.ContentHtml,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPublicArticleBySlug = `-- name: GetPublicArticleBySlug :one

SELECT id, title, slug, content_html, content_type, description, excerpt, meta_description, meta_title, meta_image, source_author, source_url, source_content, status, comment, scheduled_at, scheduled_crosspost_platforms, scheduled_send_newsletter, created_at, updated_at, content_markdown FROM articles WHERE slug = ?
`

// Public site queries (plan T12). Visibility follows plan section 4.1: only
// status = 1 (publish) is listed publicly; show pages additionally accept
// status = 4 (shared) and authenticated previews of any status.
func (q *Queries) GetPublicArticleBySlug(ctx context.Context, slug sql.NullString) (Article, error) {
	row := q.db.QueryRowContext(ctx, getPublicArticleBySlug, slug)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.ContentHtml,
		&i.ContentType,
		&i.Description,
		&i.Excerpt,
		&i.MetaDescription,
		&i.MetaTitle,
		&i.MetaImage,
		&i.SourceAuthor,
		&i.SourceUrl,
		&i.SourceContent,
		&i.Status,
		&i.Comment,
		&i.ScheduledAt,
		&i.ScheduledCrosspostPlatforms,
		&i.ScheduledSendNewsletter,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContentMarkdown,
	)
	return i, err
}

const getPublicPageBySlug = `-- name: GetPublicPageBySlug :one
SELECT id, title, slug, content_html, content_type, redirect_url, page_order, status, comment, scheduled_at, created_at, updated_at, content_markdown FROM pages WHERE slug = ?
`

func (q *Queries) GetPublicPageBySlug(ctx context.Context, slug sql.NullString) (Page, error) {
	row := q.db.QueryRowContext(ctx, getPublicPageBySlug, slug)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.ContentHtml,
		&i.ContentType,
		&i.RedirectUrl,
		&i.PageOrder,
		&i.Status,
		&i.Comment,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContentMarkdown,
	)
	return i, err
}

const getPublicTagBySlug = `-- name: GetPublicTagBySlug :one
SELECT id, name, slug, created_at, updated_at FROM tags WHERE slug = ?
`

func (q *Queries) GetPublicTagBySlug(ctx context.Context, slug string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getPublicTagBySlug, slug)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const latestPublishedArticleUpdate = `-- name: LatestPublishedArticleUpdate :one
SELECT MAX(updated_at) FROM articles WHERE status = 1
`

func (q *Queries) LatestPublishedArticleUpdate(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, latestPublishedArticleUpdate)
	var max interface{}
	err := row.Scan(&max)
	return max, err
}

const listNavbarPages = `-- name: ListNavbarPages :many
SELECT id, title, slug, redirect_url FROM pages WHERE status = 1 ORDER BY page_order DESC
`

type ListNavbarPagesRow struct {
	ID          int64
	Title       sql.NullString
	Slug        sql.NullString
	RedirectUrl sql.NullString
}

// CacheableSettings.navbar_items: published pages, page_order DESC.
func (q *Queries) ListNavbarPages(ctx context.Context) ([]ListNavbarPagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listNavbarPages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNavbarPagesRow
	for rows.Next() {
		var i ListNavbarPagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.RedirectUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicTags = `-- name: ListPublicTags :many
SELECT id, name, slug, created_at, updated_at FROM tags ORDER BY name
`

// Tag.alphabetical (order(:name)).
func (q *Queries) ListPublicTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listPublicTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedArticleSitemap = `-- name: ListPublishedArticleSitemap :many
SELECT slug, updated_at FROM articles WHERE status = 1 ORDER BY created_at DESC
`

type ListPublishedArticleSitemapRow struct {
	Slug      sql.NullString
	UpdatedAt int64
}

func (q *Queries) ListPublishedArticleSitemap(ctx context.Context) ([]ListPublishedArticleSitemapRow, error) {
	rows, err := q.db.QueryContext(ctx, listPublishedArticleSitemap)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishedArticleSitemapRow
	for rows.Next() {
		var i ListPublishedArticleSitemapRow
		if err := rows.Scan(&i.Slug, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedArticles = `-- name: ListPublishedArticles :many
SELECT id, title, slug, content_html, content_type, description, excerpt, meta_description, meta_title, meta_image, source_author, source_url, source_content, status, comment, scheduled_at, scheduled_crosspost_platforms, scheduled_send_newsletter, created_at, updated_at, content_markdown FROM articles
WHERE status = 1
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListPublishedArticlesParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListPublishedArticles(ctx context.Context, arg ListPublishedArticlesParams) ([]Article, error) {
	rows, err := q.db.QueryContext(ctx, listPublishedArticles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Article
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.ContentHtml,
			&i.ContentType,
			&i.Description,
			&i.Excerpt,
			&i.MetaDescription,
			&i.MetaTitle,
			&i.MetaImage,
			&i.SourceAuthor,
			&i.SourceUrl,
			&i.SourceContent,
			&i.Status,
			&i.Comment,
			&i.ScheduledAt,
			&i.ScheduledCrosspostPlatforms,
			&i.ScheduledSendNewsletter,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContentMarkdown,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedArticlesByTag = `-- name: ListPublishedArticlesByTag :many
SELECT articles.id, articles.title, articles.slug, articles.content_html, articles.content_type, articles.description, articles.excerpt, articles.meta_description, articles.meta_title, articles.meta_image, articles.source_author, articles.source_url, articles.source_content, articles.status, articles.comment, articles.scheduled_at, articles.scheduled_crosspost_platforms, articles.scheduled_send_newsletter, articles.created_at, articles.updated_at, articles.content_markdown FROM articles
JOIN article_tags ON article_tags.article_id = articles.id
WHERE articles.status = 1 AND article_tags.tag_id = ?
ORDER BY articles.created_at DESC
LIMIT ? OFFSET ?
`

type ListPublishedArticlesByTagParams struct {
	TagID  int64
	Limit  int64
	Offset int64
}

func (q *Queries) ListPublishedArticlesByTag(ctx context.Context, arg ListPublishedArticlesByTagParams) ([]Article, error) {
	rows, err := q.db.QueryContext(ctx, listPublishedArticlesByTag, arg.TagID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Article
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.ContentHtml,
			&i.ContentType,
			&i.Description,
			&i.Excerpt,
			&i.MetaDescription,
			&i.MetaTitle,
			&i.MetaImage,
			&i.SourceAuthor,
			&i.SourceUrl,
			&i.SourceContent,
			&i.Status,
			&i.Comment,
			&i.ScheduledAt,
			&i.ScheduledCrosspostPlatforms,
			&i.ScheduledSendNewsletter,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContentMarkdown,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedCountsByTag = `-- name: ListPublishedCountsByTag :many
SELECT article_tags.tag_id, COUNT(*) AS published_count
FROM article_tags
JOIN articles ON articles.id = article_tags.article_id
WHERE articles.status = 1
GROUP BY article_tags.tag_id
`

type ListPublishedCountsByTagRow struct {
	TagID          int64
	PublishedCount int64
}

// TagsController#index: published article counts grouped by tag_id.
func (q *Queries) ListPublishedCountsByTag(ctx context.Context) ([]ListPublishedCountsByTagRow, error) {
	rows, err := q.db.QueryContext(ctx, listPublishedCountsByTag)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishedCountsByTagRow
	for rows.Next() {
		var i ListPublishedCountsByTagRow
		if err := rows.Scan(&i.TagID, &i.PublishedCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedPageSitemap = `-- name: ListPublishedPageSitemap :many
SELECT slug, updated_at FROM pages WHERE status = 1 ORDER BY created_at DESC
`

type ListPublishedPageSitemapRow struct {
	Slug      sql.NullString
	UpdatedAt int64
}

func (q *Queries) ListPublishedPageSitemap(ctx context.Context) ([]ListPublishedPageSitemapRow, error) {
	rows, err := q.db.QueryContext(ctx, listPublishedPageSitemap)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishedPageSitemapRow
	for rows.Next() {
		var i ListPublishedPageSitemapRow
		if err := rows.Scan(&i.Slug, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsForArticle = `-- name: ListTagsForArticle :many
SELECT tags.id, tags.name, tags.slug, tags.created_at, tags.updated_at FROM tags
JOIN article_tags ON article_tags.tag_id = tags.id
WHERE article_tags.article_id = ?
ORDER BY tags.name
`

// Tags shown next to each article in the public list (Tag.alphabetical).
func (q *Queries) ListTagsForArticle(ctx context.Context, articleID int64) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTagsForArticle, articleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPublishedArticles = `-- name: SearchPublishedArticles :many
SELECT id, title, slug, content_html, content_type, description, excerpt, meta_description, meta_title, meta_image, source_author, source_url, source_content, status, comment, scheduled_at, scheduled_crosspost_platforms, scheduled_send_newsletter, created_at, updated_at, content_markdown FROM articles
WHERE status = 1 AND (
  (title LIKE ? ESCAPE '\') OR
  (slug LIKE ? ESCAPE '\') OR
  (description LIKE ? ESCAPE '\') OR
  (content_html LIKE ? ESCAPE '\')
)
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type SearchPublishedArticlesParams struct {
	Title       sql.NullString
	Slug        sql.NullString
	Description sql.NullString
	ContentHtml sql.NullString
	Limit       int64
	Offset      int64
}

// Mirrors Article.search_content + published scope. The caller escapes %, _
// and backslash in the term and wraps it in %...%; ESCAPE '\' makes the
// escaping effective.
func (q *Queries) SearchPublishedArticles(ctx context.Context, arg SearchPublishedArticlesParams) ([]Article, error) {
	rows, err := q.db.QueryContext(ctx, searchPublishedArticles,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.ContentHtml,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Article
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.ContentHtml,
			&i.ContentType,
			&i.Description,
			&i.Excerpt,
			&i.MetaDescription,
			&i.MetaTitle,
			&i.MetaImage,
			&i.SourceAuthor,
			&i.SourceUrl,
			&i.SourceContent,
			&i.Status,
			&i.Comment,
			&i.ScheduledAt,
			&i.ScheduledCrosspostPlatforms,
			&i.ScheduledSendNewsletter,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContentMarkdown,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
