// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: redirects.sql

package query

import (
	"context"
)

const createRedirect = `-- name: CreateRedirect :one
INSERT INTO redirects (regex, replacement, permanent, enabled, match_on, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, regex, replacement, enabled, permanent, created_at, updated_at, match_on
`

type CreateRedirectParams struct {
	Regex       string
	Replacement string
	Permanent   int64
	Enabled     int64
	MatchOn     string
	CreatedAt   int64
	UpdatedAt   int64
}

func (q *Queries) CreateRedirect(ctx context.Context, arg CreateRedirectParams) (Redirect, error) {
	row := q.db.QueryRowContext(ctx, createRedirect,
		arg.Regex,
		arg.Replacement,
		arg.Permanent,
		arg.Enabled,
		arg.MatchOn,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Redirect
	err := row.Scan(
		&i.ID,
		&i.Regex,
		&i.Replacement,
		&i.Enabled,
		&i.Permanent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MatchOn,
	)
	return i, err
}

const deleteRedirect = `-- name: DeleteRedirect :exec
DELETE FROM redirects WHERE id = ?
`

func (q *Queries) DeleteRedirect(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRedirect, id)
	return err
}

const getRedirectByID = `-- name: GetRedirectByID :one
SELECT id, regex, replacement, enabled, permanent, created_at, updated_at, match_on FROM redirects WHERE id = ?
`

func (q *Queries) GetRedirectByID(ctx context.Context, id int64) (Redirect, error) {
	row := q.db.QueryRowContext(ctx, getRedirectByID, id)
	var i Redirect
	err := row.Scan(
		&i.ID,
		&i.Regex,
		&i.Replacement,
		&i.Enabled,
		&i.Permanent,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MatchOn,
	)
	return i, err
}

const listEnabledRedirects = `-- name: ListEnabledRedirects :many
SELECT id, regex, replacement, enabled, permanent, created_at, updated_at, match_on FROM redirects WHERE enabled = 1 ORDER BY id
`

func (q *Queries) ListEnabledRedirects(ctx context.Context) ([]Redirect, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledRedirects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Redirect
	for rows.Next() {
		var i Redirect
		if err := rows.Scan(
			&i.ID,
			&i.Regex,
			&i.Replacement,
			&i.Enabled,
			&i.Permanent,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MatchOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRedirects = `-- name: ListRedirects :many
SELECT id, regex, replacement, enabled, permanent, created_at, updated_at, match_on FROM redirects ORDER BY created_at DESC
`

func (q *Queries) ListRedirects(ctx context.Context) ([]Redirect, error) {
	rows, err := q.db.QueryContext(ctx, listRedirects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Redirect
	for rows.Next() {
		var i Redirect
		if err := rows.Scan(
			&i.ID,
			&i.Regex,
			&i.Replacement,
			&i.Enabled,
			&i.Permanent,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MatchOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRedirect = `-- name: UpdateRedirect :exec
UPDATE redirects
SET regex = ?, replacement = ?, permanent = ?, enabled = ?, match_on = ?, updated_at = ?
WHERE id = ?
`

type UpdateRedirectParams struct {
	Regex       string
	Replacement string
	Permanent   int64
	Enabled     int64
	MatchOn     string
	UpdatedAt   int64
	ID          int64
}

func (q *Queries) UpdateRedirect(ctx context.Context, arg UpdateRedirectParams) error {
	_, err := q.db.ExecContext(ctx, updateRedirect,
		arg.Regex,
		arg.Replacement,
		arg.Permanent,
		arg.Enabled,
		arg.MatchOn,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
