// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package query

import (
	"context"
	"database/sql"
)

const updateSettings = `-- name: UpdateSettings :exec

UPDATE settings
SET title = ?, description = ?, author = ?, url = ?, time_zone = ?,
    head_code = ?, custom_css = ?, tool_code = ?, giscus = ?,
    social_links = ?, updated_at = ?
WHERE id = 1
`

type UpdateSettingsParams struct {
	Title       sql.NullString
	Description sql.NullString
	Author      sql.NullString
	Url         sql.NullString
	TimeZone    string
	HeadCode    sql.NullString
	CustomCss   sql.NullString
	ToolCode    sql.NullString
	Giscus      sql.NullString
	SocialLinks sql.NullString
	UpdatedAt   int64
}

// Singleton settings row (id = 1). GetSettings and EnsureSettings live in
// auth.sql; this file adds the admin update.
func (q *Queries) UpdateSettings(ctx context.Context, arg UpdateSettingsParams) error {
	_, err := q.db.ExecContext(ctx, updateSettings,
		arg.Title,
		arg.Description,
		arg.Author,
		arg.Url,
		arg.TimeZone,
		arg.HeadCode,
		arg.CustomCss,
		arg.ToolCode,
		arg.Giscus,
		arg.SocialLinks,
		arg.UpdatedAt,
	)
	return err
}
