// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: static_files.sql

package query

import (
	"context"
	"database/sql"
)

const createStaticFile = `-- name: CreateStaticFile :one
INSERT INTO static_files (filename, description, file_id, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, filename, description, file_id, created_at, updated_at
`

type CreateStaticFileParams struct {
	Filename    string
	Description sql.NullString
	FileID      int64
	CreatedAt   int64
	UpdatedAt   int64
}

func (q *Queries) CreateStaticFile(ctx context.Context, arg CreateStaticFileParams) (StaticFile, error) {
	row := q.db.QueryRowContext(ctx, createStaticFile,
		arg.Filename,
		arg.Description,
		arg.FileID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i StaticFile
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.Description,
		&i.FileID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFileByID = `-- name: DeleteFileByID :exec
DELETE FROM files WHERE id = ?
`

func (q *Queries) DeleteFileByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteFileByID, id)
	return err
}

const deleteStaticFile = `-- name: DeleteStaticFile :exec
DELETE FROM static_files WHERE id = ?
`

func (q *Queries) DeleteStaticFile(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteStaticFile, id)
	return err
}

const getFileForStaticFilename = `-- name: GetFileForStaticFilename :one
SELECT f.id, f."key", f.filename, f.content_type, f.byte_size, f.checksum, f.variant_of, f.created_at FROM static_files sf
JOIN files f ON f.id = sf.file_id
WHERE sf.filename = ?
`

func (q *Queries) GetFileForStaticFilename(ctx context.Context, filename string) (File, error) {
	row := q.db.QueryRowContext(ctx, getFileForStaticFilename, filename)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Filename,
		&i.ContentType,
		&i.ByteSize,
		&i.Checksum,
		&i.VariantOf,
		&i.CreatedAt,
	)
	return i, err
}

const getStaticFileByFilename = `-- name: GetStaticFileByFilename :one
SELECT id, filename, description, file_id, created_at, updated_at FROM static_files WHERE filename = ?
`

func (q *Queries) GetStaticFileByFilename(ctx context.Context, filename string) (StaticFile, error) {
	row := q.db.QueryRowContext(ctx, getStaticFileByFilename, filename)
	var i StaticFile
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.Description,
		&i.FileID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStaticFileByID = `-- name: GetStaticFileByID :one
SELECT id, filename, description, file_id, created_at, updated_at FROM static_files WHERE id = ?
`

func (q *Queries) GetStaticFileByID(ctx context.Context, id int64) (StaticFile, error) {
	row := q.db.QueryRowContext(ctx, getStaticFileByID, id)
	var i StaticFile
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.Description,
		&i.FileID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStaticFiles = `-- name: ListStaticFiles :many
SELECT sf.id, sf.filename, sf.description, sf.file_id, sf.created_at, sf.updated_at,
  f.key, f.byte_size, f.content_type
FROM static_files sf
JOIN files f ON f.id = sf.file_id
ORDER BY sf.created_at DESC
`

type ListStaticFilesRow struct {
	ID          int64
	Filename    string
	Description sql.NullString
	FileID      int64
	CreatedAt   int64
	UpdatedAt   int64
	Key         string
	ByteSize    int64
	ContentType sql.NullString
}

func (q *Queries) ListStaticFiles(ctx context.Context) ([]ListStaticFilesRow, error) {
	rows, err := q.db.QueryContext(ctx, listStaticFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStaticFilesRow
	for rows.Next() {
		var i ListStaticFilesRow
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.Description,
			&i.FileID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Key,
			&i.ByteSize,
			&i.ContentType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStaticFile = `-- name: UpdateStaticFile :exec
UPDATE static_files
SET description = ?, file_id = ?, updated_at = ?
WHERE id = ?
`

type UpdateStaticFileParams struct {
	Description sql.NullString
	FileID      int64
	UpdatedAt   int64
	ID          int64
}

func (q *Queries) UpdateStaticFile(ctx context.Context, arg UpdateStaticFileParams) error {
	_, err := q.db.ExecContext(ctx, updateStaticFile,
		arg.Description,
		arg.FileID,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
