// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscribers.sql

package query

import (
	"context"
	"database/sql"
)

const addSubscriberTag = `-- name: AddSubscriberTag :exec
INSERT INTO subscriber_tags (subscriber_id, tag_id, created_at, updated_at) VALUES (?, ?, ?, ?)
ON CONFLICT(subscriber_id, tag_id) DO NOTHING
`

type AddSubscriberTagParams struct {
	SubscriberID int64
	TagID        int64
	CreatedAt    int64
	UpdatedAt    int64
}

// subscriber.tags = tags replaces the set; ON CONFLICT absorbs duplicate
// tag ids inside one assignment.
func (q *Queries) AddSubscriberTag(ctx context.Context, arg AddSubscriberTagParams) error {
	_, err := q.db.ExecContext(ctx, addSubscriberTag,
		arg.SubscriberID,
		arg.TagID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const confirmSubscriber = `-- name: ConfirmSubscriber :exec
UPDATE subscribers SET confirmed_at = ?, updated_at = ? WHERE id = ?
`

type ConfirmSubscriberParams struct {
	ConfirmedAt sql.NullInt64
	UpdatedAt   int64
	ID          int64
}

// Subscriber#confirm!: update(confirmed_at:) unless confirmed? (the caller
// checks the current state first).
func (q *Queries) ConfirmSubscriber(ctx context.Context, arg ConfirmSubscriberParams) error {
	_, err := q.db.ExecContext(ctx, confirmSubscriber, arg.ConfirmedAt, arg.UpdatedAt, arg.ID)
	return err
}

const createSubscriber = `-- name: CreateSubscriber :one
INSERT INTO subscribers (email, confirmation_token, unsubscribe_token, created_at, updated_at)
VALUES (?, ?, ?, ?, ?) RETURNING id, email, confirmation_token, unsubscribe_token, confirmed_at, unsubscribed_at, created_at, updated_at
`

type CreateSubscriberParams struct {
	Email             string
	ConfirmationToken sql.NullString
	UnsubscribeToken  sql.NullString
	CreatedAt         int64
	UpdatedAt         int64
}

// Tokens are generated by the caller: Subscriber#generate_tokens only fills
// blanks (||=), so imports can keep pre-set tokens.
func (q *Queries) CreateSubscriber(ctx context.Context, arg CreateSubscriberParams) (Subscriber, error) {
	row := q.db.QueryRowContext(ctx, createSubscriber,
		arg.Email,
		arg.ConfirmationToken,
		arg.UnsubscribeToken,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.ConfirmationToken,
		&i.UnsubscribeToken,
		&i.ConfirmedAt,
		&i.UnsubscribedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSubscriber = `-- name: DeleteSubscriber :exec
DELETE FROM subscribers WHERE id = ?
`

func (q *Queries) DeleteSubscriber(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSubscriber, id)
	return err
}

const deleteSubscriberTagsBySubscriberID = `-- name: DeleteSubscriberTagsBySubscriberID :exec
DELETE FROM subscriber_tags WHERE subscriber_id = ?
`

// has_many :subscriber_tags, dependent: :destroy.
func (q *Queries) DeleteSubscriberTagsBySubscriberID(ctx context.Context, subscriberID int64) error {
	_, err := q.db.ExecContext(ctx, deleteSubscriberTagsBySubscriberID, subscriberID)
	return err
}

const getSubscriberByConfirmationToken = `-- name: GetSubscriberByConfirmationToken :one
SELECT id, email, confirmation_token, unsubscribe_token, confirmed_at, unsubscribed_at, created_at, updated_at FROM subscribers WHERE confirmation_token = ?
`

func (q *Queries) GetSubscriberByConfirmationToken(ctx context.Context, confirmationToken sql.NullString) (Subscriber, error) {
	row := q.db.QueryRowContext(ctx, getSubscriberByConfirmationToken, confirmationToken)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.ConfirmationToken,
		&i.UnsubscribeToken,
		&i.ConfirmedAt,
		&i.UnsubscribedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriberByEmail = `-- name: GetSubscriberByEmail :one
SELECT id, email, confirmation_token, unsubscribe_token, confirmed_at, unsubscribed_at, created_at, updated_at FROM subscribers WHERE email = ?
`

func (q *Queries) GetSubscriberByEmail(ctx context.Context, email string) (Subscriber, error) {
	row := q.db.QueryRowContext(ctx, getSubscriberByEmail, email)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.ConfirmationToken,
		&i.UnsubscribeToken,
		&i.ConfirmedAt,
		&i.UnsubscribedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriberByID = `-- name: GetSubscriberByID :one

SELECT id, email, confirmation_token, unsubscribe_token, confirmed_at, unsubscribed_at, created_at, updated_at FROM subscribers WHERE id = ?
`

// Subscriber queries (plan T16, section 4.6). Timestamps are unix seconds.
func (q *Queries) GetSubscriberByID(ctx context.Context, id int64) (Subscriber, error) {
	row := q.db.QueryRowContext(ctx, getSubscriberByID, id)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.ConfirmationToken,
		&i.UnsubscribeToken,
		&i.ConfirmedAt,
		&i.UnsubscribedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriberByUnsubscribeToken = `-- name: GetSubscriberByUnsubscribeToken :one
SELECT id, email, confirmation_token, unsubscribe_token, confirmed_at, unsubscribed_at, created_at, updated_at FROM subscribers WHERE unsubscribe_token = ?
`

func (q *Queries) GetSubscriberByUnsubscribeToken(ctx context.Context, unsubscribeToken sql.NullString) (Subscriber, error) {
	row := q.db.QueryRowContext(ctx, getSubscriberByUnsubscribeToken, unsubscribeToken)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.ConfirmationToken,
		&i.UnsubscribeToken,
		&i.ConfirmedAt,
		&i.UnsubscribedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAdminSubscribers = `-- name: ListAdminSubscribers :many
SELECT id, email, confirmation_token, unsubscribe_token, confirmed_at, unsubscribed_at, created_at, updated_at FROM subscribers
WHERE (?1 = '' OR
  (?1 = 'active' AND confirmed_at IS NOT NULL AND unsubscribed_at IS NULL) OR
  (?1 = 'unconfirmed' AND confirmed_at IS NULL) OR
  (?1 = 'unsubscribed' AND confirmed_at IS NOT NULL AND unsubscribed_at IS NOT NULL))
ORDER BY created_at DESC
`

// Admin index status filter (apply_status_filter); the tag filter and the
// 30-per-page window are applied by the caller over this ordered list.
func (q *Queries) ListAdminSubscribers(ctx context.Context, status interface{}) ([]Subscriber, error) {
	rows, err := q.db.QueryContext(ctx, listAdminSubscribers, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscriber
	for rows.Next() {
		var i Subscriber
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.ConfirmationToken,
			&i.UnsubscribeToken,
			&i.ConfirmedAt,
			&i.UnsubscribedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriberIDsByTagID = `-- name: ListSubscriberIDsByTagID :many
SELECT subscriber_id FROM subscriber_tags WHERE tag_id = ?
`

// Tag-filter candidates: subscribers carrying one given tag.
func (q *Queries) ListSubscriberIDsByTagID(ctx context.Context, tagID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listSubscriberIDsByTagID, tagID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var subscriber_id int64
		if err := rows.Scan(&subscriber_id); err != nil {
			return nil, err
		}
		items = append(items, subscriber_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriberIDsWithoutTags = `-- name: ListSubscriberIDsWithoutTags :many
SELECT id FROM subscribers WHERE NOT EXISTS (
  SELECT 1 FROM subscriber_tags WHERE subscriber_tags.subscriber_id = subscribers.id
)
`

// Subscribers with no tags (left_joins(:tags).where(tags: { id: nil })).
func (q *Queries) ListSubscriberIDsWithoutTags(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listSubscriberIDsWithoutTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsForSubscriber = `-- name: ListTagsForSubscriber :many
SELECT tags.id, tags.name, tags.slug, tags.created_at, tags.updated_at FROM tags
JOIN subscriber_tags ON subscriber_tags.tag_id = tags.id
WHERE subscriber_tags.subscriber_id = ?
ORDER BY subscriber_tags.id
`

// subscriber.tags in association (join-row insertion) order.
func (q *Queries) ListTagsForSubscriber(ctx context.Context, subscriberID int64) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTagsForSubscriber, subscriberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetSubscriberForResubscribe = `-- name: ResetSubscriberForResubscribe :exec
UPDATE subscribers SET confirmed_at = NULL, unsubscribed_at = NULL, confirmation_token = ?, updated_at = ?
WHERE id = ?
`

type ResetSubscriberForResubscribeParams struct {
	ConfirmationToken sql.NullString
	UpdatedAt         int64
	ID                int64
}

// Re-subscribe of an unsubscribed address (SubscriptionsController#create):
// confirmation state resets and a fresh confirmation token is issued.
func (q *Queries) ResetSubscriberForResubscribe(ctx context.Context, arg ResetSubscriberForResubscribeParams) error {
	_, err := q.db.ExecContext(ctx, resetSubscriberForResubscribe, arg.ConfirmationToken, arg.UpdatedAt, arg.ID)
	return err
}

const unsubscribeSubscriber = `-- name: UnsubscribeSubscriber :exec
UPDATE subscribers SET unsubscribed_at = ?, updated_at = ? WHERE id = ?
`

type UnsubscribeSubscriberParams struct {
	UnsubscribedAt sql.NullInt64
	UpdatedAt      int64
	ID             int64
}

// Subscriber#unsubscribe!: update(unsubscribed_at:) unless unsubscribed?.
func (q *Queries) UnsubscribeSubscriber(ctx context.Context, arg UnsubscribeSubscriberParams) error {
	_, err := q.db.ExecContext(ctx, unsubscribeSubscriber, arg.UnsubscribedAt, arg.UpdatedAt, arg.ID)
	return err
}
