// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package query

import (
	"context"
)

const countTagsBySlug = `-- name: CountTagsBySlug :one
SELECT COUNT(*) FROM tags WHERE slug = ? AND id != ?
`

type CountTagsBySlugParams struct {
	Slug string
	ID   int64
}

// Slug-uniqueness probe for Tag#generate_slug's "-1", "-2", ... suffix loop
// (excludeID plays the role of where.not(id: id || 0)).
func (q *Queries) CountTagsBySlug(ctx context.Context, arg CountTagsBySlugParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTagsBySlug, arg.Slug, arg.ID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (name, slug, created_at, updated_at) VALUES (?, ?, ?, ?) RETURNING id, name, slug, created_at, updated_at
`

type CreateTagParams struct {
	Name      string
	Slug      string
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, createTag,
		arg.Name,
		arg.Slug,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteArticleTagsByTagID = `-- name: DeleteArticleTagsByTagID :exec
DELETE FROM article_tags WHERE tag_id = ?
`

func (q *Queries) DeleteArticleTagsByTagID(ctx context.Context, tagID int64) error {
	_, err := q.db.ExecContext(ctx, deleteArticleTagsByTagID, tagID)
	return err
}

const deleteSubscriberTagsByTagID = `-- name: DeleteSubscriberTagsByTagID :exec
DELETE FROM subscriber_tags WHERE tag_id = ?
`

func (q *Queries) DeleteSubscriberTagsByTagID(ctx context.Context, tagID int64) error {
	_, err := q.db.ExecContext(ctx, deleteSubscriberTagsByTagID, tagID)
	return err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags WHERE id = ?
`

func (q *Queries) DeleteTag(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTag, id)
	return err
}

const getTagByID = `-- name: GetTagByID :one
SELECT id, name, slug, created_at, updated_at FROM tags WHERE id = ?
`

func (q *Queries) GetTagByID(ctx context.Context, id int64) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTagByID, id)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTagByLowerName = `-- name: GetTagByLowerName :one
SELECT id, name, slug, created_at, updated_at FROM tags WHERE LOWER(name) = LOWER(?)
`

// Case-insensitive lookup mirroring Tag.find_or_create_by_names'
// where("LOWER(name) = ?", name.downcase). SQLite LOWER folds ASCII only,
// exactly like the Rails app running on SQLite.
func (q *Queries) GetTagByLowerName(ctx context.Context, lower string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTagByLowerName, lower)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTagIfAbsent = `-- name: InsertTagIfAbsent :exec
INSERT INTO tags (name, slug, created_at, updated_at)
SELECT ?, ?, ?, ?
WHERE NOT EXISTS (SELECT 1 FROM tags WHERE LOWER(name) = LOWER(?5))
`

type InsertTagIfAbsentParams struct {
	Name      string
	Slug      string
	CreatedAt int64
	UpdatedAt int64
	LowerName string
}

// Race-safe insert for find-or-create: the name check and the insert are one
// atomic statement (SQLite serializes writers), so even case-variant names
// ("Go" vs "go", which the case-sensitive UNIQUE(name) would both admit)
// cannot duplicate; the row is re-read afterwards, mirroring the
// RecordNotUnique rescue. A slug conflict still errors so the caller loops.
func (q *Queries) InsertTagIfAbsent(ctx context.Context, arg InsertTagIfAbsentParams) error {
	_, err := q.db.ExecContext(ctx, insertTagIfAbsent,
		arg.Name,
		arg.Slug,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.LowerName,
	)
	return err
}

const listTagsWithArticleCount = `-- name: ListTagsWithArticleCount :many
SELECT tags.id, tags.name, tags.slug, tags.created_at, tags.updated_at, COUNT(articles.id) AS articles_total
FROM tags
LEFT JOIN article_tags ON article_tags.tag_id = tags.id
LEFT JOIN articles ON articles.id = article_tags.article_id
GROUP BY tags.id
ORDER BY tags.name
`

type ListTagsWithArticleCountRow struct {
	ID            int64
	Name          string
	Slug          string
	CreatedAt     int64
	UpdatedAt     int64
	ArticlesTotal int64
}

// Admin index: Tag.alphabetical.left_joins(:articles) with articles_total.
func (q *Queries) ListTagsWithArticleCount(ctx context.Context) ([]ListTagsWithArticleCountRow, error) {
	rows, err := q.db.QueryContext(ctx, listTagsWithArticleCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTagsWithArticleCountRow
	for rows.Next() {
		var i ListTagsWithArticleCountRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArticlesTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchArticlesByTagID = `-- name: TouchArticlesByTagID :exec
UPDATE articles SET updated_at = ? WHERE id IN (SELECT article_id FROM article_tags WHERE tag_id = ?)
`

type TouchArticlesByTagIDParams struct {
	UpdatedAt int64
	TagID     int64
}

// Tag#touch_articles: busts the render cache keyed on article id+updated_at.
func (q *Queries) TouchArticlesByTagID(ctx context.Context, arg TouchArticlesByTagIDParams) error {
	_, err := q.db.ExecContext(ctx, touchArticlesByTagID, arg.UpdatedAt, arg.TagID)
	return err
}

const updateTagName = `-- name: UpdateTagName :exec
UPDATE tags SET name = ?, updated_at = ? WHERE id = ?
`

type UpdateTagNameParams struct {
	Name      string
	UpdatedAt int64
	ID        int64
}

// Rename keeps the slug: Tag#generate_slug only fills blank slugs.
func (q *Queries) UpdateTagName(ctx context.Context, arg UpdateTagNameParams) error {
	_, err := q.db.ExecContext(ctx, updateTagName, arg.Name, arg.UpdatedAt, arg.ID)
	return err
}
