// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transfer_import.sql

package query

import (
	"context"
	"database/sql"
)

const importArticleIDBySlug = `-- name: ImportArticleIDBySlug :one

SELECT id FROM articles WHERE slug = ?
`

// Import queries used by the RSS importer (transfer/import_rss.go).
// Timestamps are unix seconds; booleans are 0/1.
// articles: skip when the slug already exists.
func (q *Queries) ImportArticleIDBySlug(ctx context.Context, slug sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, importArticleIDBySlug, slug)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const importInsertArticle = `-- name: ImportInsertArticle :one
INSERT INTO articles (title, slug, content_html, content_type, description, excerpt,
  meta_description, meta_title, meta_image, source_author, source_url, source_content,
  status, comment, scheduled_at, scheduled_crosspost_platforms, scheduled_send_newsletter,
  created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id
`

type ImportInsertArticleParams struct {
	Title                       sql.NullString
	Slug                        sql.NullString
	ContentHtml                 sql.NullString
	ContentType                 string
	Description                 sql.NullString
	Excerpt                     sql.NullString
	MetaDescription             sql.NullString
	MetaTitle                   sql.NullString
	MetaImage                   sql.NullString
	SourceAuthor                sql.NullString
	SourceUrl                   sql.NullString
	SourceContent               sql.NullString
	Status                      int64
	Comment                     int64
	ScheduledAt                 sql.NullInt64
	ScheduledCrosspostPlatforms string
	ScheduledSendNewsletter     int64
	CreatedAt                   int64
	UpdatedAt                   int64
}

func (q *Queries) ImportInsertArticle(ctx context.Context, arg ImportInsertArticleParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, importInsertArticle,
		arg.Title,
		arg.Slug,
		arg.ContentHtml,
		arg.ContentType,
		arg.Description,
		arg.Excerpt,
		arg.MetaDescription,
		arg.MetaTitle,
		arg.MetaImage,
		arg.SourceAuthor,
		arg.SourceUrl,
		arg.SourceContent,
		arg.Status,
		arg.Comment,
		arg.ScheduledAt,
		arg.ScheduledCrosspostPlatforms,
		arg.ScheduledSendNewsletter,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
