// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transfer_import.sql

package query

import (
	"context"
	"database/sql"
)

const importArticleIDBySlug = `-- name: ImportArticleIDBySlug :one
SELECT id FROM articles WHERE slug = ?
`

// articles: skip when the slug already exists.
func (q *Queries) ImportArticleIDBySlug(ctx context.Context, slug sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, importArticleIDBySlug, slug)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const importArticleTagID = `-- name: ImportArticleTagID :one
SELECT id FROM article_tags WHERE article_id = ? AND tag_id = ?
`

type ImportArticleTagIDParams struct {
	ArticleID int64
	TagID     int64
}

func (q *Queries) ImportArticleTagID(ctx context.Context, arg ImportArticleTagIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, importArticleTagID, arg.ArticleID, arg.TagID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const importAttachmentID = `-- name: ImportAttachmentID :one
SELECT id FROM attachments WHERE record_type = ? AND record_id = ? AND name = ? AND file_id = ?
`

type ImportAttachmentIDParams struct {
	RecordType string
	RecordID   int64
	Name       string
	FileID     int64
}

// attachments: skip when (record_type, record_id, name, file_id) already exists.
func (q *Queries) ImportAttachmentID(ctx context.Context, arg ImportAttachmentIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, importAttachmentID,
		arg.RecordType,
		arg.RecordID,
		arg.Name,
		arg.FileID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const importCrosspostByPlatform = `-- name: ImportCrosspostByPlatform :one
SELECT id, platform, enabled, api_key, api_key_secret, access_token, access_token_secret, client_id, client_key, client_secret, app_password, refresh_token, token_expires_at, server_url, username, max_characters, auto_fetch_comments, comment_fetch_schedule, settings, created_at, updated_at FROM crossposts WHERE platform = ?
`

// crossposts upsert by platform.
func (q *Queries) ImportCrosspostByPlatform(ctx context.Context, platform string) (Crosspost, error) {
	row := q.db.QueryRowContext(ctx, importCrosspostByPlatform, platform)
	var i Crosspost
	err := row.Scan(
		&i.ID,
		&i.Platform,
		&i.Enabled,
		&i.ApiKey,
		&i.ApiKeySecret,
		&i.AccessToken,
		&i.AccessTokenSecret,
		&i.ClientID,
		&i.ClientKey,
		&i.ClientSecret,
		&i.AppPassword,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.ServerUrl,
		&i.Username,
		&i.MaxCharacters,
		&i.AutoFetchComments,
		&i.CommentFetchSchedule,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const importExternalCommentID = `-- name: ImportExternalCommentID :one
SELECT id FROM comments WHERE article_id = ? AND platform = ? AND external_id = ?
`

type ImportExternalCommentIDParams struct {
	ArticleID  sql.NullInt64
	Platform   sql.NullString
	ExternalID sql.NullString
}

// comments: external duplicates match (article_id, platform, external_id);
// local duplicates match article + author + content within a +-5s window on
// published_at (preferred) or created_at (ImportZip#import_comments).
func (q *Queries) ImportExternalCommentID(ctx context.Context, arg ImportExternalCommentIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, importExternalCommentID, arg.ArticleID, arg.Platform, arg.ExternalID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const importFileByKey = `-- name: ImportFileByKey :one
SELECT id, "key", filename, content_type, byte_size, checksum, variant_of, created_at FROM files WHERE key = ?
`

// files: skip when the key already exists; the CSV key is kept verbatim.
func (q *Queries) ImportFileByKey(ctx context.Context, key string) (File, error) {
	row := q.db.QueryRowContext(ctx, importFileByKey, key)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Filename,
		&i.ContentType,
		&i.ByteSize,
		&i.Checksum,
		&i.VariantOf,
		&i.CreatedAt,
	)
	return i, err
}

const importInsertArticle = `-- name: ImportInsertArticle :one
INSERT INTO articles (title, slug, content_html, content_type, description, excerpt,
  meta_description, meta_title, meta_image, source_author, source_url, source_content,
  status, comment, scheduled_at, scheduled_crosspost_platforms, scheduled_send_newsletter,
  created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id
`

type ImportInsertArticleParams struct {
	Title                       sql.NullString
	Slug                        sql.NullString
	ContentHtml                 sql.NullString
	ContentType                 string
	Description                 sql.NullString
	Excerpt                     sql.NullString
	MetaDescription             sql.NullString
	MetaTitle                   sql.NullString
	MetaImage                   sql.NullString
	SourceAuthor                sql.NullString
	SourceUrl                   sql.NullString
	SourceContent               sql.NullString
	Status                      int64
	Comment                     int64
	ScheduledAt                 sql.NullInt64
	ScheduledCrosspostPlatforms string
	ScheduledSendNewsletter     int64
	CreatedAt                   int64
	UpdatedAt                   int64
}

func (q *Queries) ImportInsertArticle(ctx context.Context, arg ImportInsertArticleParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, importInsertArticle,
		arg.Title,
		arg.Slug,
		arg.ContentHtml,
		arg.ContentType,
		arg.Description,
		arg.Excerpt,
		arg.MetaDescription,
		arg.MetaTitle,
		arg.MetaImage,
		arg.SourceAuthor,
		arg.SourceUrl,
		arg.SourceContent,
		arg.Status,
		arg.Comment,
		arg.ScheduledAt,
		arg.ScheduledCrosspostPlatforms,
		arg.ScheduledSendNewsletter,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const importInsertArticleTag = `-- name: ImportInsertArticleTag :exec
INSERT INTO article_tags (article_id, tag_id, created_at, updated_at)
VALUES (?, ?, ?, ?)
`

type ImportInsertArticleTagParams struct {
	ArticleID int64
	TagID     int64
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) ImportInsertArticleTag(ctx context.Context, arg ImportInsertArticleTagParams) error {
	_, err := q.db.ExecContext(ctx, importInsertArticleTag,
		arg.ArticleID,
		arg.TagID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const importInsertAttachment = `-- name: ImportInsertAttachment :exec
INSERT INTO attachments (file_id, record_type, record_id, name, created_at)
VALUES (?, ?, ?, ?, ?)
`

type ImportInsertAttachmentParams struct {
	FileID     int64
	RecordType string
	RecordID   int64
	Name       string
	CreatedAt  int64
}

func (q *Queries) ImportInsertAttachment(ctx context.Context, arg ImportInsertAttachmentParams) error {
	_, err := q.db.ExecContext(ctx, importInsertAttachment,
		arg.FileID,
		arg.RecordType,
		arg.RecordID,
		arg.Name,
		arg.CreatedAt,
	)
	return err
}

const importInsertComment = `-- name: ImportInsertComment :one
INSERT INTO comments (commentable_type, commentable_id, article_id, parent_id,
  author_name, author_email, author_url, author_username, author_avatar_url,
  content, status, platform, external_id, url, published_at, created_at, updated_at)
VALUES (?, ?, ?, NULL, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id
`

type ImportInsertCommentParams struct {
	CommentableType sql.NullString
	CommentableID   sql.NullInt64
	ArticleID       sql.NullInt64
	AuthorName      string
	AuthorEmail     sql.NullString
	AuthorUrl       sql.NullString
	AuthorUsername  sql.NullString
	AuthorAvatarUrl sql.NullString
	Content         string
	Status          int64
	Platform        sql.NullString
	ExternalID      sql.NullString
	Url             sql.NullString
	PublishedAt     sql.NullInt64
	CreatedAt       int64
	UpdatedAt       int64
}

// First pass inserts with parent_id NULL; the second pass backfills it.
func (q *Queries) ImportInsertComment(ctx context.Context, arg ImportInsertCommentParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, importInsertComment,
		arg.CommentableType,
		arg.CommentableID,
		arg.ArticleID,
		arg.AuthorName,
		arg.AuthorEmail,
		arg.AuthorUrl,
		arg.AuthorUsername,
		arg.AuthorAvatarUrl,
		arg.Content,
		arg.Status,
		arg.Platform,
		arg.ExternalID,
		arg.Url,
		arg.PublishedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const importInsertCrosspost = `-- name: ImportInsertCrosspost :exec
INSERT INTO crossposts (platform, enabled, api_key, api_key_secret, access_token,
  access_token_secret, client_id, client_key, client_secret, app_password,
  refresh_token, token_expires_at, server_url, username, max_characters,
  auto_fetch_comments, comment_fetch_schedule, settings, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type ImportInsertCrosspostParams struct {
	Platform             string
	Enabled              int64
	ApiKey               sql.NullString
	ApiKeySecret         sql.NullString
	AccessToken          sql.NullString
	AccessTokenSecret    sql.NullString
	ClientID             sql.NullString
	ClientKey            sql.NullString
	ClientSecret         sql.NullString
	AppPassword          sql.NullString
	RefreshToken         sql.NullString
	TokenExpiresAt       sql.NullInt64
	ServerUrl            sql.NullString
	Username             sql.NullString
	MaxCharacters        sql.NullInt64
	AutoFetchComments    int64
	CommentFetchSchedule sql.NullString
	Settings             sql.NullString
	CreatedAt            int64
	UpdatedAt            int64
}

func (q *Queries) ImportInsertCrosspost(ctx context.Context, arg ImportInsertCrosspostParams) error {
	_, err := q.db.ExecContext(ctx, importInsertCrosspost,
		arg.Platform,
		arg.Enabled,
		arg.ApiKey,
		arg.ApiKeySecret,
		arg.AccessToken,
		arg.AccessTokenSecret,
		arg.ClientID,
		arg.ClientKey,
		arg.ClientSecret,
		arg.AppPassword,
		arg.RefreshToken,
		arg.TokenExpiresAt,
		arg.ServerUrl,
		arg.Username,
		arg.MaxCharacters,
		arg.AutoFetchComments,
		arg.CommentFetchSchedule,
		arg.Settings,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const importInsertFile = `-- name: ImportInsertFile :one
INSERT INTO files (key, filename, content_type, byte_size, checksum, variant_of, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?) RETURNING id
`

type ImportInsertFileParams struct {
	Key         string
	Filename    string
	ContentType sql.NullString
	ByteSize    int64
	Checksum    sql.NullString
	VariantOf   sql.NullInt64
	CreatedAt   int64
}

func (q *Queries) ImportInsertFile(ctx context.Context, arg ImportInsertFileParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, importInsertFile,
		arg.Key,
		arg.Filename,
		arg.ContentType,
		arg.ByteSize,
		arg.Checksum,
		arg.VariantOf,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const importInsertListmonk = `-- name: ImportInsertListmonk :exec
INSERT INTO listmonks (id, url, username, api_key, list_id, template_id, enabled,
  created_at, updated_at)
VALUES (1, ?, ?, ?, ?, ?, ?, ?, ?)
`

type ImportInsertListmonkParams struct {
	Url        sql.NullString
	Username   sql.NullString
	ApiKey     sql.NullString
	ListID     sql.NullInt64
	TemplateID sql.NullInt64
	Enabled    int64
	CreatedAt  int64
	UpdatedAt  int64
}

func (q *Queries) ImportInsertListmonk(ctx context.Context, arg ImportInsertListmonkParams) error {
	_, err := q.db.ExecContext(ctx, importInsertListmonk,
		arg.Url,
		arg.Username,
		arg.ApiKey,
		arg.ListID,
		arg.TemplateID,
		arg.Enabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const importInsertNewsletterSetting = `-- name: ImportInsertNewsletterSetting :exec
INSERT INTO newsletter_settings (id, enabled, provider, from_email, smtp_address,
  smtp_port, smtp_user_name, smtp_password, smtp_domain, smtp_authentication,
  smtp_enable_starttls, created_at, updated_at)
VALUES (1, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type ImportInsertNewsletterSettingParams struct {
	Enabled            int64
	Provider           string
	FromEmail          sql.NullString
	SmtpAddress        sql.NullString
	SmtpPort           sql.NullInt64
	SmtpUserName       sql.NullString
	SmtpPassword       sql.NullString
	SmtpDomain         sql.NullString
	SmtpAuthentication sql.NullString
	SmtpEnableStarttls sql.NullInt64
	CreatedAt          int64
	UpdatedAt          int64
}

func (q *Queries) ImportInsertNewsletterSetting(ctx context.Context, arg ImportInsertNewsletterSettingParams) error {
	_, err := q.db.ExecContext(ctx, importInsertNewsletterSetting,
		arg.Enabled,
		arg.Provider,
		arg.FromEmail,
		arg.SmtpAddress,
		arg.SmtpPort,
		arg.SmtpUserName,
		arg.SmtpPassword,
		arg.SmtpDomain,
		arg.SmtpAuthentication,
		arg.SmtpEnableStarttls,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const importInsertPage = `-- name: ImportInsertPage :one
INSERT INTO pages (title, slug, content_html, content_type, redirect_url, page_order,
  status, comment, scheduled_at, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id
`

type ImportInsertPageParams struct {
	Title       sql.NullString
	Slug        sql.NullString
	ContentHtml sql.NullString
	ContentType string
	RedirectUrl sql.NullString
	PageOrder   int64
	Status      int64
	Comment     int64
	ScheduledAt sql.NullInt64
	CreatedAt   int64
	UpdatedAt   int64
}

func (q *Queries) ImportInsertPage(ctx context.Context, arg ImportInsertPageParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, importInsertPage,
		arg.Title,
		arg.Slug,
		arg.ContentHtml,
		arg.ContentType,
		arg.RedirectUrl,
		arg.PageOrder,
		arg.Status,
		arg.Comment,
		arg.ScheduledAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const importInsertRedirect = `-- name: ImportInsertRedirect :exec
INSERT INTO redirects (regex, replacement, enabled, permanent, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type ImportInsertRedirectParams struct {
	Regex       string
	Replacement string
	Enabled     int64
	Permanent   int64
	CreatedAt   int64
	UpdatedAt   int64
}

func (q *Queries) ImportInsertRedirect(ctx context.Context, arg ImportInsertRedirectParams) error {
	_, err := q.db.ExecContext(ctx, importInsertRedirect,
		arg.Regex,
		arg.Replacement,
		arg.Enabled,
		arg.Permanent,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const importInsertSettings = `-- name: ImportInsertSettings :exec
INSERT INTO settings (id, title, description, author, url, time_zone, head_code,
  custom_css, tool_code, giscus, social_links, setup_completed, created_at, updated_at)
VALUES (1, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type ImportInsertSettingsParams struct {
	Title          sql.NullString
	Description    sql.NullString
	Author         sql.NullString
	Url            sql.NullString
	TimeZone       string
	HeadCode       sql.NullString
	CustomCss      sql.NullString
	ToolCode       sql.NullString
	Giscus         sql.NullString
	SocialLinks    sql.NullString
	SetupCompleted int64
	CreatedAt      int64
	UpdatedAt      int64
}

func (q *Queries) ImportInsertSettings(ctx context.Context, arg ImportInsertSettingsParams) error {
	_, err := q.db.ExecContext(ctx, importInsertSettings,
		arg.Title,
		arg.Description,
		arg.Author,
		arg.Url,
		arg.TimeZone,
		arg.HeadCode,
		arg.CustomCss,
		arg.ToolCode,
		arg.Giscus,
		arg.SocialLinks,
		arg.SetupCompleted,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const importInsertSocialMediaPost = `-- name: ImportInsertSocialMediaPost :exec
INSERT INTO social_media_posts (article_id, platform, url, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
`

type ImportInsertSocialMediaPostParams struct {
	ArticleID int64
	Platform  string
	Url       string
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) ImportInsertSocialMediaPost(ctx context.Context, arg ImportInsertSocialMediaPostParams) error {
	_, err := q.db.ExecContext(ctx, importInsertSocialMediaPost,
		arg.ArticleID,
		arg.Platform,
		arg.Url,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const importInsertStaticFile = `-- name: ImportInsertStaticFile :one
INSERT INTO static_files (filename, description, file_id, created_at, updated_at)
VALUES (?, ?, ?, ?, ?) RETURNING id
`

type ImportInsertStaticFileParams struct {
	Filename    string
	Description sql.NullString
	FileID      int64
	CreatedAt   int64
	UpdatedAt   int64
}

func (q *Queries) ImportInsertStaticFile(ctx context.Context, arg ImportInsertStaticFileParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, importInsertStaticFile,
		arg.Filename,
		arg.Description,
		arg.FileID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const importInsertSubscriber = `-- name: ImportInsertSubscriber :one
INSERT INTO subscribers (email, confirmation_token, unsubscribe_token,
  confirmed_at, unsubscribed_at, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?) RETURNING id
`

type ImportInsertSubscriberParams struct {
	Email             string
	ConfirmationToken sql.NullString
	UnsubscribeToken  sql.NullString
	ConfirmedAt       sql.NullInt64
	UnsubscribedAt    sql.NullInt64
	CreatedAt         int64
	UpdatedAt         int64
}

func (q *Queries) ImportInsertSubscriber(ctx context.Context, arg ImportInsertSubscriberParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, importInsertSubscriber,
		arg.Email,
		arg.ConfirmationToken,
		arg.UnsubscribeToken,
		arg.ConfirmedAt,
		arg.UnsubscribedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const importInsertSubscriberTag = `-- name: ImportInsertSubscriberTag :exec
INSERT INTO subscriber_tags (subscriber_id, tag_id, created_at, updated_at)
VALUES (?, ?, ?, ?)
`

type ImportInsertSubscriberTagParams struct {
	SubscriberID int64
	TagID        int64
	CreatedAt    int64
	UpdatedAt    int64
}

func (q *Queries) ImportInsertSubscriberTag(ctx context.Context, arg ImportInsertSubscriberTagParams) error {
	_, err := q.db.ExecContext(ctx, importInsertSubscriberTag,
		arg.SubscriberID,
		arg.TagID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const importInsertTag = `-- name: ImportInsertTag :one
INSERT INTO tags (name, slug, created_at, updated_at)
VALUES (?, ?, ?, ?) RETURNING id
`

type ImportInsertTagParams struct {
	Name      string
	Slug      string
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) ImportInsertTag(ctx context.Context, arg ImportInsertTagParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, importInsertTag,
		arg.Name,
		arg.Slug,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const importListmonk = `-- name: ImportListmonk :one
SELECT id, url, username, api_key, list_id, template_id, enabled, created_at, updated_at FROM listmonks WHERE id = 1
`

// listmonks is a singleton (id = 1).
func (q *Queries) ImportListmonk(ctx context.Context) (Listmonk, error) {
	row := q.db.QueryRowContext(ctx, importListmonk)
	var i Listmonk
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Username,
		&i.ApiKey,
		&i.ListID,
		&i.TemplateID,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const importLocalCommentIDByCreatedAt = `-- name: ImportLocalCommentIDByCreatedAt :one
SELECT id FROM comments
WHERE article_id = ?1 AND platform IS NULL
  AND author_name = ?2 AND content = ?3
  AND created_at >= ?4 AND created_at <= ?5
LIMIT 1
`

type ImportLocalCommentIDByCreatedAtParams struct {
	ArticleID  sql.NullInt64
	AuthorName string
	Content    string
	FromTs     int64
	ToTs       int64
}

func (q *Queries) ImportLocalCommentIDByCreatedAt(ctx context.Context, arg ImportLocalCommentIDByCreatedAtParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, importLocalCommentIDByCreatedAt,
		arg.ArticleID,
		arg.AuthorName,
		arg.Content,
		arg.FromTs,
		arg.ToTs,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const importLocalCommentIDByPublishedAt = `-- name: ImportLocalCommentIDByPublishedAt :one
SELECT id FROM comments
WHERE article_id = ?1 AND platform IS NULL
  AND author_name = ?2 AND content = ?3
  AND published_at >= ?4 AND published_at <= ?5
LIMIT 1
`

type ImportLocalCommentIDByPublishedAtParams struct {
	ArticleID  sql.NullInt64
	AuthorName string
	Content    string
	FromTs     sql.NullInt64
	ToTs       sql.NullInt64
}

func (q *Queries) ImportLocalCommentIDByPublishedAt(ctx context.Context, arg ImportLocalCommentIDByPublishedAtParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, importLocalCommentIDByPublishedAt,
		arg.ArticleID,
		arg.AuthorName,
		arg.Content,
		arg.FromTs,
		arg.ToTs,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const importNewsletterSetting = `-- name: ImportNewsletterSetting :one
SELECT id, enabled, provider, from_email, smtp_address, smtp_port, smtp_user_name, smtp_password, smtp_domain, smtp_authentication, smtp_enable_starttls, created_at, updated_at FROM newsletter_settings WHERE id = 1
`

// newsletter_settings is a singleton (id = 1).
func (q *Queries) ImportNewsletterSetting(ctx context.Context) (NewsletterSetting, error) {
	row := q.db.QueryRowContext(ctx, importNewsletterSetting)
	var i NewsletterSetting
	err := row.Scan(
		&i.ID,
		&i.Enabled,
		&i.Provider,
		&i.FromEmail,
		&i.SmtpAddress,
		&i.SmtpPort,
		&i.SmtpUserName,
		&i.SmtpPassword,
		&i.SmtpDomain,
		&i.SmtpAuthentication,
		&i.SmtpEnableStarttls,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const importPageIDBySlug = `-- name: ImportPageIDBySlug :one
SELECT id FROM pages WHERE slug = ?
`

// pages: skip when the slug already exists.
func (q *Queries) ImportPageIDBySlug(ctx context.Context, slug sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, importPageIDBySlug, slug)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const importRedirectIDByRegex = `-- name: ImportRedirectIDByRegex :one
SELECT id FROM redirects WHERE regex = ?
`

// redirects: skip when the regex already exists.
func (q *Queries) ImportRedirectIDByRegex(ctx context.Context, regex string) (int64, error) {
	row := q.db.QueryRowContext(ctx, importRedirectIDByRegex, regex)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const importSetCommentParent = `-- name: ImportSetCommentParent :exec
UPDATE comments SET parent_id = ?, updated_at = ? WHERE id = ? AND parent_id IS NULL
`

type ImportSetCommentParentParams struct {
	ParentID  sql.NullInt64
	UpdatedAt int64
	ID        int64
}

func (q *Queries) ImportSetCommentParent(ctx context.Context, arg ImportSetCommentParentParams) error {
	_, err := q.db.ExecContext(ctx, importSetCommentParent, arg.ParentID, arg.UpdatedAt, arg.ID)
	return err
}

const importSettingsID = `-- name: ImportSettingsID :one
SELECT id FROM settings WHERE id = 1
`

// settings is a singleton (id = 1): update the existing row, else insert.
func (q *Queries) ImportSettingsID(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, importSettingsID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const importSocialMediaPostID = `-- name: ImportSocialMediaPostID :one
SELECT id FROM social_media_posts WHERE article_id = ? AND platform = ?
`

type ImportSocialMediaPostIDParams struct {
	ArticleID int64
	Platform  string
}

// social_media_posts: skip when (article_id, platform) already exists.
func (q *Queries) ImportSocialMediaPostID(ctx context.Context, arg ImportSocialMediaPostIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, importSocialMediaPostID, arg.ArticleID, arg.Platform)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const importStaticFileIDByFilename = `-- name: ImportStaticFileIDByFilename :one
SELECT id FROM static_files WHERE filename = ?
`

// static_files: skip when the filename already exists.
func (q *Queries) ImportStaticFileIDByFilename(ctx context.Context, filename string) (int64, error) {
	row := q.db.QueryRowContext(ctx, importStaticFileIDByFilename, filename)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const importSubscriberIDByEmail = `-- name: ImportSubscriberIDByEmail :one
SELECT id FROM subscribers WHERE email = ?
`

// subscribers: skip when the email already exists.
func (q *Queries) ImportSubscriberIDByEmail(ctx context.Context, email string) (int64, error) {
	row := q.db.QueryRowContext(ctx, importSubscriberIDByEmail, email)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const importSubscriberTagID = `-- name: ImportSubscriberTagID :one
SELECT id FROM subscriber_tags WHERE subscriber_id = ? AND tag_id = ?
`

type ImportSubscriberTagIDParams struct {
	SubscriberID int64
	TagID        int64
}

func (q *Queries) ImportSubscriberTagID(ctx context.Context, arg ImportSubscriberTagIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, importSubscriberTagID, arg.SubscriberID, arg.TagID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const importTagIDBySlug = `-- name: ImportTagIDBySlug :one

SELECT id FROM tags WHERE slug = ?
`

// Import queries (plan T26, section 4.11). All run inside the single import
// transaction. Timestamps are unix seconds; booleans are 0/1.
// tags: skip when the slug already exists.
func (q *Queries) ImportTagIDBySlug(ctx context.Context, slug string) (int64, error) {
	row := q.db.QueryRowContext(ctx, importTagIDBySlug, slug)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const importUpdateCrosspost = `-- name: ImportUpdateCrosspost :exec
UPDATE crossposts SET enabled = ?, api_key = ?, api_key_secret = ?, access_token = ?,
  access_token_secret = ?, client_id = ?, client_key = ?, client_secret = ?,
  app_password = ?, refresh_token = ?, token_expires_at = ?, server_url = ?,
  username = ?, max_characters = ?, auto_fetch_comments = ?, comment_fetch_schedule = ?,
  settings = ?, created_at = ?, updated_at = ?
WHERE platform = ?
`

type ImportUpdateCrosspostParams struct {
	Enabled              int64
	ApiKey               sql.NullString
	ApiKeySecret         sql.NullString
	AccessToken          sql.NullString
	AccessTokenSecret    sql.NullString
	ClientID             sql.NullString
	ClientKey            sql.NullString
	ClientSecret         sql.NullString
	AppPassword          sql.NullString
	RefreshToken         sql.NullString
	TokenExpiresAt       sql.NullInt64
	ServerUrl            sql.NullString
	Username             sql.NullString
	MaxCharacters        sql.NullInt64
	AutoFetchComments    int64
	CommentFetchSchedule sql.NullString
	Settings             sql.NullString
	CreatedAt            int64
	UpdatedAt            int64
	Platform             string
}

func (q *Queries) ImportUpdateCrosspost(ctx context.Context, arg ImportUpdateCrosspostParams) error {
	_, err := q.db.ExecContext(ctx, importUpdateCrosspost,
		arg.Enabled,
		arg.ApiKey,
		arg.ApiKeySecret,
		arg.AccessToken,
		arg.AccessTokenSecret,
		arg.ClientID,
		arg.ClientKey,
		arg.ClientSecret,
		arg.AppPassword,
		arg.RefreshToken,
		arg.TokenExpiresAt,
		arg.ServerUrl,
		arg.Username,
		arg.MaxCharacters,
		arg.AutoFetchComments,
		arg.CommentFetchSchedule,
		arg.Settings,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Platform,
	)
	return err
}

const importUpdateListmonk = `-- name: ImportUpdateListmonk :exec
UPDATE listmonks SET url = ?, username = ?, api_key = ?, list_id = ?, template_id = ?,
  enabled = ?, created_at = ?, updated_at = ?
WHERE id = 1
`

type ImportUpdateListmonkParams struct {
	Url        sql.NullString
	Username   sql.NullString
	ApiKey     sql.NullString
	ListID     sql.NullInt64
	TemplateID sql.NullInt64
	Enabled    int64
	CreatedAt  int64
	UpdatedAt  int64
}

func (q *Queries) ImportUpdateListmonk(ctx context.Context, arg ImportUpdateListmonkParams) error {
	_, err := q.db.ExecContext(ctx, importUpdateListmonk,
		arg.Url,
		arg.Username,
		arg.ApiKey,
		arg.ListID,
		arg.TemplateID,
		arg.Enabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const importUpdateNewsletterSetting = `-- name: ImportUpdateNewsletterSetting :exec
UPDATE newsletter_settings SET enabled = ?, provider = ?, from_email = ?,
  smtp_address = ?, smtp_port = ?, smtp_user_name = ?, smtp_password = ?,
  smtp_domain = ?, smtp_authentication = ?, smtp_enable_starttls = ?,
  created_at = ?, updated_at = ?
WHERE id = 1
`

type ImportUpdateNewsletterSettingParams struct {
	Enabled            int64
	Provider           string
	FromEmail          sql.NullString
	SmtpAddress        sql.NullString
	SmtpPort           sql.NullInt64
	SmtpUserName       sql.NullString
	SmtpPassword       sql.NullString
	SmtpDomain         sql.NullString
	SmtpAuthentication sql.NullString
	SmtpEnableStarttls sql.NullInt64
	CreatedAt          int64
	UpdatedAt          int64
}

func (q *Queries) ImportUpdateNewsletterSetting(ctx context.Context, arg ImportUpdateNewsletterSettingParams) error {
	_, err := q.db.ExecContext(ctx, importUpdateNewsletterSetting,
		arg.Enabled,
		arg.Provider,
		arg.FromEmail,
		arg.SmtpAddress,
		arg.SmtpPort,
		arg.SmtpUserName,
		arg.SmtpPassword,
		arg.SmtpDomain,
		arg.SmtpAuthentication,
		arg.SmtpEnableStarttls,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const importUpdateSettings = `-- name: ImportUpdateSettings :exec
UPDATE settings SET title = ?, description = ?, author = ?, url = ?, time_zone = ?,
  head_code = ?, custom_css = ?, tool_code = ?, giscus = ?, social_links = ?,
  setup_completed = ?, created_at = ?, updated_at = ?
WHERE id = 1
`

type ImportUpdateSettingsParams struct {
	Title          sql.NullString
	Description    sql.NullString
	Author         sql.NullString
	Url            sql.NullString
	TimeZone       string
	HeadCode       sql.NullString
	CustomCss      sql.NullString
	ToolCode       sql.NullString
	Giscus         sql.NullString
	SocialLinks    sql.NullString
	SetupCompleted int64
	CreatedAt      int64
	UpdatedAt      int64
}

func (q *Queries) ImportUpdateSettings(ctx context.Context, arg ImportUpdateSettingsParams) error {
	_, err := q.db.ExecContext(ctx, importUpdateSettings,
		arg.Title,
		arg.Description,
		arg.Author,
		arg.Url,
		arg.TimeZone,
		arg.HeadCode,
		arg.CustomCss,
		arg.ToolCode,
		arg.Giscus,
		arg.SocialLinks,
		arg.SetupCompleted,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
