// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transfer.sql

package query

import (
	"context"
	"database/sql"
)

const exportArticleTags = `-- name: ExportArticleTags :many
SELECT article_tags.id, article_tags.article_id, article_tags.tag_id, article_tags.created_at, article_tags.updated_at, articles.slug AS article_slug, tags.name AS tag_name, tags.slug AS tag_slug
FROM article_tags
LEFT JOIN articles ON articles.id = article_tags.article_id
LEFT JOIN tags ON tags.id = article_tags.tag_id
ORDER BY article_tags.id
`

type ExportArticleTagsRow struct {
	ID          int64
	ArticleID   int64
	TagID       int64
	CreatedAt   int64
	UpdatedAt   int64
	ArticleSlug sql.NullString
	TagName     sql.NullString
	TagSlug     sql.NullString
}

func (q *Queries) ExportArticleTags(ctx context.Context) ([]ExportArticleTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, exportArticleTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportArticleTagsRow
	for rows.Next() {
		var i ExportArticleTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.ArticleID,
			&i.TagID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArticleSlug,
			&i.TagName,
			&i.TagSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportArticles = `-- name: ExportArticles :many
SELECT id, title, slug, content_html, content_type, description, excerpt, meta_description, meta_title, meta_image, source_author, source_url, source_content, status, comment, scheduled_at, scheduled_crosspost_platforms, scheduled_send_newsletter, created_at, updated_at FROM articles ORDER BY id
`

func (q *Queries) ExportArticles(ctx context.Context) ([]Article, error) {
	rows, err := q.db.QueryContext(ctx, exportArticles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Article
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.ContentHtml,
			&i.ContentType,
			&i.Description,
			&i.Excerpt,
			&i.MetaDescription,
			&i.MetaTitle,
			&i.MetaImage,
			&i.SourceAuthor,
			&i.SourceUrl,
			&i.SourceContent,
			&i.Status,
			&i.Comment,
			&i.ScheduledAt,
			&i.ScheduledCrosspostPlatforms,
			&i.ScheduledSendNewsletter,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportAttachments = `-- name: ExportAttachments :many
SELECT id, file_id, record_type, record_id, name, created_at FROM attachments ORDER BY id
`

func (q *Queries) ExportAttachments(ctx context.Context) ([]Attachment, error) {
	rows, err := q.db.QueryContext(ctx, exportAttachments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attachment
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.RecordType,
			&i.RecordID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportComments = `-- name: ExportComments :many
SELECT comments.id, comments.commentable_type, comments.commentable_id, comments.article_id, comments.parent_id, comments.author_name, comments.author_email, comments.author_url, comments.author_username, comments.author_avatar_url, comments.content, comments.status, comments.platform, comments.external_id, comments.url, comments.published_at, comments.created_at, comments.updated_at, articles.slug AS article_slug
FROM comments
LEFT JOIN articles ON articles.id = comments.article_id
ORDER BY comments.id
`

type ExportCommentsRow struct {
	ID              int64
	CommentableType sql.NullString
	CommentableID   sql.NullInt64
	ArticleID       sql.NullInt64
	ParentID        sql.NullInt64
	AuthorName      string
	AuthorEmail     sql.NullString
	AuthorUrl       sql.NullString
	AuthorUsername  sql.NullString
	AuthorAvatarUrl sql.NullString
	Content         string
	Status          int64
	Platform        sql.NullString
	ExternalID      sql.NullString
	Url             sql.NullString
	PublishedAt     sql.NullInt64
	CreatedAt       int64
	UpdatedAt       int64
	ArticleSlug     sql.NullString
}

func (q *Queries) ExportComments(ctx context.Context) ([]ExportCommentsRow, error) {
	rows, err := q.db.QueryContext(ctx, exportComments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportCommentsRow
	for rows.Next() {
		var i ExportCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.CommentableType,
			&i.CommentableID,
			&i.ArticleID,
			&i.ParentID,
			&i.AuthorName,
			&i.AuthorEmail,
			&i.AuthorUrl,
			&i.AuthorUsername,
			&i.AuthorAvatarUrl,
			&i.Content,
			&i.Status,
			&i.Platform,
			&i.ExternalID,
			&i.Url,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArticleSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportCrossposts = `-- name: ExportCrossposts :many
SELECT id, platform, enabled, api_key, api_key_secret, access_token, access_token_secret, client_id, client_key, client_secret, app_password, refresh_token, token_expires_at, server_url, username, max_characters, auto_fetch_comments, comment_fetch_schedule, settings, created_at, updated_at FROM crossposts ORDER BY id
`

func (q *Queries) ExportCrossposts(ctx context.Context) ([]Crosspost, error) {
	rows, err := q.db.QueryContext(ctx, exportCrossposts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Crosspost
	for rows.Next() {
		var i Crosspost
		if err := rows.Scan(
			&i.ID,
			&i.Platform,
			&i.Enabled,
			&i.ApiKey,
			&i.ApiKeySecret,
			&i.AccessToken,
			&i.AccessTokenSecret,
			&i.ClientID,
			&i.ClientKey,
			&i.ClientSecret,
			&i.AppPassword,
			&i.RefreshToken,
			&i.TokenExpiresAt,
			&i.ServerUrl,
			&i.Username,
			&i.MaxCharacters,
			&i.AutoFetchComments,
			&i.CommentFetchSchedule,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportFiles = `-- name: ExportFiles :many
SELECT id, "key", filename, content_type, byte_size, checksum, variant_of, created_at FROM files ORDER BY id
`

func (q *Queries) ExportFiles(ctx context.Context) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, exportFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Filename,
			&i.ContentType,
			&i.ByteSize,
			&i.Checksum,
			&i.VariantOf,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportListmonks = `-- name: ExportListmonks :many
SELECT id, url, username, api_key, list_id, template_id, enabled, created_at, updated_at FROM listmonks ORDER BY id
`

func (q *Queries) ExportListmonks(ctx context.Context) ([]Listmonk, error) {
	rows, err := q.db.QueryContext(ctx, exportListmonks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Listmonk
	for rows.Next() {
		var i Listmonk
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Username,
			&i.ApiKey,
			&i.ListID,
			&i.TemplateID,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportNewsletterSettings = `-- name: ExportNewsletterSettings :many
SELECT id, enabled, provider, from_email, smtp_address, smtp_port, smtp_user_name, smtp_password, smtp_domain, smtp_authentication, smtp_enable_starttls, created_at, updated_at FROM newsletter_settings ORDER BY id
`

func (q *Queries) ExportNewsletterSettings(ctx context.Context) ([]NewsletterSetting, error) {
	rows, err := q.db.QueryContext(ctx, exportNewsletterSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NewsletterSetting
	for rows.Next() {
		var i NewsletterSetting
		if err := rows.Scan(
			&i.ID,
			&i.Enabled,
			&i.Provider,
			&i.FromEmail,
			&i.SmtpAddress,
			&i.SmtpPort,
			&i.SmtpUserName,
			&i.SmtpPassword,
			&i.SmtpDomain,
			&i.SmtpAuthentication,
			&i.SmtpEnableStarttls,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportPages = `-- name: ExportPages :many
SELECT id, title, slug, content_html, content_type, redirect_url, page_order, status, comment, scheduled_at, created_at, updated_at FROM pages ORDER BY id
`

func (q *Queries) ExportPages(ctx context.Context) ([]Page, error) {
	rows, err := q.db.QueryContext(ctx, exportPages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Page
	for rows.Next() {
		var i Page
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.ContentHtml,
			&i.ContentType,
			&i.RedirectUrl,
			&i.PageOrder,
			&i.Status,
			&i.Comment,
			&i.ScheduledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportRedirects = `-- name: ExportRedirects :many
SELECT id, regex, replacement, enabled, permanent, created_at, updated_at FROM redirects ORDER BY id
`

func (q *Queries) ExportRedirects(ctx context.Context) ([]Redirect, error) {
	rows, err := q.db.QueryContext(ctx, exportRedirects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Redirect
	for rows.Next() {
		var i Redirect
		if err := rows.Scan(
			&i.ID,
			&i.Regex,
			&i.Replacement,
			&i.Enabled,
			&i.Permanent,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportSettings = `-- name: ExportSettings :many
SELECT id, title, description, author, url, time_zone, head_code, custom_css, tool_code, giscus, social_links, setup_completed, created_at, updated_at FROM settings ORDER BY id
`

func (q *Queries) ExportSettings(ctx context.Context) ([]Setting, error) {
	rows, err := q.db.QueryContext(ctx, exportSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Setting
	for rows.Next() {
		var i Setting
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Author,
			&i.Url,
			&i.TimeZone,
			&i.HeadCode,
			&i.CustomCss,
			&i.ToolCode,
			&i.Giscus,
			&i.SocialLinks,
			&i.SetupCompleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportSocialMediaPosts = `-- name: ExportSocialMediaPosts :many
SELECT social_media_posts.id, social_media_posts.article_id, social_media_posts.platform, social_media_posts.url, social_media_posts.created_at, social_media_posts.updated_at, articles.slug AS article_slug
FROM social_media_posts
LEFT JOIN articles ON articles.id = social_media_posts.article_id
ORDER BY social_media_posts.id
`

type ExportSocialMediaPostsRow struct {
	ID          int64
	ArticleID   int64
	Platform    string
	Url         string
	CreatedAt   int64
	UpdatedAt   int64
	ArticleSlug sql.NullString
}

func (q *Queries) ExportSocialMediaPosts(ctx context.Context) ([]ExportSocialMediaPostsRow, error) {
	rows, err := q.db.QueryContext(ctx, exportSocialMediaPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportSocialMediaPostsRow
	for rows.Next() {
		var i ExportSocialMediaPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.ArticleID,
			&i.Platform,
			&i.Url,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArticleSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportStaticFiles = `-- name: ExportStaticFiles :many
SELECT static_files.id, static_files.filename, static_files.description, static_files.file_id, static_files.created_at, static_files.updated_at, files.filename AS blob_filename
FROM static_files
LEFT JOIN files ON files.id = static_files.file_id
ORDER BY static_files.id
`

type ExportStaticFilesRow struct {
	ID           int64
	Filename     string
	Description  sql.NullString
	FileID       int64
	CreatedAt    int64
	UpdatedAt    int64
	BlobFilename sql.NullString
}

func (q *Queries) ExportStaticFiles(ctx context.Context) ([]ExportStaticFilesRow, error) {
	rows, err := q.db.QueryContext(ctx, exportStaticFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportStaticFilesRow
	for rows.Next() {
		var i ExportStaticFilesRow
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.Description,
			&i.FileID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BlobFilename,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportSubscriberTags = `-- name: ExportSubscriberTags :many
SELECT subscriber_tags.id, subscriber_tags.subscriber_id, subscriber_tags.tag_id, subscriber_tags.created_at, subscriber_tags.updated_at, subscribers.email AS subscriber_email, tags.name AS tag_name, tags.slug AS tag_slug
FROM subscriber_tags
LEFT JOIN subscribers ON subscribers.id = subscriber_tags.subscriber_id
LEFT JOIN tags ON tags.id = subscriber_tags.tag_id
ORDER BY subscriber_tags.id
`

type ExportSubscriberTagsRow struct {
	ID              int64
	SubscriberID    int64
	TagID           int64
	CreatedAt       int64
	UpdatedAt       int64
	SubscriberEmail sql.NullString
	TagName         sql.NullString
	TagSlug         sql.NullString
}

func (q *Queries) ExportSubscriberTags(ctx context.Context) ([]ExportSubscriberTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, exportSubscriberTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportSubscriberTagsRow
	for rows.Next() {
		var i ExportSubscriberTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.SubscriberID,
			&i.TagID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SubscriberEmail,
			&i.TagName,
			&i.TagSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportSubscribers = `-- name: ExportSubscribers :many
SELECT id, email, confirmation_token, unsubscribe_token, confirmed_at, unsubscribed_at, created_at, updated_at FROM subscribers ORDER BY id
`

func (q *Queries) ExportSubscribers(ctx context.Context) ([]Subscriber, error) {
	rows, err := q.db.QueryContext(ctx, exportSubscribers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscriber
	for rows.Next() {
		var i Subscriber
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.ConfirmationToken,
			&i.UnsubscribeToken,
			&i.ConfirmedAt,
			&i.UnsubscribedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportTags = `-- name: ExportTags :many
SELECT id, name, slug, created_at, updated_at FROM tags ORDER BY id
`

func (q *Queries) ExportTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, exportTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
