// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: twitter_archive.sql

package query

import (
	"context"
	"database/sql"
)

const clearTwitterArchiveImportSource = `-- name: ClearTwitterArchiveImportSource :exec
UPDATE twitter_archive_imports SET source_path = NULL, updated_at = ? WHERE id = ?
`

type ClearTwitterArchiveImportSourceParams struct {
	UpdatedAt int64
	ID        int64
}

func (q *Queries) ClearTwitterArchiveImportSource(ctx context.Context, arg ClearTwitterArchiveImportSourceParams) error {
	_, err := q.db.ExecContext(ctx, clearTwitterArchiveImportSource, arg.UpdatedAt, arg.ID)
	return err
}

const completeTwitterArchiveImport = `-- name: CompleteTwitterArchiveImport :exec
UPDATE twitter_archive_imports
SET status = 'completed', progress = 100, status_message = 'Import completed',
    tweets_count = ?, followers_count = ?, following_count = ?, likes_count = ?, total_items_count = ?,
    finished_at = ?, error_message = NULL, active_slot = NULL, updated_at = ?
WHERE id = ?
`

type CompleteTwitterArchiveImportParams struct {
	TweetsCount     int64
	FollowersCount  int64
	FollowingCount  int64
	LikesCount      int64
	TotalItemsCount int64
	FinishedAt      sql.NullInt64
	UpdatedAt       int64
	ID              int64
}

func (q *Queries) CompleteTwitterArchiveImport(ctx context.Context, arg CompleteTwitterArchiveImportParams) error {
	_, err := q.db.ExecContext(ctx, completeTwitterArchiveImport,
		arg.TweetsCount,
		arg.FollowersCount,
		arg.FollowingCount,
		arg.LikesCount,
		arg.TotalItemsCount,
		arg.FinishedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const countAttachmentsForFile = `-- name: CountAttachmentsForFile :one
SELECT COUNT(*) FROM attachments WHERE file_id = ?
`

func (q *Queries) CountAttachmentsForFile(ctx context.Context, fileID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAttachmentsForFile, fileID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTwitterArchiveConnectionsByType = `-- name: CountTwitterArchiveConnectionsByType :many
SELECT relationship_type, COUNT(*) AS n FROM twitter_archive_connections GROUP BY relationship_type
`

type CountTwitterArchiveConnectionsByTypeRow struct {
	RelationshipType string
	N                int64
}

func (q *Queries) CountTwitterArchiveConnectionsByType(ctx context.Context) ([]CountTwitterArchiveConnectionsByTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, countTwitterArchiveConnectionsByType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountTwitterArchiveConnectionsByTypeRow
	for rows.Next() {
		var i CountTwitterArchiveConnectionsByTypeRow
		if err := rows.Scan(&i.RelationshipType, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countTwitterArchiveLikes = `-- name: CountTwitterArchiveLikes :one
SELECT COUNT(*) FROM twitter_archive_likes
`

func (q *Queries) CountTwitterArchiveLikes(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTwitterArchiveLikes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTwitterArchiveTweetsByType = `-- name: CountTwitterArchiveTweetsByType :many
SELECT entry_type, COUNT(*) AS n FROM twitter_archive_tweets GROUP BY entry_type
`

type CountTwitterArchiveTweetsByTypeRow struct {
	EntryType string
	N         int64
}

// Admin index summary.
func (q *Queries) CountTwitterArchiveTweetsByType(ctx context.Context) ([]CountTwitterArchiveTweetsByTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, countTwitterArchiveTweetsByType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountTwitterArchiveTweetsByTypeRow
	for rows.Next() {
		var i CountTwitterArchiveTweetsByTypeRow
		if err := rows.Scan(&i.EntryType, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countTwitterArchiveTweetsOfType = `-- name: CountTwitterArchiveTweetsOfType :one
SELECT COUNT(*) FROM twitter_archive_tweets WHERE entry_type = ?
`

func (q *Queries) CountTwitterArchiveTweetsOfType(ctx context.Context, entryType string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTwitterArchiveTweetsOfType, entryType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTwitterArchiveImport = `-- name: CreateTwitterArchiveImport :one
INSERT INTO twitter_archive_imports (status, progress, source_filename, source_path, status_message, queued_at, active_slot, created_at, updated_at)
VALUES ('queued', 0, ?, ?, 'Queued', ?, 1, ?, ?)
RETURNING id, status, progress, total_items_count, tweets_count, followers_count, following_count, likes_count, source_filename, source_path, status_message, error_message, queued_at, started_at, finished_at, active_slot, created_at, updated_at
`

type CreateTwitterArchiveImportParams struct {
	SourceFilename string
	SourcePath     sql.NullString
	QueuedAt       int64
	CreatedAt      int64
	UpdatedAt      int64
}

// Import history rows (twitter_archive_imports). active_slot is 1 while the
// row is queued/running and NULL afterwards, so the partial unique index
// guarantees a single active import.
func (q *Queries) CreateTwitterArchiveImport(ctx context.Context, arg CreateTwitterArchiveImportParams) (TwitterArchiveImport, error) {
	row := q.db.QueryRowContext(ctx, createTwitterArchiveImport,
		arg.SourceFilename,
		arg.SourcePath,
		arg.QueuedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i TwitterArchiveImport
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Progress,
		&i.TotalItemsCount,
		&i.TweetsCount,
		&i.FollowersCount,
		&i.FollowingCount,
		&i.LikesCount,
		&i.SourceFilename,
		&i.SourcePath,
		&i.StatusMessage,
		&i.ErrorMessage,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ActiveSlot,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAllTwitterArchiveConnections = `-- name: DeleteAllTwitterArchiveConnections :exec
DELETE FROM twitter_archive_connections
`

func (q *Queries) DeleteAllTwitterArchiveConnections(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllTwitterArchiveConnections)
	return err
}

const deleteAllTwitterArchiveLikes = `-- name: DeleteAllTwitterArchiveLikes :exec
DELETE FROM twitter_archive_likes
`

func (q *Queries) DeleteAllTwitterArchiveLikes(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllTwitterArchiveLikes)
	return err
}

const deleteAllTwitterArchiveTweets = `-- name: DeleteAllTwitterArchiveTweets :exec

DELETE FROM twitter_archive_tweets
`

// Twitter archive (plan section 4.10): full-replace import tables, import
// history rows and the public archive pages.
func (q *Queries) DeleteAllTwitterArchiveTweets(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllTwitterArchiveTweets)
	return err
}

const deleteFile = `-- name: DeleteFile :exec
DELETE FROM files WHERE id = ?
`

func (q *Queries) DeleteFile(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteFile, id)
	return err
}

const deleteTwitterArchiveTweetAttachments = `-- name: DeleteTwitterArchiveTweetAttachments :exec
DELETE FROM attachments WHERE record_type = 'TwitterArchiveTweet'
`

func (q *Queries) DeleteTwitterArchiveTweetAttachments(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteTwitterArchiveTweetAttachments)
	return err
}

const failTwitterArchiveImport = `-- name: FailTwitterArchiveImport :exec
UPDATE twitter_archive_imports
SET status = 'failed', status_message = 'Import failed', error_message = ?,
    finished_at = ?, active_slot = NULL, updated_at = ?
WHERE id = ?
`

type FailTwitterArchiveImportParams struct {
	ErrorMessage sql.NullString
	FinishedAt   sql.NullInt64
	UpdatedAt    int64
	ID           int64
}

func (q *Queries) FailTwitterArchiveImport(ctx context.Context, arg FailTwitterArchiveImportParams) error {
	_, err := q.db.ExecContext(ctx, failTwitterArchiveImport,
		arg.ErrorMessage,
		arg.FinishedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const getTwitterArchiveImport = `-- name: GetTwitterArchiveImport :one
SELECT id, status, progress, total_items_count, tweets_count, followers_count, following_count, likes_count, source_filename, source_path, status_message, error_message, queued_at, started_at, finished_at, active_slot, created_at, updated_at FROM twitter_archive_imports WHERE id = ?
`

func (q *Queries) GetTwitterArchiveImport(ctx context.Context, id int64) (TwitterArchiveImport, error) {
	row := q.db.QueryRowContext(ctx, getTwitterArchiveImport, id)
	var i TwitterArchiveImport
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Progress,
		&i.TotalItemsCount,
		&i.TweetsCount,
		&i.FollowersCount,
		&i.FollowingCount,
		&i.LikesCount,
		&i.SourceFilename,
		&i.SourcePath,
		&i.StatusMessage,
		&i.ErrorMessage,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ActiveSlot,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasActiveTwitterArchiveImport = `-- name: HasActiveTwitterArchiveImport :one
SELECT COUNT(*) FROM twitter_archive_imports WHERE status IN ('queued', 'running')
`

func (q *Queries) HasActiveTwitterArchiveImport(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasActiveTwitterArchiveImport)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertTwitterArchiveConnection = `-- name: InsertTwitterArchiveConnection :exec
INSERT OR IGNORE INTO twitter_archive_connections (account_id, screen_name, user_link, relationship_type, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertTwitterArchiveConnectionParams struct {
	AccountID        string
	ScreenName       sql.NullString
	UserLink         sql.NullString
	RelationshipType string
	CreatedAt        int64
	UpdatedAt        int64
}

// OR IGNORE mirrors the in-memory seen_connections/seen_likes dedup of the
// Rails importer: the first occurrence of a key wins.
func (q *Queries) InsertTwitterArchiveConnection(ctx context.Context, arg InsertTwitterArchiveConnectionParams) error {
	_, err := q.db.ExecContext(ctx, insertTwitterArchiveConnection,
		arg.AccountID,
		arg.ScreenName,
		arg.UserLink,
		arg.RelationshipType,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertTwitterArchiveLike = `-- name: InsertTwitterArchiveLike :exec
INSERT OR IGNORE INTO twitter_archive_likes (tweet_id, full_text, expanded_url, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
`

type InsertTwitterArchiveLikeParams struct {
	TweetID     string
	FullText    sql.NullString
	ExpandedUrl sql.NullString
	CreatedAt   int64
	UpdatedAt   int64
}

func (q *Queries) InsertTwitterArchiveLike(ctx context.Context, arg InsertTwitterArchiveLikeParams) error {
	_, err := q.db.ExecContext(ctx, insertTwitterArchiveLike,
		arg.TweetID,
		arg.FullText,
		arg.ExpandedUrl,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listTwitterArchiveImportsRecent = `-- name: ListTwitterArchiveImportsRecent :many
SELECT id, status, progress, total_items_count, tweets_count, followers_count, following_count, likes_count, source_filename, source_path, status_message, error_message, queued_at, started_at, finished_at, active_slot, created_at, updated_at FROM twitter_archive_imports ORDER BY created_at DESC, id DESC LIMIT ?
`

func (q *Queries) ListTwitterArchiveImportsRecent(ctx context.Context, limit int64) ([]TwitterArchiveImport, error) {
	rows, err := q.db.QueryContext(ctx, listTwitterArchiveImportsRecent, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TwitterArchiveImport
	for rows.Next() {
		var i TwitterArchiveImport
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Progress,
			&i.TotalItemsCount,
			&i.TweetsCount,
			&i.FollowersCount,
			&i.FollowingCount,
			&i.LikesCount,
			&i.SourceFilename,
			&i.SourcePath,
			&i.StatusMessage,
			&i.ErrorMessage,
			&i.QueuedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.ActiveSlot,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTwitterArchiveLikes = `-- name: ListTwitterArchiveLikes :many
SELECT id, tweet_id, full_text, expanded_url, created_at, updated_at FROM twitter_archive_likes
ORDER BY created_at DESC, tweet_id DESC
LIMIT ? OFFSET ?
`

type ListTwitterArchiveLikesParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListTwitterArchiveLikes(ctx context.Context, arg ListTwitterArchiveLikesParams) ([]TwitterArchiveLike, error) {
	rows, err := q.db.QueryContext(ctx, listTwitterArchiveLikes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TwitterArchiveLike
	for rows.Next() {
		var i TwitterArchiveLike
		if err := rows.Scan(
			&i.ID,
			&i.TweetID,
			&i.FullText,
			&i.ExpandedUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTwitterArchiveTweetMedia = `-- name: ListTwitterArchiveTweetMedia :many
SELECT f.key, f.filename, f.content_type FROM attachments a
JOIN files f ON f.id = a.file_id
WHERE a.record_type = 'TwitterArchiveTweet' AND a.name = 'media' AND a.record_id = ?
ORDER BY a.id
`

type ListTwitterArchiveTweetMediaRow struct {
	Key         string
	Filename    string
	ContentType sql.NullString
}

func (q *Queries) ListTwitterArchiveTweetMedia(ctx context.Context, recordID int64) ([]ListTwitterArchiveTweetMediaRow, error) {
	rows, err := q.db.QueryContext(ctx, listTwitterArchiveTweetMedia, recordID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTwitterArchiveTweetMediaRow
	for rows.Next() {
		var i ListTwitterArchiveTweetMediaRow
		if err := rows.Scan(&i.Key, &i.Filename, &i.ContentType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTwitterArchiveTweetMediaFiles = `-- name: ListTwitterArchiveTweetMediaFiles :many
SELECT f.id, f.key FROM attachments a
JOIN files f ON f.id = a.file_id
WHERE a.record_type = 'TwitterArchiveTweet'
`

type ListTwitterArchiveTweetMediaFilesRow struct {
	ID  int64
	Key string
}

// Media cleanup for the full replace (mirrors has_many_attached
// dependent: :purge_later on TwitterArchiveTweet#media).
func (q *Queries) ListTwitterArchiveTweetMediaFiles(ctx context.Context) ([]ListTwitterArchiveTweetMediaFilesRow, error) {
	rows, err := q.db.QueryContext(ctx, listTwitterArchiveTweetMediaFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTwitterArchiveTweetMediaFilesRow
	for rows.Next() {
		var i ListTwitterArchiveTweetMediaFilesRow
		if err := rows.Scan(&i.ID, &i.Key); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTwitterArchiveTweetsByType = `-- name: ListTwitterArchiveTweetsByType :many
SELECT id, tweet_id, screen_name, full_text, entry_type, tweeted_at, created_at, updated_at FROM twitter_archive_tweets
WHERE entry_type = ?
ORDER BY tweeted_at DESC, tweet_id DESC
LIMIT ? OFFSET ?
`

type ListTwitterArchiveTweetsByTypeParams struct {
	EntryType string
	Limit     int64
	Offset    int64
}

// Public archive pages (20 per tab page).
func (q *Queries) ListTwitterArchiveTweetsByType(ctx context.Context, arg ListTwitterArchiveTweetsByTypeParams) ([]TwitterArchiveTweet, error) {
	rows, err := q.db.QueryContext(ctx, listTwitterArchiveTweetsByType, arg.EntryType, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TwitterArchiveTweet
	for rows.Next() {
		var i TwitterArchiveTweet
		if err := rows.Scan(
			&i.ID,
			&i.TweetID,
			&i.ScreenName,
			&i.FullText,
			&i.EntryType,
			&i.TweetedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTwitterArchiveImportRunning = `-- name: MarkTwitterArchiveImportRunning :exec
UPDATE twitter_archive_imports
SET status = 'running', progress = 5, status_message = 'Reading archive',
    started_at = ?, finished_at = NULL, error_message = NULL, updated_at = ?
WHERE id = ?
`

type MarkTwitterArchiveImportRunningParams struct {
	StartedAt sql.NullInt64
	UpdatedAt int64
	ID        int64
}

func (q *Queries) MarkTwitterArchiveImportRunning(ctx context.Context, arg MarkTwitterArchiveImportRunningParams) error {
	_, err := q.db.ExecContext(ctx, markTwitterArchiveImportRunning, arg.StartedAt, arg.UpdatedAt, arg.ID)
	return err
}

const twitterArchiveLastImportedAt = `-- name: TwitterArchiveLastImportedAt :one
SELECT COALESCE(
  (SELECT MAX(finished_at) FROM twitter_archive_imports WHERE status = 'completed'),
  (SELECT MAX(created_at) FROM twitter_archive_tweets)
) AS last_imported_at
`

// TwitterArchiveImport.last_imported_at: latest completed import finish,
// falling back to the newest archived tweet.
func (q *Queries) TwitterArchiveLastImportedAt(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, twitterArchiveLastImportedAt)
	var last_imported_at interface{}
	err := row.Scan(&last_imported_at)
	return last_imported_at, err
}

const updateTwitterArchiveImportProgress = `-- name: UpdateTwitterArchiveImportProgress :exec
UPDATE twitter_archive_imports
SET progress = ?, status_message = ?, updated_at = ?
WHERE id = ?
`

type UpdateTwitterArchiveImportProgressParams struct {
	Progress      int64
	StatusMessage sql.NullString
	UpdatedAt     int64
	ID            int64
}

func (q *Queries) UpdateTwitterArchiveImportProgress(ctx context.Context, arg UpdateTwitterArchiveImportProgressParams) error {
	_, err := q.db.ExecContext(ctx, updateTwitterArchiveImportProgress,
		arg.Progress,
		arg.StatusMessage,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const upsertTwitterArchiveTweet = `-- name: UpsertTwitterArchiveTweet :one
INSERT INTO twitter_archive_tweets (tweet_id, screen_name, full_text, entry_type, tweeted_at, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(tweet_id) DO UPDATE SET
  entry_type = CASE
    WHEN (CASE excluded.entry_type WHEN 'retweet_quote' THEN 2 WHEN 'reply' THEN 1 ELSE 0 END)
       > (CASE twitter_archive_tweets.entry_type WHEN 'retweet_quote' THEN 2 WHEN 'reply' THEN 1 ELSE 0 END)
    THEN excluded.entry_type ELSE twitter_archive_tweets.entry_type END,
  screen_name = CASE
    WHEN twitter_archive_tweets.screen_name != '' AND twitter_archive_tweets.screen_name != 'archive' THEN twitter_archive_tweets.screen_name
    WHEN excluded.screen_name != '' AND excluded.screen_name != 'archive' THEN excluded.screen_name
    WHEN twitter_archive_tweets.screen_name != '' THEN twitter_archive_tweets.screen_name
    WHEN excluded.screen_name != '' THEN excluded.screen_name
    ELSE 'archive' END,
  full_text = CASE
    WHEN length(excluded.full_text) > length(twitter_archive_tweets.full_text) THEN excluded.full_text
    ELSE twitter_archive_tweets.full_text END
RETURNING id
`

type UpsertTwitterArchiveTweetParams struct {
	TweetID    string
	ScreenName string
	FullText   string
	EntryType  string
	TweetedAt  int64
	CreatedAt  int64
	UpdatedAt  int64
}

// Upsert carries the duplicate-row merge semantics of
// TwitterArchiveImporter#merge_tweet_rows: the higher-ranked entry type wins
// (retweet_quote > reply > tweet), the non-"archive" screen name wins, the
// longer text wins, and the first tweeted_at sticks.
func (q *Queries) UpsertTwitterArchiveTweet(ctx context.Context, arg UpsertTwitterArchiveTweetParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertTwitterArchiveTweet,
		arg.TweetID,
		arg.ScreenName,
		arg.FullText,
		arg.EntryType,
		arg.TweetedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
