// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: twitter_sync.sql

package query

import (
	"context"
	"database/sql"
)

const ensureTwitterSync = `-- name: EnsureTwitterSync :exec

INSERT OR IGNORE INTO twitter_syncs (id, created_at, updated_at) VALUES (1, ?, ?)
`

type EnsureTwitterSyncParams struct {
	CreatedAt int64
	UpdatedAt int64
}

// Twitter sync (plan section 4.9): singleton config (twitter_syncs, id = 1)
// plus the cursor writes the syncer performs. GetTwitterSync lives in
// jobs.sql.
// TwitterSync.instance (first_or_create).
func (q *Queries) EnsureTwitterSync(ctx context.Context, arg EnsureTwitterSyncParams) error {
	_, err := q.db.ExecContext(ctx, ensureTwitterSync, arg.CreatedAt, arg.UpdatedAt)
	return err
}

const setTwitterSyncFailure = `-- name: SetTwitterSyncFailure :exec
UPDATE twitter_syncs SET last_error = ?, updated_at = ? WHERE id = 1
`

type SetTwitterSyncFailureParams struct {
	LastError sql.NullString
	UpdatedAt int64
}

// Failed run: only last_error changes (update_columns(last_error:) semantics).
func (q *Queries) SetTwitterSyncFailure(ctx context.Context, arg SetTwitterSyncFailureParams) error {
	_, err := q.db.ExecContext(ctx, setTwitterSyncFailure, arg.LastError, arg.UpdatedAt)
	return err
}

const setTwitterSyncSuccess = `-- name: SetTwitterSyncSuccess :exec
UPDATE twitter_syncs SET since_id = ?, last_synced_at = ?, last_error = NULL, updated_at = ?
WHERE id = 1
`

type SetTwitterSyncSuccessParams struct {
	SinceID      sql.NullString
	LastSyncedAt sql.NullInt64
	UpdatedAt    int64
}

// Successful run: advance the cursor, stamp last_synced_at, clear last_error.
func (q *Queries) SetTwitterSyncSuccess(ctx context.Context, arg SetTwitterSyncSuccessParams) error {
	_, err := q.db.ExecContext(ctx, setTwitterSyncSuccess, arg.SinceID, arg.LastSyncedAt, arg.UpdatedAt)
	return err
}

const setTwitterSyncUserID = `-- name: SetTwitterSyncUserID :exec
UPDATE twitter_syncs SET user_id = ?, updated_at = ? WHERE id = 1
`

type SetTwitterSyncUserIDParams struct {
	UserID    sql.NullString
	UpdatedAt int64
}

// resolve_user_id: persist the users/by/username lookup.
func (q *Queries) SetTwitterSyncUserID(ctx context.Context, arg SetTwitterSyncUserIDParams) error {
	_, err := q.db.ExecContext(ctx, setTwitterSyncUserID, arg.UserID, arg.UpdatedAt)
	return err
}

const updateTwitterSyncConfig = `-- name: UpdateTwitterSyncConfig :exec
UPDATE twitter_syncs SET
  enabled = ?, username = ?, user_id = ?, start_date = ?, sync_schedule = ?,
  since_id = ?, last_synced_at = ?, last_error = ?, updated_at = ?
WHERE id = 1
`

type UpdateTwitterSyncConfigParams struct {
	Enabled      int64
	Username     sql.NullString
	UserID       sql.NullString
	StartDate    sql.NullString
	SyncSchedule string
	SinceID      sql.NullString
	LastSyncedAt sql.NullInt64
	LastError    sql.NullString
	UpdatedAt    int64
}

// Admin update: full overlay of the permitted twitter_sync params. The
// handler pre-computes the cursor reset (username/start_date change clears
// since_id/last_synced_at/last_error; username change also clears user_id).
func (q *Queries) UpdateTwitterSyncConfig(ctx context.Context, arg UpdateTwitterSyncConfigParams) error {
	_, err := q.db.ExecContext(ctx, updateTwitterSyncConfig,
		arg.Enabled,
		arg.Username,
		arg.UserID,
		arg.StartDate,
		arg.SyncSchedule,
		arg.SinceID,
		arg.LastSyncedAt,
		arg.LastError,
		arg.UpdatedAt,
	)
	return err
}
