-- Subscriber queries (plan T16, section 4.6). Timestamps are unix seconds.

-- name: GetSubscriberByID :one
SELECT * FROM subscribers WHERE id = ?;

-- name: GetSubscriberByEmail :one
SELECT * FROM subscribers WHERE email = ?;

-- name: GetSubscriberByConfirmationToken :one
SELECT * FROM subscribers WHERE confirmation_token = ?;

-- name: GetSubscriberByUnsubscribeToken :one
SELECT * FROM subscribers WHERE unsubscribe_token = ?;

-- Tokens are generated by the caller: Subscriber#generate_tokens only fills
-- blanks (||=), so imports can keep pre-set tokens.
-- name: CreateSubscriber :one
INSERT INTO subscribers (email, confirmation_token, unsubscribe_token, created_at, updated_at)
VALUES (?, ?, ?, ?, ?) RETURNING *;

-- Subscriber#confirm!: update(confirmed_at:) unless confirmed? (the caller
-- checks the current state first).
-- name: ConfirmSubscriber :exec
UPDATE subscribers SET confirmed_at = ?, updated_at = ? WHERE id = ?;

-- Subscriber#unsubscribe!: update(unsubscribed_at:) unless unsubscribed?.
-- name: UnsubscribeSubscriber :exec
UPDATE subscribers SET unsubscribed_at = ?, updated_at = ? WHERE id = ?;

-- Re-subscribe of an unsubscribed address (SubscriptionsController#create):
-- confirmation state resets and a fresh confirmation token is issued.
-- name: ResetSubscriberForResubscribe :exec
UPDATE subscribers SET confirmed_at = NULL, unsubscribed_at = NULL, confirmation_token = ?, updated_at = ?
WHERE id = ?;

-- name: DeleteSubscriber :exec
DELETE FROM subscribers WHERE id = ?;

-- has_many :subscriber_tags, dependent: :destroy.
-- name: DeleteSubscriberTagsBySubscriberID :exec
DELETE FROM subscriber_tags WHERE subscriber_id = ?;

-- subscriber.tags = tags replaces the set; ON CONFLICT absorbs duplicate
-- tag ids inside one assignment.
-- name: AddSubscriberTag :exec
INSERT INTO subscriber_tags (subscriber_id, tag_id, created_at, updated_at) VALUES (?, ?, ?, ?)
ON CONFLICT(subscriber_id, tag_id) DO NOTHING;

-- subscriber.tags in association (join-row insertion) order.
-- name: ListTagsForSubscriber :many
SELECT tags.* FROM tags
JOIN subscriber_tags ON subscriber_tags.tag_id = tags.id
WHERE subscriber_tags.subscriber_id = ?
ORDER BY subscriber_tags.id;

-- Admin index status filter (apply_status_filter); the tag filter and the
-- 30-per-page window are applied by the caller over this ordered list.
-- name: ListAdminSubscribers :many
SELECT * FROM subscribers
WHERE (sqlc.arg(status) = '' OR
  (sqlc.arg(status) = 'active' AND confirmed_at IS NOT NULL AND unsubscribed_at IS NULL) OR
  (sqlc.arg(status) = 'unconfirmed' AND confirmed_at IS NULL) OR
  (sqlc.arg(status) = 'unsubscribed' AND confirmed_at IS NOT NULL AND unsubscribed_at IS NOT NULL))
ORDER BY created_at DESC;

-- Tag-filter candidates: subscribers carrying one given tag.
-- name: ListSubscriberIDsByTagID :many
SELECT subscriber_id FROM subscriber_tags WHERE tag_id = ?;

-- Subscribers with no tags (left_joins(:tags).where(tags: { id: nil })).
-- name: ListSubscriberIDsWithoutTags :many
SELECT id FROM subscribers WHERE NOT EXISTS (
  SELECT 1 FROM subscriber_tags WHERE subscriber_tags.subscriber_id = subscribers.id
);
